namespace Idera.SQLdm.Common
{
    public static class HelpTopics
    {
        //[START]: SQLdm9.0 (Gaurav Karwal): unused urls/properties
        public const string AddServersWizardBaseline = @"Configure baseline collection.htm";
        public const string ServerDashboardViewActiveSessions = @"Active Sessions.htm";
        public const string ServerDashboardViewActiveSessionsAlert = @"Active Sessions Alert.htm";
        public const string ServerDashboardViewDiskSpaceUsedAlert = @"Percent SQL Server Database.htm";
        public const string ServerDashboardViewDiskUsageGraph = @"Percentage of Disk in Use.htm";
        public const string ServerDashboardViewLogSpaceUsedAlert = @"Percent of SQL Server Alert.htm";
        public const string ServerDashboardViewMemoryPagingAlert = @"Memory Paging Alert.htm";
        public const string ServerDashboardViewMemoryPagingChart = @"Memory Paging Chart.htm";
        public const string ServerDashboardViewOsCpuUsage = @"Total CPU Usage.htm";
        public const string ServerDashboardViewOsCpuUsageAlert = @"CPU Usage Alert.htm";
        public const string ServerDashboardViewOsCpuUsageChart = @"CPU Usage.htm";
        public const string ServerDashboardViewOsMemoryUsageAlert = @"Total Memory Usage Alert.htm";
        public const string ServerDashboardViewResponseTimeChart = @"Response Time Chart.htm";
        //[END]: SQLdm9.0 (Gaurav Karwal): unused urls/properties

        
        
        public const string IderaWikiBaseURL = @"http://wiki.idera.com";
        public const string IderaWikiSubfolder = @"x";

        public const string SQLdmMobileNewsfeedRequirements = @"IwA1";
        public const string SQLdmMobileNewsfeedInstallationRequirements = @"JAA1";
        public const string AlertAlwaysOnRedoRate = @"RAE1";
        public const string ActiveAlertsView = @"YwA1";
        public const string ActivityTimelineview = @"qAA1";
        public const string AddActionProviderWizard = @"wwA1";
        public const string AddActionProviderWizardType = @"xAA1";
        public const string AlertOSCPUUserTime = @"fwE1";
        public const string AddActionProviderWizardSNMP = @"xgA1";
        public const string AddActionProviderWizardSMTP = @"xQA1";
        public const string AddJobStepFilter = @"uQA1";
        public const string AddPermissionWizard = @"AgE1";
        public const string AddPermissionWizardUser = @"AwE1";
        public const string TasksView = @"DgNJAg";
        public const string AddPermissionWizardPermission = @"BAE1";
        public const string AddPermissionWizardServers = @"BQE1";
        public const string AddPermissionWizardSummary = @"BgE1";
        public const string ServerDashboardViewBlockedSessionsAlert = @"SwE1";
        public const string AddServersWizard = @"LAA1";
        public const string AddServersWizard_ServerTypeSelection = @"KIE3Aw";
        public const string AddServersWizardWMI = @"MAA1";
        public const string AddServersWizardCollect = @"LwA1";
        public const string AddServersWizardConfig = @"LQA1";
        public const string AddServersWizardSelect = @"LgA1";
        public const string AdministrationView = @"fICXAg";//SQLdm 9.1 (Vineet Kumar) (Community Integration) -- Changed wiki help links
        public const string AdvancedAlertConfig_Smoothing = @"sQA1";
        public const string AdvancedAlertConfig_DatabaseExclustions = @"mwGfAg";        //SQLdm 9.1 (Abhishek Joshi) -Wiki Links --Change the tiny URL for 'Configure alert filters- database exclusions' topic 
        public const string AdvancedAlertConfig_JobExclusions = @"tgA1";
        public const string AdvancedAlertConfig_SessionExclusions = @"twA1";
        public const string AdvancedAlertConfig_DiskDriveExclusions = @"sgA1";
        public const string AdvancedAlertConfig_CustomCounterOptions = @"uAA1";
        public const string AdvancedAlertConfig_ConfigureSizeRemaining = @"tAA1";
        public const string AdvancedAlertConfig_TextAndExpression = @"swA1";
        public const string AdvancedAlertConfig_ConfigureAlertDuration = @"sAA1";
        public const string AdvancedQueryMonitorConfigurationDialog = @"bgA1";
        public const string AlertRecommendationsDialog = @"bgDKAg";//Updated wiki link -- SQLdm 10.0 (Ankit Nagpal)
        public const string AlertRecommendationsOptionsDialog = @"RQDKAg";//Updated wiki link -- SQLdm 10.0 (Ankit Nagpal)
        public const string AlertsConfiguration = @"qgA1";
        public const string AlertsView = @"vwA1";
        public const string ApplicationSecurityView = @"AQE1";
        public const string ChangeLogHelp = @"CQE1";
        public const string ConfigureCustomView = @"EgA1";
        public const string ConfigureEmailSettings = @"xQA1";
        public const string ConfigureLogs = @"pwA1";
        public const string ConfigureBaselineDialog = @"awA1";
        public const string ConfigureNotificationRulesAndProviders = @"NYH-Ag";//Updated wiki link -- SQLdm 10.0 (Ankit Nagpal)
        public const string ConfigureRepositoryConnection = @"KwA1";
        public const string ConsoleOptions = @"NAA1";
        public const string CustomCountersAdministration = @"FYCDAg";//SQLdm 9.1 (Vineet Kumar) (Community Integration) -- Changed wiki help links
        public const string CustomCountersDelete = @"RAA1";
        public const string CustomCountersLink = @"boCXAg";//SQLdm 9.1 (Vineet Kumar) (Community Integration) -- Changed wiki help links
        public const string CustomCountersTest = @"RQA1";
        public const string CustomCountersWizardAdd = @"OgA1";
        public const string CustomCountersWizardConfigureAlertSettings = @"QgA1";
        public const string CustomCountersWizardCustomizeCounterDefinition = @"QQA1";
        public const string CustomCountersWizardCustomizeCounterValue = @"QAA1";
        public const string CustomCountersWizardEdit = @"QwA1";
        public const string CustomCountersWizardImport = @"GYCDAg";//SQLdm 9.1 (Vineet Kumar) (Community Integration) -- Adedd wiki help links
        public const string CustomCountersWizardProvideSQLCounter = @"PgA1";
        public const string CustomCountersWizardSelectCounterType = @"OwA1";
        public const string CustomCountersWizardSelectSQLCounter = @" PQA1";
        public const string CustomCountersWizardSelectSystemCounter = @" PAA1";
        public const string CustomCountersWizardSelectVMCounter = @" PwA1";
        public const string CustomReportsWizard = @"SADoAg";//Updated wiki link custom reports-- SQLdm 10.0 (Ankit Nagpal)
        public const string CustomReportsWizardImport = @"rICXAg";//SQLdm 9.1 (Vineet Kumar) (Community Integration) -- Adedd wiki help links
        public const string CustomReportsWizardSelectReport = @" -QA1";
        public const string CustomReportsWizardSelectCounters = @" PgDoAg";//Updated wiki link -- SQLdm 10.0 (Ankit Nagpal)
        public const string CustomReportsWizardAggregateCounters = @" -wA1";
        public const string CycleLogs = @" pgA1";
        public const string DatabaseBrowser = @"EgE1";
        public const string DatabasesBackupsAndRestoresView = @" mQA1";
        public const string DatabasesConfigurationView = @" kgA1";
        public const string DatabasesFilesView = @" lAA1";
        public const string DatabasesSummaryView = @" jgA1";
        public const string DatabasesAlwaysOnView = @" jwA1";
        public const string DatabasesMirroringView = @" nQA1";
        public const string DatabasesTablesAndIndexesView = @" mgA1";
        public const string DatabasesTempdbView = @" kAA1";
        public const string ConfigureAlertTemplates = @"NwCLAg";//SQLdm 9.1 (Vineet Kumar) (Community Integration) -- Changed wiki help links
        public const string AlertTemplatesWizardImport = @"U4CXAg";//SQLdm 9.1 (Vineet Kumar) (Community Integration) -- Adedd wiki help links
        public const string DefaultAlertsConfiguration = @"doCXAg";//SQLdm 9.1 (Vineet Kumar) (Community Integration) -- Changed wiki help links
        public const string EnablingOsMetricsMonitoring = @" dQA1";
        public const string EditConfigurationValue = @" YgA1";
        public const string GettingStartedWithSQLdm = @" CQA1";
        public const string GroomingOptions = @" OAA1";
        public const string HelpStartPage = @" CQA1";
        public const string HelpSubFolder = @"SQLdm";
        public const string HistoryBrowserOptionsDialogHelp = @"jwI2B"; //SqlDM 10.2 (Anshul Aggarwal) - Wiki help link for histor browser console options.
        public const string HowToTopic1 = @" NYH-Ag";//Updated wiki link -- SQLdm 10.0 (Ankit Nagpal)
        public const string HowToTopic2 = @" SwA1";
        public const string HowToTopic3 = @" jQA1";
        public const string HowToTopic4 = @" yAA1";
        public const string ImportExportHelp = @"M4H-Ag";//Added wiki link -- SQLdm 10.0 (Ankit Nagpal)
        public const string Licensing = @" DAE1";
        public const string LogsView = @" owA1";
        public const string ManageServers = @" DwE1";
        public const string NewNotificationRule = @" iQDKAg";//Updated wiki link -- SQLdm 10.0 (Ankit Nagpal)
        public const string PermissionDialogGeneral = @" BwE1";
        public const string PermissionDialogServers = @" CAE1";
        public const string QueriesView = @" gAA1";
        public const string QueriesViewSigMode = @" hQDKAg";//Updated wiki link -- SQLdm 10.0 (Ankit Nagpal)
        public const string QueriesViewStmtMode = @" gwDKAg";//Updated wiki link -- SQLdm 10.0 (Ankit Nagpal)
        public const string QueriesViewHistory = @" hwDKAg";//Updated wiki link -- SQLdm 10.0 (Ankit Nagpal)
        public const string RebuildIndexes = @" nAA1";
        public const string ResourcesCpuView = @" hwA1";
        public const string ResourcesDiskView = @" iQA1";
        public const string ResourcesMemoryView = @" iAA1";
        public const string ResourcesProcedureCacheView = @" iwA1";
        public const string ResourcesSummaryView = @" hgA1";
        public const string ResourcesWaitsStatsView = @" jAA1";
        public const string ResourcesQueryWaitsView = @" hAA1";
        public const string ResourcesFileActivityView = @" igA1";
        public const string ResourcesQueryWaitsviewBackup = @" NwE1";
        public const string ResourcesQueryWaitsviewMemory = @" OgE1";
        public const string ResourcesQueryWaitsviewIO = @" OAE1";
        public const string ResourcesQueryWaitsviewLock = @" OQE1";
        public const string ResourcesQueryWaitsviewTransactionLog = @" PgE1";
        public const string ResourcesQueryWaitsviewNonPageLatch = @" PAE1";
        public const string ResourcesQueryWaitsviewNonIOPageLatch = @" OwE1";
        public const string ResourcesQueryWaitsviewOther = @" PQE1";
        public const string SearchLogs = @" pQA1";
        public const string ServerConfigurationView = @"YQA1";
        public const string ServerDashboardView = @"TgA1";
        public const string ServerDashboardViewNeedMoreHelp = @"qQA1";
        public const string ServerDashboardViewBatchesReceived = @"LwE1";
        public const string ServerDashboardViewBlockedSessions = @"FQE1";
        public const string ServerDashboardViewBufferCacheHitRatio = @"FgE1";
        public const string ServerDashboardViewClientComputers = @"FwE1";
        public const string ServerDashboardViewClientComputersAlert = @"TQE1";
        public const string ServerDashboardViewDatabasesStatus = @"kwA1";
        public const string ServerDashboardViewDatabasesStatusAlert = @"VQE1";
        public const string ServerDashboardViewDiskQueueLength = @"GwE1";
        public const string ServerDashboardViewDiskQueueLengthAlert = @"cwE1";
        public const string ServerDashboardViewDiskReadsWrites = @"KwE1";
        public const string ServerDashboardViewDiskSpaceUsed = @"KQE1";
        public const string ServerDashboardViewLogFlushes = @"HwE1";
        public const string ServerDashboardViewLogSpaceUsed = @"KgE1";
        public const string ServerDashboardViewMemoryPaging = @"IQE1";
        public const string ServerDashboardViewOsMemoryUsage = @"NAE1";
        public const string ServerDashboardViewPacketsSentReceived = @"JQE1";
        public const string ServerDashboardViewProcedureCacheHitRatio = @"gQE1";
        public const string ServerDashboardViewProcessorQueueLength = @"LAE1";
        public const string ServerDashboardViewProcessorQueueLengthAlert = @"fQE1";
        public const string ServerDashboardViewResponseTimeAlert = @"kQE1";
        public const string ServerDashboardViewResponseTimeGraph = @"MwE1";
        public const string ServerDashboardViewSqlCpuUsage = @"MAE1";
        public const string ServerDashboardViewSqlCpuUsageAlert = @" jAE1";
        public const string ServerDashboardViewSqlMemoryUsage = @"MgE1";
        public const string ServerDashboardViewSqlMemoryUsageAlert = @"kAE1";
        public const string SelectDashboardLayoutView = @"UQA1";
        public const string ServerDashboardViewDesignMode = @"UAA1";
        public const string ServerDashboardSave = @"UgA1";
        public const string ServerDashboardViewCachePanel = @"UwA1";
        public const string ServerDashboardViewCachePanelAreas = ServerDashboardViewCachePanel + @"#CacheAreas";
        public const string ServerDashboardViewCachePanelHitRatios = ServerDashboardViewCachePanel + @"#CacheHitRatios";
        public const string ServerDashboardViewCachePanelPageLife = ServerDashboardViewCachePanel + @"#CachePageLife";
        public const string ServerDashboardViewCpuPanel = @"VAA1";
        public const string ServerDashboardViewCpuPanelCallRates = ServerDashboardViewCpuPanel + @"#CPUCallRates";
        public const string ServerDashboardViewCpuPanelQueueLength = ServerDashboardViewCpuPanel + @"#CPUProcQueueLength";
        public const string ServerDashboardViewCpuPanelUsage = ServerDashboardViewCpuPanel + @"#CPUUsage";
        public const string ServerDashboardViewCustomCountersPanel = @"VQA1";
        public const string ServerDashboardViewDatabasesPanel = @"VgA1";
        public const string ServerDashboardViewDatabasesPanelIoStall = ServerDashboardViewDatabasesPanel + @"#DBIOStall";
        public const string ServerDashboardViewDatabasesPanelLogFlushes = ServerDashboardViewDatabasesPanel + @"#DBLogFlushes";
        public const string ServerDashboardViewDatabasesPanelReads = ServerDashboardViewDatabasesPanel + @"#DBReads";
        public const string ServerDashboardViewDatabasesPanelTrans = ServerDashboardViewDatabasesPanel + @"#DBTransactions";
        public const string ServerDashboardViewDatabasesPanelWrites = ServerDashboardViewDatabasesPanel + @"#DBWrites";
        public const string ServerDashboardViewDiskPanel = @"VwA1";
        //6.2.4
        public const string ServerDashboardViewAzureDiskPanel = @"VwA1";
        public const string ServerDashboardViewAzureDiskPanelRate = ServerDashboardViewAzureDiskPanel + @"#DiskRate";
        public const string ServerDashboardViewAzureDiskPanelUsage = ServerDashboardViewAzureDiskPanel + @"#DiskUsage";


        public const string ServerDashboardViewDiskPanelLatency = ServerDashboardViewDiskPanel + @"#DiskLatency";
        public const string ServerDashboardViewDiskPanelPhysicalIo = ServerDashboardViewDiskPanel + @"#DiskPhysicalIO";
        public const string ServerDashboardViewDiskPanelThroughput = ServerDashboardViewDiskPanel + @"#DiskThroughput";
        public const string ServerDashboardViewFileActivityPanel = @"WAA1";
        public const string ServerDashboardViewFileActivityPanelReads = ServerDashboardViewFileActivityPanel + @"#FileActivityReads";
        public const string ServerDashboardViewFileActivityPanelWrites = ServerDashboardViewFileActivityPanel + @"#FileActivityWrites";
        public const string ServerDashboardViewFileActivityPanelTransfers = ServerDashboardViewFileActivityPanel + @"#FileActivityTransfers";
        public const string ServerDashboardViewFileActivityPanelNoData = ServerDashboardViewFileActivityPanel + @"#FileActivityNoData";
        public const string ServerDashboardViewLocksPanel = @"WQA1";
        public const string ServerDashboardViewLocksPanelWaits = ServerDashboardViewLocksPanel + @"#LocksNumber";
        public const string ServerDashboardViewMemoryPanel = @"WgA1";
        public const string ServerDashboardViewMemoryPanelPaging = ServerDashboardViewMemoryPanel + @"#MemoryPaging";
        public const string ServerDashboardViewMemoryPanelUsage = ServerDashboardViewMemoryPanel + @"#MemoryUsage";
        public const string ServerDashboardViewNetworkPanel = @" WwA1";
        public const string ServerDashboardViewNetworkPanelResponseTime = ServerDashboardViewNetworkPanel + @"#NetworkResponseTime";
        public const string ServerDashboardViewNetworkPanelThroughput = ServerDashboardViewNetworkPanel + @"#NetworkThroughput";
        public const string ServerDashboardViewServerWaitsPanel = @"XAA1";
        public const string ServerDashboardViewServerWaitsPanelWaits = ServerDashboardViewServerWaitsPanel + @"#ServerWaitsSummary";
        public const string ServerDashboardViewSessionsPanel = @"XQA1";
        public const string ServerDashboardViewSessionsPanelClients = ServerDashboardViewSessionsPanel + @"#SessionsClients";
        public const string ServerDashboardViewSessionsPanelSessions = ServerDashboardViewSessionsPanel + @"#SessionsActivityBlocking";
        public const string ServerDashboardViewTempDBPanel = @"XgA1";
        public const string ServerDashboardViewTempDBPanelUsage = ServerDashboardViewTempDBPanel + @"#TempdbSpaceUsedOverTime";
        public const string ServerDashboardViewTempDBPanelContention = ServerDashboardViewTempDBPanel + @"#TempdbContention";
        public const string ServerDashboardViewTempDBPanelVersionStore = ServerDashboardViewTempDBPanel + @"#VersionStoreCleanupRate";
        public const string ServerDashboardViewVMPanel = @"XwA1";
        public const string ServerDashboardViewVMPanelMemory = ServerDashboardViewVMPanel + @"#VirtualizationMemoryUsage";
        public const string ServerDashboardViewVMPanelCpu = ServerDashboardViewVMPanel + @"#VirtualizationCPUReady";
        public const string ServerDashboardViewVMPanelDisk = ServerDashboardViewVMPanel + @"#VirtualizationDiskUsage";
        public const string ServerDetailsView = @"YAA1";
        public const string AnalysisView = @" eADKAg";
        public const string ServerGroupView = @"EgA1";
        public const string ServerGroupPropertiesView = @"EwA1";
        public const string ServerPropertiesGeneral = @"agA1";
        public const string ServerPropertiesQueryMonitor = @"bQA1";
        public const string ServerPropertiesActivityMonitor = @"sYCXAg";  //SQLdm 9.1 (Abhishek Joshi) -Wiki Links --Change the tiny URL for 'Set activity monitor options' topic
        public const string ServerPropertiesAnalysisConfiguration = @"jQDKAg";
        public const string ServerSettings = @"DwD6Ag";//Added wiki link for server settings -- SQLdm 10.0 (Ankit Nagpal)
        public const string BaselineAssistant = @"cwDKAg";//Added wiki link for baseline assistant -- SQLdm 10.0 (Ankit Nagpal)
        public const string ServerPropertiesReplication = @"cAA1";
        public const string ServerPropertiesTableStatistics = @"cQA1";
        public const string ServerPropertiesDiskStatistics = @"dgA1";
        public const string ServerPropertiesOleAutomation = @"dQA1";
        public const string ServerPropertiesClusterSettings = @"dwA1";
        public const string ServerPropertiesWaitMonitoring = @"eAA1";
        public const string ServerPropertiesVirtualization = @"egA1";
        public const string ServerPropertiesBaseline = @"cQDKAg";//Updated wiki link -- SQLdm 10.0 (Ankit Nagpal)
        public const string ServerPropertiesBaselineApplyToOthers = @"bAA1";
        public const string ServicesFullTextSearchView = @"oQA1";
        public const string ServicesReplicationView = @"ogA1";
        public const string ServicesSqlAgentJobsView = @"oAA1";
        public const string ServicesSummaryView = @"8wKfAg";     //SQLdm 9.1 (Abhishek Joshi) -Wiki Links --Change the tiny URL for 'Monitor services' topic
        public const string SessionsBlockingView = @"fwA1";
        public const string SessionsDetailsView = @"fQA1";
        public const string SessionsLocksView = @"fgA1";
        public const string SessionsSummaryView = @"fAA1";
        public const string SnoozeAlertsDialog = @"ZgA1";
        public const string SQLdmSystemDiagnostics = @"pwE1";
        public const string SQLdmTodayView = @"CoCDAg";//SQLdm 9.1 (Vineet Kumar) (Community Integration) -- Changed wiki help links
        public const string SqlServerBrowser = @"EQE1";
        public const string UpdateIndexStatistics = @"mwA1";
        public const string ViewFilters = @"EAA1";
        public const string WmiConnectionError = @"twE1";
        public const string MaintenanceMode = @"dAA1";
        public const string AlertsConfigurationBlueBar = @"awDKAg";//Updated wiki link -- SQLdm 10.0 (Ankit Nagpal)
        public const string VirtualizationConfig = @"MgA1";
        public const string vCenterConnection = @"MwA1";
        public const string AlertDefault = @"egGfAg";         //SQLdm 9.1 (Abhishek Joshi) -Wiki Links --Change the tiny URL for 'Metric Alerts' topic
        public const string AlertLastBackup = @"iABJAw";
        public const string AlertGroomingTimedOut = @"WgRyAg";
        public const string AlertMaintenanceMode = @"ZwE1";
        public const string AlertDiskQueueLength = @"dAE1";
        public const string AlertDiskTimePercent = @"dwE1";
        public const string AlertOSDiskPhysicalDiskTimePctPerDisk = @"eAE1";
        public const string AlertMemoryPaging = @"ewE1";
        public const string AlertUserConnections = @"mAE1";
        public const string AlertDataUsed = @"jQE1";
        public const string AlertLogUsed = @"jwE1";
        public const string AlertDatabaseReadWriteError = @"VAE1";
        public const string AlertDatabaseStatus = @"VQE1";
        public const string AlertDatabaseSize = @"UgE1";
        public const string AlertTransLogSize = @"ZAE1";
        public const string AlertReorganisation = @"lAE1";
        public const string AlertCLRStatus = @"B4CQAg";        //SQLdm 9.1 (Abhishek Joshi) -Wiki Links --Change the tiny URL for 'Default Alert IDs' topic
        // SQLdm 10.2.2 (Varun Chopra) SQLDM-19310 'Show Alert Help' link for 'CLR Enabled' metric takes you to the wrong link.
        public const string AlertCLRStatusUpdated = @"TgE1";
        public const string Display = @"Display";
        public const string Sqldm = @"SQLDM";
        public const string AlertOleAutomationStatus = @"cgE1";
        public const string AlertOSMetricStatus = @"egE1";
        public const string AlertAgentXPStatus = @"iwE1";
        public const string AlertWMIStatus = @"pAE1";
        public const string AlertQueryMonitorStatus = @"ggE1";
        public const string AlertOSDiskFull = @"wQKfAg";         //SQLdm 9.1 (Abhishek Joshi) -Wiki Links --Change the tiny URL for 'OS Disk Full (Percent) alert' topic
        public const string AlertOSMemoryUsage = @"eQE1";
        public const string AlertOSCPUPrivilegedTime = @"fAE1";
        public const string AlertClientComputers = @"TQE1";
        public const string AlertOldestOpenTrans = @"cQE1";
        public const string AlertSessionCPU = @"gwE1";
        public const string AlertFullTextServiceStatus = @"YAE1";
        public const string AlertNonDistributedTrans = @"cAE1";
        public const string AlertAgentJobCompletion = @"hQE1";
        public const string AlertAgentJobFailures = @"hgE1";
        public const string AlertAgentLongRunningJobsInMinutes = @"iAE1";
        public const string AlertAgentLongRunningJobsPercent = @"iQE1";
        public const string AlertAgentServiceStatus = @"igE1";
        public const string AlertSQLServiceStatus = @"kgE1";
        public const string AlertNonSubscribedTransNum = @"lgE1";
        public const string AlertNonSubscribedTransTime = @" lwE1";
        public const string AlertBlocking = @"TAE1";
        public const string AlertOSCPUProcessorQueueLength = @" fQE1";
        public const string AlertOSCPUUsage = @"fgE1";
        public const string AlertSQLCPUUsage = @"MAE1";//JSFIX
        public const string AlertSQLMemoryUsage = @"kAE1";
        public const string AlertDTCServiceStatus = @"WwE1";
        public const string AlertBlockedSessions = @"SwE1";
        public const string AlertServerResponseTime = @"kQE1";
        public const string AlertMirrorCommitOverhead = @"aAE1";
        public const string AlertMirroredServerRoleChange = @"aQE1";
        public const string AlertMirroringOldestUnsent = @"agE1";
        public const string AlertMirroringSessionPreferredRole = @"awE1";
        public const string AlertMirroringStatus = @"bAE1";
        public const string AlertMirroringUnrestoredLog = @"bQE1";
        public const string AlertMirroringUnsentLog = @"bgE1";
        public const string AlertMirroringWitnessConnection = @"bwE1";
        public const string AlertSQLServerErrorLog = @"jgE1";
        public const string AlertSQLServerAgentLog = @"hwE1";
        public const string AlertDeadlock = @"VgE1";
        public const string AlertPageLifeExpectancy = @"gAE1";
        public const string AlertProcCacheHitRatio = @"gQE1";
        public const string AlertClusterActiveNode = @"TwE1";
        public const string AlertClusterFailover = @"UAE1";
        public const string AlertReplicationDistributionLatency = @"WgE1";
        public const string AlertAvgDiskSecPerRead = @"SAE1";
        public const string AlertAvgDiskSecPerWrite = @"SgE1";
        public const string AlertAvgDiskSecPerTransfer = @"SQE1";
        public const string AlertAvgDiskReadsPerSecond = @"VwE1";
        public const string AlertAvgDiskTransfersPerSecond = @"WAE1";
        public const string AlertAvgDiskWritesPerSecond = @"WQE1";
        public const string AlertVersionStoreGenerationRatio = @"mQE1";
        public const string AlertVersionStoreSize = @"mgE1";
        public const string AlertLongRunningVersionStoreTransaction = @"ZgE1";
        public const string AlertSessionTempdbSpaceUsage = @"hAE1";
        public const string AlertTempdbContention = @"lQE1";
        public const string AlertLogFileAutogrow = @"YwE1";
        public const string AlertDataFileAutogrow = @"UQE1";
        public const string AlertSQLdmServiceStatus = @"kwE1";
        public const string AlertESXCPUUtilization = @"XAE1";
        public const string AlertESXMemorySwapDetected = @"XQE1";
        public const string AlertESXMemoryUsage = @"XgE1";
        public const string AlertESXPowerState = @"XwE1";
        public const string AlertVMCPUReadyWaitTime = @"mwE1";
        public const string AlertVMCPUUsage = @"nAE1";
        public const string AlertVMHostServerChange = @"nQE1";
        public const string AlertVMMemorySwapDelayDetected = @"ngE1";
        public const string AlertVMMemoryUsagePercent = @"nwE1";
        public const string AlertVMPowerState = @"oAE1";
        public const string AlertVMReclaimedBalloonedMemory = @"oQE1";
        public const string AlertVMResourceConfigurationChange = @"ogE1";
        public const string AlertVMResourceLimitsDetected = @"owE1";
        public const string AlertDatabaseFullSize = @"UwE1";
        public const string AlertTranLogFullSize = @"ZQE1";
        public const string AlertOsDiskFreeSize = @"dQE1";
        public const string AlertAlwaysOnEstimatedDataLossTime = @"QAE1";
        public const string AlertAlwaysOnEstimatedRecoveryTime = @"QQE1";
        public const string AlertAlwaysOnLogSendQueueSize = @"QgE1";
        public const string AlertAlwaysOnRedoQueueSize = @"QwE1";
        public const string AlertAlwaysOnAvailabilityGroupRoleChange = @"RQE1";
        public const string AlertAlwaysOnSynchronizationHealthState = @"RgE1";
        public const string AlertAlwaysOnSynchronizationPerformance = @"RwE1";
        public const string AlertAlwaysOnPreferredNode = @"1gBJAg";

        public const string ReportsView = @"yAA1";
        public const string ReportFilters = @"yQA1";
        public const string ReportsActiveAlerts = @"zgA1";
        public const string ReportsAlertHistory = @"3wA1";
        public const string ReportsDatabaseGrowthForecast = @"9AA1";
        public const string ReportsDatabaseMirroringHistory = @"5QA1";
        public const string ReportsDatabaseMirroringSummary = @"zwA1";
        public const string ReportsDatabaseStatistics = @"4wA1";
        public const string ReportsDiskSpaceUsageForecast = @"8wA1";
        public const string ReportsEnterpriseSummary = @"zAA1";
        public const string ReportsQueryOverview = @"3AA1";
        public const string ReportsQueryStatistics = @"3gA1";
        public const string ReportsServerInventory = @"2wA1";
        public const string ReportsServerStatistics = @"2gA1";
        public const string ReportsServerSummary = @"zQA1";
        public const string ReportsTableGrowthForecast = @"9QA1";
        public const string ReportsTopDatabases = @"4gA1";
        public const string ReportsTopDatabaseApplications = @"5AA1";
        public const string ReportsTopQueries = @"3QA1";
        public const string ReportsTopServers = @"2QA1";
        public const string ReportsTopTablesByGrowth = @"5gA1";
        public const string ReportsTopTablesByFragmentation = @"5wA1";
        public const string ReportsSessionStatistics = @"7AA1";
        public const string ReportsMemoryStatistics = @"8QA1";
        public const string ReportsCPUStatistics = @"7QA1";
        public const string ReportsDiskStatistics = @"7wA1";
        public const string ReportsReplicationStatistics = @"8AA1";
        public const string ReportsDeploymentIntroduction = @"9gA1";
        public const string ReportsDeploymentSelectReports = @"9wA1";
        public const string ReportsDeploymentSelectReportServer = @"_AA1";
        public const string ReportsDeploymentScheduleEmail = @"_QA1";
        public const string ReportsDeploymentSummary = @"_gA1";
        public const string ReportsCustom = @"moCXAg";//SQLdm 9.1 (Vineet Kumar) (Community Integration) -- Changed wiki help links
        public const string ReportsMetricThreshold = @"0AA1";
        public const string ReportsDiskDetails = @"7gA1";
        public const string ReportsTempdbStatistics = @"6AA1";
        public const string ReportsVirtualizationStatistics = @"1AA1";
        public const string ReportsVirtualizationSummary = @"0wA1";
        public const string ReportsTransactionLogStatistics = @"6QA1";
        public const string ReportsBaselineStatistics = @"4AA1";
        public const string ReportsChangeLogSummary = @"1gA1";
        public const string ReportsAlwaysOnStatistics = @"6gA1";
        public const string ReportsAlwaysOnTopology = @"0QA1";
        //[START] SQLdm9.0: adding help links for query waits and virtualization section
        public const string ReportsQueryWaitStatistics = @"GANJAg";
        public const string ReportsVirtualizationSection = @"0gA1";
        //[END] SQLdm9.0: adding help links for query waits and virtualization section
        public const string ReportDiskSpaceUsage = @"5QKfAg";            //SQLdm 9.1 (Abhishek Joshi) -Wiki Links --Add the tiny URL for Disk Space Usage (report)
        public const string ReportDiskSpaceHistory = @"6QKfAg";          //SQLdm 9.1 (Abhishek Joshi) -Wiki Links --Add the tiny URL for Disk Space History (report)
        public const string TagsAddTag = @"SQA1";
        public const string TagsAddServersSelectTags = @"MQA1";
        public const string TagsManageTags = @"SAA1";
        public const string TagsServerPropertiesCustomCounters = @"cwA1";
        public const string TagsTagProperties = @"SgA1";
        public const string TableStatisticsDatabaseExclude = @"cgA1";
        public const string AlertForecast = @"ZQA1";
        public const string AlertForecasting = @"ZAA1";
        public const string InstanceThresholdsDatabase = @"rQA1";
        public const string InstanceThresholdsDisk = @"rgA1";
        //START: SQLdm 9.1 (Abhishek Joshi) -Wiki Links --Added wiki help links for new alerts and disk size view
        public const string ResourcesDiskSizeView = @"qYCXAg";
        public const string AlertFilegroupPercent = @"fgGfAg";
        public const string AlertFilegroupSize = @"ggGfAg";
        public const string AlertSQLActiveDirectoryHelper = @"_QKfAg";
        public const string AlertSQLBrowser = @"-AKfAg";
        //END: SQLdm 9.1 (Abhishek Joshi) -Wiki Links --Added wiki help links for new alerts and disk size view
        public const string ReportTemplateComparison = @"1Qg1";
        public const string ReportAlertThreshold = @"2Qg1";
        public const string ReportAlertTemplate = @"3Qg1";
        public static string DiskBrowser { get; set; }
    }
}
