//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idera.SQLdm.ImportWizard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Idera.SQLdm.ImportWizard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Check {
            get {
                object obj = ResourceManager.GetObject("Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon data_into {
            get {
                object obj = ResourceManager.GetObject("data_into", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_into_49 {
            get {
                object obj = ResourceManager.GetObject("data_into_49", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred while running the SQL diagnostic manager Import Wizard..
        /// </summary>
        internal static string ExceptionUnhandled {
            get {
                return ResourceManager.GetString("ExceptionUnhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL diagnostic manager Import Wizard.
        /// </summary>
        internal static string ImportWizardTitle {
            get {
                return ResourceManager.GetString("ImportWizardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL diagnostic manager Import Wizard was started with one or more  invalid command line parameter.   The valid parameters are:.
        /// </summary>
        internal static string InvalidCommandLineParamsError {
            get {
                return ResourceManager.GetString("InvalidCommandLineParamsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified import date is greater than the last import or registration date for some of the Servers. Data will not be imported for these Servers. Do you want to continue?.
        /// </summary>
        internal static string InvalidImportDateWarn {
            get {
                return ResourceManager.GetString("InvalidImportDateWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To browse for a database, you must first specify a server name..
        /// </summary>
        internal static string NoServerForDbBrowsingError {
            get {
                return ResourceManager.GetString("NoServerForDbBrowsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click on the notification icon to see import progress..
        /// </summary>
        internal static string NotifyClickHereForProgress {
            get {
                return ResourceManager.GetString("NotifyClickHereForProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you select SQL Server authentication, you must specify user name and password..
        /// </summary>
        internal static string NoUserPwdForSqlAuthError {
            get {
                return ResourceManager.GetString("NoUserPwdForSqlAuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SQL diagnostic manager installation does not exist on this computer. The Import Wizard imports historical data from SQL diagnostic manager 4.x into the new Repository..
        /// </summary>
        internal static string SQLdmNotInstalledError {
            get {
                return ResourceManager.GetString("SQLdmNotInstalledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer does not have a valid SQL diagnostic manager installation. The Import Wizard imports historical data from SQL diagnostic manager 4.x into the new Repository. If you have a earlier installation, upgrade to 4.0 or later before importing the historical data..
        /// </summary>
        internal static string SQLdmVersionNotSupportedError {
            get {
                return ResourceManager.GetString("SQLdmVersionNotSupportedError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap wiz_margin_image {
            get {
                object obj = ResourceManager.GetObject("wiz_margin_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
