using System;
using System.Collections.Generic;
using System.Text;
using Idera.SQLdm.PrescriptiveAnalyzer.Common.Resources;

namespace Idera.SQLdm.PrescriptiveAnalyzer.Common.Recommendations
{
    /// <summary>
    /// When adding a recommendation type make sure you also enter the FindingId attribute
    /// for it.  This is what ties the recommendation type to a recommendation ID in the 
    /// Recommendation object.  The association is made in the constructor and in the RecommendationType 
    /// setter.  If you must dynamically assign the recommendation ID then you should override the
    /// RecommendationType setter to ensure that ID is not set or is set correctly.
    /// </summary>


    [Serializable]
    public enum RecommendationType
    {
        Unknown,
        [FindingId("SDR-D1")]
        DiskQueueLength48,
        [FindingId("SDR-D2")]
        DiskQueueLength49,
        [FindingId("SDR-D23")]
        ResourceGovernerIOStall,
        [FindingId("SDR-D3")]
        DiskWaiting,
        [FindingId("SDR-D4")]
        DiskQueueLength50,
        [FindingId("SDR-D5")]
        DiskBlockSize,
        [FindingId("SDR-D6")]
        DiskQueueLength52,
        [FindingId("SDR-D7")]
        DiskQueueLength53,
        [FindingId("SDR-D8")]
        DiskNeedSeManageVolumeName,
        [FindingId("SDR-D9")]
        DiskTempDbSizeMismatch,
        [FindingId("SDR-D10")]
        DiskTempDbPresizeSettings,
        [FindingId("SDR-D11")]
        DiskTempDbWaiting,
        [FindingId("SDR-D12")]
        DiskTempDbNotEnoughFiles,
        [FindingId("SDR-D13")]
        DiskTempDbTooManyFiles,
        [FindingId("SDR-D14")]
        DiskEnableCompression,
        [FindingId("SDR-D15")]
        DiskTempDbRecoveryModel,
        [FindingId("SDR-D16")]
        Disk16,
        [FindingId("SDR-D17")]
        FillFactor,
        [FindingId("SDR-D18")]
        Disk18,
        [FindingId("SDR-D19")]
        AutoShrinkEnabled,
        [FindingId("SDR-D20")]
        Disk20,
        [FindingId("SDR-D21")]
        Disk21,
        [FindingId("SDR-D22")]
        DiskTempDbAutogrowth,
        [FindingId("SDR-Q29")]
        AnsiTopEquivalent,
        [FindingId("SDR-Q1")]
        DeallocateCursor,
        [FindingId("SDR-Q2")]
        FastForwardCursor,
        [FindingId("SDR-Q24")]
        FunctionInWhereClause,
        [FindingId("SDR-Q13")]
        HintAbuse,
        [FindingId("SDR-Q16")]
        LeftExpressionInWhereClause,
        [FindingId("SDR-Q17")]
        LikeUseNotNeeded,
        [FindingId("SDR-Q18")]
        NestedMinMax,
        [FindingId("SDR-Q34")]
        NakedInsert,
        [FindingId("SDR-Q22")]
        SelectStarAbuse,
        [FindingId("SDR-Q28")]
        TopVsRowCount,
        [FindingId("SDR-Q8")]
        TwoExpressionCoalesce,
        [FindingId("SDR-Q11")]
        UnfilteredDelete,
        [FindingId("SDR-Q26")]
        UnionSetAbuse,
        [FindingId("SDR-I4")]
        MissingIndex,
        [FindingId("SDR-Q19")]
        NoJoinPredicate,
        [FindingId("SDR-I19")]
        NoColumnStats,
        [FindingId("SDR-I18")]
        MemLimitExceededOld,
        [FindingId("SDR-N1")]
        NetCardLost,
        [FindingId("SDR-N2")]
        NetBandwidthLost,
        [FindingId("SDR-N4")]
        NetRetranSegs,
        [FindingId("SDR-N5")]
        NetRedirectorErrors,
        [FindingId("SDR-N9")]
        NetCardErrors,
        [FindingId("SDR-N3")]
        NetCongestion,
        [FindingId("SDR-N6")]
        NetSSLEncryption,
        [FindingId("SDR-N7")]
        NetNoCount,
        [FindingId("SDR-N8")]
        NetRedundantCards,
        [FindingId("SDR-I5")]
        DisabledIndex,
        [FindingId("SDR-I7")]
        HypotheticalIndex,
        [FindingId("SDR-I2")]
        FragmentedIndex,
        [FindingId("SDR-I23")]
        NonIncrementalColumnStatOnPartitionedTable,
        [FindingId("SDR-I24")]
        HighModificationsSinceLastStatUpdate,
        [FindingId("SDR-I25")]
        HashIndexFewBuckets,
        [FindingId("SDR-I26")]
        HashIndexLargeDuplicateKey,
        [FindingId("SDR-I27")]
        ScannedHashIndex,
        [FindingId("SDR-I28")]
        HashIndexTooManyBuckets,
        [FindingId("SDR-I29")]
        RarelyUsedIndexOnInMemoryTable,
        [FindingId("SDR-I30")]
        ColumnStoreIndexMissingOnLargeTables,
        [FindingId("SDR-I31")]
        FilteredColumnNotInKeyOfFilteredIndex,
        [FindingId("SDR-I17")]
        IndexPageLatchContention,
        [FindingId("SDR-I9")]
        IndexLockContention,
        [FindingId("SDR-I6")]
        DuplicateIndex,
        [FindingId("SDR-I8")]
        PartialDuplicateIndex,
        [FindingId("SDR-I10")]
        IndexUnderutilized,
        [FindingId("SDR-I16")]
        IndexUnused,
        [FindingId("SDR-I3")]
        OutOfDateStats,
        [FindingId("SDR-Q36")]
        ImplicitConversionInPredicate,
        [FindingId("SDR-Q37")]   //SQLdm10.0 -Srishti Purohit -  New Recommendations
        Flag4199LowCompatible,
        [FindingId("SDR-Q38")] //SQLdm10.0 -Srishti Purohit -  New Recommendations
        Flag4199AllDbCompatible,
        [FindingId("SDR-M31")]   //SQLdm10.0 -Srishti Purohit -  New Recommendations
        LargeBufferPoolExtensionSize,
        [FindingId("SDR-M32")] //SQLdm10.0 -Srishti Purohit -  New Recommendations
        BufferPoolExtensionNotUseful,
        [FindingId("SDR-M33")] //SQLdm10.0 -Srishti Purohit -  New Recommendations
        BufferPoolExtensionHighIO,
        [FindingId("SDR-Q39")] //SQLdm10.0 -Srishti Purohit -  New Recommendations
        QueryStoreDisabled,
        [FindingId("SDR-Q40")] //SQLdm10.0 -Srishti Purohit -  New Recommendations
        QueryStoreOutOfSpace,
        [FindingId("SDR-Q41")] //SQLdm10.0 -Srishti Purohit -  New Recommendations
        QueryStoreAlmostFull,
        [FindingId("SDR-Q42")] //SQLdm10.0 -Srishti Purohit -  New Recommendations
        PlanGuidesUsedOverQueryStore,
        [FindingId("SDR-Q43")] //SQLdm10.0 -Srishti Purohit -  New Recommendations
        FrequentlyExecutedProcedureWithHighCPUTime,
        [FindingId("SDR-Q44")]
        NewCardinalityEstimatorNotBeingUsed, //SQLdm10.0 -Srishti Purohit -  New Recommendations
        [FindingId("SDR-Q45")] //SQLdm10.0 -Srishti Purohit -  New Recommendations
        BothNewAndOldCardinalityEstimatorInUse,
        [FindingId("SDR-Q46")] //SQLdm10.0 -Srishti Purohit -  New Recommendations 
        Top10QueriesWithLongestAverageExecutionTime,
        [FindingId("SDR-Q47")] //SQLdm10.0 -Srishti Purohit -  New Recommendations 
        Top10QueriesConsumingMostIO,
        [FindingId("SDR-Q48")] //SQLdm10.0 -Srishti Purohit -  New Recommendations 
        QueriesWithDoubleIncreaseInExecutionTime,
        [FindingId("SDR-Q49")] //SQLdm10.0 -Srishti Purohit -  New Recommendations 
        Top10QueriesHavingLongerDurationInLastHour,
        [FindingId("SDR-Q50")] //SQLdm10.0 -Srishti Purohit -  New Recommendations
        QueriesWithFourDifferentPlanInTwoDays,
        [FindingId("SDR-Q35")]
        FunctionInPredicate,
        [FindingId("SDR-Q6")]
        CachedPlanMisuse,
        [FindingId("SDR-I1")]
        AutoStats,
        [FindingId("SDR-Q3")]
        SQLModuleOptions,
        [FindingId("SDR-I20")]
        DMVMissingIndex,
        [FindingId("SDR-Q7")]
        HighCompilations,
        [FindingId("SDR-P1")]
        CpuAffinity,
        [FindingId("SDR-P2")]
        CpuAffinityReduced,
        [FindingId("SDR-P3")]
        CpuClockSpeedLost,
        [FindingId("SDR-P4")]
        CpuFullFrequency,
        [FindingId("SDR-P5")]
        CpuConstantFrequency,
        [FindingId("SDR-P6")]
        CpuMaxDOP,
        [FindingId("SDR-P7")]
        CpuEncryptedDatabaseIO,
        [FindingId("SDR-P8")]
        CpuDatabaseEncryptionAlgorithm,
        [FindingId("SDR-P10")]
        CpuMultipleInstances,
        [FindingId("SDR-P11")]
        CpuLightweightPooling,
        [FindingId("SDR-P12")]
        CpuEncryptedConnections,
        [FindingId("SDR-P13")]
        CpuInterruptsNetwork,
        [FindingId("SDR-P14")]
        CpuInterruptsDisk,
        [FindingId("SDR-P15")]
        CpuInterrupts,
        [FindingId("SDR-P16")]
        CpuEncryptedVolume,
        [FindingId("SDR-P17")]
        CpuC2Audit,
        [FindingId("SDR-P18")]
        CpuVirtualMachine,
        [FindingId("SDR-P21")]
        CpuThemes,
        [FindingId("SDR-M1")]
        Mem64bitLockPages,
        [FindingId("SDR-M2")]
        Mem32bit16g,
        [FindingId("SDR-M3")]
        Mem32bit4to16g,
        [FindingId("SDR-M4")]
        Mem32bit4g,
        [FindingId("SDR-M5")]
        Mem32bit3to4g,
        [FindingId("SDR-M6")]
        Mem32bit3gOrLess,
        [FindingId("SDR-M7")]
        MemStarvation,
        [FindingId("SDR-M8")]
        MemPaging,
        [FindingId("SDR-BP1")]
        BlockingProcess,
        [FindingId("SDR-OT1")]
        OpenTransaction,
        [FindingId("SDR-LR1")]
        LongRunningJob,
        [FindingId("SDR-DL1")]
        DeadlockTraceFlags,
        [FindingId("SDR-DL2")]
        Deadlock,
        [FindingId("SDR-M10")]
        MemRunningProcess,
        [FindingId("SDR-M12")]
        MemFileSharing,
        [FindingId("SDR-M13")]
        MemIncreaseDefaultFillFactor,
        [FindingId("SDR-M14")]
        MemAdjustDefaultFillFactor,
        [FindingId("SDR-M15")]
        MemDecreaseDefaultFillFactor,
        [FindingId("SDR-M16")]
        MemDecreased,
        [FindingId("SDR-M17")]
        MemMaxServerMemory,
        [FindingId("SDR-M18")]
        MemUserConnections,
        [FindingId("SDR-M19")]
        MemIndexCreation,
        [FindingId("SDR-M21")]
        MemPerfOfServices,
        [FindingId("SDR-M23")]
        MemPerfOfCache,
        [FindingId("SDR-M24")]
        MemOptimizeForAdhoc,
        [FindingId("SDR-M27")]
        MemTop10Processes,
        [FindingId("SDR-M11")]
        MemDomainController,
        [FindingId("SDR-M29")]
        MemLimitExceeded,
        [FindingId("SDR-Q20")]
        NotInUsedOnNullableColumn,
        [FindingId("SDR-DC1")]
        DatabaseConfiguration,
        [FindingId("SDR-DC2")]
        PageVerifyWriteable,
        [FindingId("SDR-DC3")]
        PageVerifyReadonly,
        [FindingId("SDR-DC4")]
        DatabaseCompatibility,
        [FindingId("SDR-DC5")]
        DatabaseCollation,
        [FindingId("SDR-SC1")]
        ServerConfiguration,
        [FindingId("SDR-SC2")]
        ServerConfigurationRestartRequired,
        [FindingId("SDR-SC3")]
        BlockedProcessThreshold,
        [FindingId("SDR-SC4")]
        LockConfiguration,
        [FindingId("SDR-SC5")]
        DefaultTraceEnabled,
        [FindingId("SDR-SC6")]
        DisallowResultsFromTriggers,
        [FindingId("SDR-SC7")]
        CLREnabled,
        [FindingId("SDR-SC8")]
        McAfeeBufferOverflow,
        [FindingId("SDR-SC9")]
        NetworkPacketSize,
        [FindingId("SDR-S1")]
        MixedModeAuthentication,
        [FindingId("SDR-S2")]
        BuiltinAdministratorIsSysadmin,
        [FindingId("SDR-S3")]
        PublicEnabledSqlAgentProxyAccount,
        [FindingId("SDR-S4")]
        DeprecatedAgentTokenInUse,
        //[FindingId("SDR-S5")]
        //ServerOnDomainController,
        [FindingId("SDR-S6")]
        VulnerableSqlLogin,
        [FindingId("SDR-S7")]
        IsTrustworthyVulnerable,
        [FindingId("SDR-S8")]
        SystemDatabaseSymmetricKey,
        [FindingId("SDR-S9")]
        NonSystemDatabaseWeakKey,
        [FindingId("SDR-S10")]
        GuestHasDatabaseAccess,
        [FindingId("SDR-P23")]
        CpuDisableParallelism,
        [FindingId("SDR-W1")]
        WaitStatsPageIoLatchCxPacket,
        [FindingId("SDR-W2")]
        WaitStatsParallelismThreshold,
        [FindingId("SDR-W3")]
        WaitStatsMaxDOP,
        [FindingId("SDR-W4")]
        WaitStatsHighCXPacket,
        [FindingId("SDR-W5")]
        WaitStatsAsyncNetIO,
        [FindingId("SDR-W6")]
        WaitStatsThreadPool,
        [FindingId("SDR-W7")]
        WaitStatsPageIoLatchDatabase,
        [FindingId("SDR-W8")]
        WaitStatsPageLatchIndex,
        [FindingId("SDR-W9")]
        WaitStatsPageLatchTable,
        [FindingId("SDR-W10")]
        WaitStatsPageLatchAllocPageContention,
        [FindingId("SDR-R1")]
        DatabaseSuspectPages,
        [FindingId("SDR-R2")]
        DatabaseBackupsOnSameVolume,
        [FindingId("SDR-R3")]
        DatabaseCheckIntegrity,
        [FindingId("SDR-R4")]
        DatabaseRecoveryModel,
        [FindingId("SDR-R5")]
        DatabaseOutdatedBackups,
        [FindingId("SDR-R6")]
        DatabaseBackupsDeleted,
        [FindingId("SDR-R7")]
        DatabaseNoRecentLogBackup,
        [FindingId("SDR-R8")]
        AvailabilityGroupNotEnabledForFailover,
        [FindingId("SDR-I21")]
        OverlappingIndexes,
        [FindingId("SDR-I22")]
        NonClusteredMatchingClusteredIndex,
        [FindingId("SDR-M30")]
        Mem32bit4gSS2012
    }
}
