using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Idera.SQLdoctor.Common.Helpers
{
    internal static class WaitStatsHelper
    {
        private static List<WaitTypeInfo> _waitInfo = new List<WaitTypeInfo>() 
        { 
            //-------------------------------------------------------------
            // Data was generated using the [WaitTypes] table from the 
            // SQLdm repository.  The 'GenWaitStatsInfoDialog' can be used by
            // pressing Ctrl+Alt+G on the main form while in debug mode.
            //
            new WaitTypeInfo(){WaitType="ABR",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="ASSEMBLY_LOAD",Category="Other",Description="Caused when there is exclusive access to assembly loading.",HelpLink=""},
            new WaitTypeInfo(){WaitType="ASYNC_DISKPOOL_LOCK",Category="Other",Description="Caused when parallel threads that are executing tasks such as file creation or initialization are attempting to synchronize.",HelpLink=""},
            new WaitTypeInfo(){WaitType="ASYNC_IO_COMPLETION",Category="I/O",Description="Caused when a task is waiting for an asynchronous I/O operation to finish.",HelpLink=""},
            new WaitTypeInfo(){WaitType="ASYNC_NETWORK_IO",Category="Other",Description="Caused when network writes are blocked behind the network. Ensure the client is processing server data.",HelpLink=""},
            new WaitTypeInfo(){WaitType="AUDIT_GROUPCACHE_LOCK",Category="Other",Description="Caused when there is a wait on a lock that controls access to a special cache. This cache has information on the audits that are being used to audit each audit action group.",HelpLink=""},
            new WaitTypeInfo(){WaitType="AUDIT_LOGINCACHE_LOCK",Category="Other",Description="Caused when there is a wait on a lock that controls access to a special cache.  This cache has information on the audits that are being used to audit each audit action group.",HelpLink=""},
            new WaitTypeInfo(){WaitType="AUDIT_ON_DEMAND_TARGET_LOCK",Category="Other",Description="Caused when there is a wait on a lock that ensures single initialization of audit related Extended Event targets.",HelpLink=""},
            new WaitTypeInfo(){WaitType="AUDIT_XE_SESSION_MGR",Category="Other",Description="Caused when there is a wait on a lock that synchronizes the start and stop of audit related Extended Events sessions.",HelpLink=""},
            new WaitTypeInfo(){WaitType="BACKUP",Category="Backup",Description="Caused when tasks are blocked as part of backup processing.",HelpLink=""},
            new WaitTypeInfo(){WaitType="BACKUP_CLIENTLOCK",Category="Backup",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="BACKUP_OPERATOR",Category="Backup",Description="Caused when tasks are waiting for a tape mount. ",HelpLink=""},
            new WaitTypeInfo(){WaitType="BACKUPBUFFER",Category="Backup",Description="Caused when a backup task is either waiting for data, or is waiting for a buffer to store data. This type is typically seen only when a task is waiting for a tape mount.",HelpLink=""},
            new WaitTypeInfo(){WaitType="BACKUPIO",Category="Backup",Description="Caused when a backup task is either waiting for data, or is waiting for a buffer to store data. This type is typically seen only when a task is waiting for a tape mount.",HelpLink=""},
            new WaitTypeInfo(){WaitType="BACKUPTHREAD",Category="Backup",Description="Caused when a task is waiting for a backup task to finish. Wait times may be long, from several minutes to several hours. If the task that is being waited on is in an I/O process, this type does not indicate a problem.",HelpLink=""},
            new WaitTypeInfo(){WaitType="BAD_PAGE_PROCESS",Category="Excluded",Description="Caused when the background suspect page logger is attempting to avoid running more than every five seconds. Excessive suspect pages cause the logger to run frequently.",HelpLink=""},
            new WaitTypeInfo(){WaitType="BROKER_CONNECTION_RECEIVE_TASK",Category="Other",Description="Caused when waiting for access to receive a message on a connection endpoint.",HelpLink=""},
            new WaitTypeInfo(){WaitType="BROKER_ENDPOINT_STATE_MUTEX",Category="Other",Description="Caused when contention exists to access the state of a Service Broker connection endpoint.",HelpLink=""},
            new WaitTypeInfo(){WaitType="BROKER_EVENTHANDLER",Category="Excluded",Description="Caused when a task is waiting in the primary event handler of the Service Broker.",HelpLink=""},
            new WaitTypeInfo(){WaitType="BROKER_INIT",Category="Other",Description="Caused when initializing Service Broker in each active database.",HelpLink=""},
            new WaitTypeInfo(){WaitType="BROKER_MASTERSTART",Category="Other",Description="Caused when a task is waiting for the primary event handler of the Service Broker to start. ",HelpLink=""},
            new WaitTypeInfo(){WaitType="BROKER_RECEIVE_WAITFOR",Category="Excluded",Description="Caused when RECEIVE WAITFOR is waiting. This happens when no messages are ready to be received.",HelpLink=""},
            new WaitTypeInfo(){WaitType="BROKER_REGISTERALLENDPOINTS",Category="Other",Description="Caused during the initialization of a Service Broker connection endpoint.",HelpLink=""},
            new WaitTypeInfo(){WaitType="BROKER_SERVICE",Category="Other",Description="Caused when the Service Broker destination list that is associated with a target service is updated or re-prioritized.",HelpLink=""},
            new WaitTypeInfo(){WaitType="BROKER_SHUTDOWN",Category="Other",Description="Caused when there is a planned shutdown of Service Broker. ",HelpLink=""},
            new WaitTypeInfo(){WaitType="BROKER_TASK_STOP",Category="Excluded",Description="Caused when the Service Broker queue task handler tries to shut down the task. The state check is serialized and must be in a running state beforehand.",HelpLink=""},
            new WaitTypeInfo(){WaitType="BROKER_TO_FLUSH",Category="Excluded",Description="Caused when the Service Broker lazy flusher flushes the in-memory transmission objects to a work table.",HelpLink=""},
            new WaitTypeInfo(){WaitType="BROKER_TRANSMITTER",Category="Excluded",Description="Caused when the Service Broker transmitter is waiting for work.",HelpLink=""},
            new WaitTypeInfo(){WaitType="BROKER_XMIT_SHUTDOWN",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="BROKER_XMIT_START",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="BROKER_XMIT_TABLE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="BUILTIN_HASHKEY_MUTEX",Category="Other",Description="Caused when when the instances is started while internal data structures are initializing. Will not occur once the data structures have initialized.",HelpLink=""},
            new WaitTypeInfo(){WaitType="CHECK_PRINT_RECORD",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="CHECKPOINT_QUEUE",Category="Excluded",Description="Caused when the checkpoint task is waiting for the next checkpoint request.",HelpLink=""},
            new WaitTypeInfo(){WaitType="CHKPT",Category="Excluded",Description="Caused when the checkpoint thread is told that it can start at server startup.",HelpLink=""},
            new WaitTypeInfo(){WaitType="CLEAR_DB",Category="Other",Description="Caused when operations occur that change the state of a database, such as the opening or closing a database.",HelpLink=""},
            new WaitTypeInfo(){WaitType="CLR_AUTO_EVENT",Category="Other",Description="Caused when a task is currently performing common language runtime (CLR) execution and is waiting for a particular autoevent to be initiated. Long waits are typical, and do not indicate a problem.",HelpLink=""},
            new WaitTypeInfo(){WaitType="CLR_CRST",Category="Other",Description="Caused when a task is currently performing a CLR execution and is waiting to enter a critical area that is currently being used by another task.",HelpLink=""},
            new WaitTypeInfo(){WaitType="CLR_JOIN",Category="Other",Description="Caused when a task is currently performing a CLR execution and waiting for another task to end. This wait state occurs when there is a join between tasks.",HelpLink=""},
            new WaitTypeInfo(){WaitType="CLR_MANUAL_EVENT",Category="Other",Description="Caused when a task is currently performing a CLR execution and is waiting for a specific manual event to begin.",HelpLink=""},
            new WaitTypeInfo(){WaitType="CLR_MEMORY_SPY",Category="Other",Description="Caused when waiting on lock acquisition for a data structure that is used to record all virtual memory allocations that come from CLR. The data structure is locked to maintain its integrity if there is parallel access.",HelpLink=""},
            new WaitTypeInfo(){WaitType="CLR_MONITOR",Category="Other",Description="Caused when a task is performing a CLR execution and is waiting to obtain a lock on the monitor.",HelpLink=""},
            new WaitTypeInfo(){WaitType="CLR_RWLOCK_READER",Category="Other",Description="Caused when a task is performing a CLR execution and is waiting for a reader lock.",HelpLink=""},
            new WaitTypeInfo(){WaitType="CLR_RWLOCK_WRITER",Category="Other",Description="Caused when a task is performing a CLR execution and is waiting for a writer lock.",HelpLink=""},
            new WaitTypeInfo(){WaitType="CLR_SEMAPHORE",Category="Excluded",Description="Caused when a task is performing a CLR execution and is waiting for a semaphore.",HelpLink=""},
            new WaitTypeInfo(){WaitType="CLR_TASK_START",Category="Other",Description="Caused when waiting for a CLR task to complete startup.",HelpLink=""},
            new WaitTypeInfo(){WaitType="CLRHOST_STATE_ACCESS",Category="Other",Description="Caused when a task is waiting acquire exclusive access to the CLR-hosting data structures. This wait type occurs while setting up or tearing down the CLR runtime.",HelpLink=""},
            new WaitTypeInfo(){WaitType="CMEMTHREAD",Category="Memory",Description="Caused when a task is waiting on a thread-safe memory object. The wait time might increase when there is contention caused by multiple tasks trying to allocate memory from the same memory object.",HelpLink=""},
            new WaitTypeInfo(){WaitType="COMMIT_TABLE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="CURSOR",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="CURSOR_ASYNC",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="CXPACKET",Category="Other",Description="Caused when parallelized query threads have an unequal workload, causing a block on the entire query until the longest-running thread is complete. See help for further discussion.",HelpLink="WS Cxpacket.htm"},
            new WaitTypeInfo(){WaitType="CXROWSET_SYNC",Category="Other",Description="Caused when a parallel range scan is in progress.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DAC_INIT",Category="Other",Description="Caused when the dedicated administrator connection is initializing.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DBMIRROR_DBM_EVENT",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DBMIRROR_DBM_MUTEX",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DBMIRROR_EVENTS_QUEUE",Category="Excluded",Description="Caused when database mirroring is waiting for events to process.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DBMIRROR_SEND",Category="Other",Description="Caused when a task is waiting for a communications backlog at the network layer to clear. This wait indicates that the communications layer is starting to become overloaded and is affecting the database mirroring data throughput.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DBMIRROR_WORKER_QUEUE",Category="Other",Description="Caused when the database mirroring worker task is waiting for more work.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DBMIRRORING_CMD",Category="Other",Description="Caused when a task is waiting for log records to be flushed to disk. This wait is typically held for a long period of time.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DBTABLE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="DEADLOCK_ENUM_MUTEX",Category="Other",Description="Caused when the deadlock monitor and sys.dm_os_waiting_tasks try to make sure that SQL Server is not running multiple deadlock searches at the same time.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DEADLOCK_TASK_SEARCH",Category="Other",Description="Caused when the server is executing queries on top of sys.dm_os_waiting_tasks, and these queries are blocking the deadlock monitor from running deadlock searches. Queries on top of the sys.dm_os_waiting_tasks use DEADLOCK_ENUM_MUTEX and this wait type is only used by the deadlock monitor.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DEBUG",Category="Other",Description="Caused when Transact-SQL and CLR are debugging for internal synchronization.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DISABLE_VERSIONING",Category="Other",Description="Caused when SQL Server polls the version transaction manager to see whether the timestamp of the earliest active transaction is later than the timestamp of when the state started changing. If the timestamp is later, all the snapshot transactions that were started before the ALTER DATABASE statement was run have finished. This wait state is used when SQL Server disables versioning by using the ALTER DATABASE statement.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DISKIO_SUSPEND",Category="Backup",Description="Caused when a task is waiting to access a file when an external backup is active. This is reported for each waiting user process. A count larger than five per user process may indicate that the SNAPSHOT BACKUP is taking too much time to finish.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DISPATCHER_QUEUE_SEMAPHORE",Category="Other",Description="Caused when a thread from the dispatcher pool is waiting for more work to process. When the dispatcher is idle the wait time will increase.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DLL_LOADING_MUTEX",Category="Other",Description="Caused once while waiting for the XML parser DLL to load.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DROPTEMP",Category="Other",Description="Caused between attempts to drop a temporary object if the previous attempt failed. The wait duration grows exponentially with each failed drop attempt.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DTC",Category="Other",Description="Caused when tasks are waiting on an event that is used to manage state transition. The manage state transition controls when the recovery of Microsoft Distributed Transaction Coordinator (MS DTC) transactions occurs after SQL Server receives notification that the MS DTC service has become unavailable. This state also describes a task that is waiting when a commit of a MS DTC transaction is initiated by SQL Server and SQL Server is waiting for the MS DTC commit to finish.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DTC_ABORT_REQUEST",Category="Other",Description="Caused in a MS DTC worker session when the session is waiting to take ownership of a MS DTC transaction. After MS DTC owns the transaction, the session can roll back the transaction. Generally, the session will wait for another session that is using the transaction.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DTC_RESOLVE",Category="Other",Description="Caused when a recovery task is waiting for the master database in a cross-database transaction so that the task can query the outcome of the transaction.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DTC_STATE",Category="Other",Description="Caused when a task is waiting for an event that protects changes to the internal MS DTC global state object. This wait should be very short.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DTC_TMDOWN_REQUEST",Category="Other",Description="Caused in a MS DTC worker session when SQL Server receives notification that the MS DTC service is not available. The worker waits for the MS DTC recovery process to start. Once the recovery process starts, the worker waits to obtain the outcome of the distributed transaction that the worker is working on. This continues until the connection with the MS DTC service has been reestablished.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DTC_WAITFOR_OUTCOME",Category="Other",Description="Caused when recovery tasks wait for MS DTC to become active to enable the resolution of prepared transactions.",HelpLink=""},
            new WaitTypeInfo(){WaitType="DUMP_LOG_COORDINATOR",Category="Other",Description="Caused when a main task is waiting for a subtask to generate data. This state does not occur normally. A long wait time indicates an unexpected blockage. ",HelpLink=""},
            new WaitTypeInfo(){WaitType="DUMP_LOG_COORDINATOR_QUEUE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="DUMPTRIGGER",Category="Other",Description="Caused  for informational purposes only. Not supported. Future compatibility is not guaranteed.",HelpLink=""},
            new WaitTypeInfo(){WaitType="EC",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="EE_PMOLOCK",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="EE_SPECPROC_MAP_INIT",Category="Other",Description="Caused during the synchronization of internal procedure hash table creation. This wait only occurs during the initial accessing of the hash table after the SQL Server instance starts.",HelpLink=""},
            new WaitTypeInfo(){WaitType="ENABLE_VERSIONING",Category="Other",Description="Caused when SQL Server waits for all update transactions in this database to finish before declaring the database ready to transition to snapshot isolation allowed state. This state is used when SQL Server enables snapshot isolation by using the ALTER DATABASE statement.",HelpLink=""},
            new WaitTypeInfo(){WaitType="ERROR_REPORTING_MANAGER",Category="Other",Description="Caused during the synchronization of multiple concurrent error log initializations.",HelpLink=""},
            new WaitTypeInfo(){WaitType="EXCHANGE",Category="Other",Description="Caused during the synchronization in the query processor exchange iterator during parallel queries.",HelpLink=""},
            new WaitTypeInfo(){WaitType="EXECSYNC",Category="Other",Description="Caused during parallel queries while synchronizing in query processor in areas not related to the exchange iterator. Examples of such areas are bitmaps, large binary objects (LOBs), and the spool iterator. LOBs may frequently use this wait state.",HelpLink=""},
            new WaitTypeInfo(){WaitType="EXECUTION_PIPE_EVENT_INTERNAL",Category="Other",Description="Caused during the synchronization between producer and consumer parts of batch execution that are submitted through the connection context.",HelpLink=""},
            new WaitTypeInfo(){WaitType="FAILPOINT",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="FCB_REPLICA_READ",Category="Other",Description="Caused when snapshot reads(or a temporary snapshot created by DBCC) sparse file are synchronized.",HelpLink=""},
            new WaitTypeInfo(){WaitType="FCB_REPLICA_START",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="FCB_REPLICA_WRITE",Category="Other",Description="Caused when snapshot page pushing or pulling of a (or a temporary snapshot created by DBCC) sparse file is synchronized.",HelpLink=""},
            new WaitTypeInfo(){WaitType="FS_FC_RWLOCK",Category="Other",Description="Caused when a wait by the FILESTREAM garbage collector to do either of the following occurs: (1) Disable garbage collection (used by backup and restore). (2) Execute one cycle of the FILESTREAM garbage collector.",HelpLink=""},
            new WaitTypeInfo(){WaitType="FS_GARBAGE_COLLECTOR_SHUTDOWN",Category="Other",Description="Caused when the FILESTREAM garbage collector is waiting for cleanup tasks to be completed.",HelpLink=""},
            new WaitTypeInfo(){WaitType="FS_HEADER_RWLOCK",Category="Other",Description="Caused when there is a wait to acquire access to the FILESTREAM header of a FILESTREAM data container to either read or update contents in the FILESTREAM header file (Filestream.hdr).",HelpLink=""},
            new WaitTypeInfo(){WaitType="FS_LOGTRUNC_RWLOCK",Category="Other",Description="Caused when there is a wait to acquire access to the FILESTREAM log truncation to do either of the following: (1) Temporarily disable the FILESTREAM log (FSLOG) truncation (used by backup and restore). (2) Execute one cycle of FSLOG truncation.",HelpLink=""},
            new WaitTypeInfo(){WaitType="FSA_FORCE_OWN_XACT",Category="Other",Description="Caused when a FILESTREAM file I/O operation needs to bind to the associated transaction, but the transaction is currently owned by another session.",HelpLink=""},
            new WaitTypeInfo(){WaitType="FSAGENT",Category="Other",Description="Caused when a FILESTREAM file I/O operation is waiting for a FILESTREAM agent resource that is being used by another file I/O operation.",HelpLink=""},
            new WaitTypeInfo(){WaitType="FSTR_CONFIG_MUTEX",Category="Other",Description="Caused when there is a wait for another FILESTREAM feature reconfiguration to be completed.",HelpLink=""},
            new WaitTypeInfo(){WaitType="FSTR_CONFIG_RWLOCK",Category="Other",Description="Caused when there is a wait to serialize access to the FILESTREAM configuration parameters.",HelpLink=""},
            new WaitTypeInfo(){WaitType="FT_COMPROWSET_RWLOCK",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="FT_IFTS_RWLOCK",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="FT_IFTS_SCHEDULER_IDLE_WAIT",Category="Excluded",Description="Caused when a background task processing full-text search requests indicates it is “waiting for work to do:” Unless unexplained FTS issues are occuring, you can safely ignore this wait.",HelpLink=""},
            new WaitTypeInfo(){WaitType="FT_IFTSHC_MUTEX",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="FT_IFTSISM_MUTEX",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="FT_MASTER_MERGE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="FT_METADATA_MUTEX",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="FT_RESTART_CRAWL",Category="Other",Description="Caused when a full-text crawl needs to restart from a last known good point to recover from a transient failure. The wait allows worker tasks currently working on that population to complete or exit the current step.",HelpLink=""},
            new WaitTypeInfo(){WaitType="FT_RESUME_CRAWL",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="FULLTEXT GATHERER",Category="Other",Description="Caused when synchronizing full-text operations.",HelpLink=""},
            new WaitTypeInfo(){WaitType="GUARDIAN",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="HTTP_ENDPOINT_COLLCREATE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="HTTP_ENUMERATION",Category="Other",Description="Caused when the enumeration of HTTP endpoints to start HTTP occurs at startup.",HelpLink=""},
            new WaitTypeInfo(){WaitType="HTTP_START",Category="Other",Description="Caused when a connection is waiting for HTTP to complete initialization.",HelpLink=""},
            new WaitTypeInfo(){WaitType="IMP_IMPORT_MUTEX",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="IMPPROV_IOWAIT",Category="Other",Description="Caused when SQL Server waits for a bulkload I/O to finish.",HelpLink=""},
            new WaitTypeInfo(){WaitType="INDEX_USAGE_STATS_MUTEX",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="INTERNAL_TESTING",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="IO_AUDIT_MUTEX",Category="Other",Description="Caused when synchronizing trace event buffers.",HelpLink=""},
            new WaitTypeInfo(){WaitType="IO_COMPLETION",Category="I/O",Description="Caused when waiting for I/O operations to complete. This wait type generally represents non-data page I/Os. Data page I/O completion waits appear as PAGEIOLATCH_* waits.",HelpLink=""},
            new WaitTypeInfo(){WaitType="IO_RETRY",Category="Other",Description="Caused when waiting for an I/O operation (read or a write to disk) fails due to insufficient resources. The operation has to try again.",HelpLink=""},
            new WaitTypeInfo(){WaitType="IOAFF_RANGE_QUEUE",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="KSOURCE_WAKEUP",Category="Excluded",Description="Caused when the service control task is waiting for requests from the Service Control Manager. Long waits are normal.",HelpLink=""},
            new WaitTypeInfo(){WaitType="KTM_ENLISTMENT",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="KTM_RECOVERY_MANAGER",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="KTM_RECOVERY_RESOLUTION",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="LATCH_DT",Category="Non-Page Latch",Description="Caused when waiting for a DT (destroy) latch. This does not include buffer latches or transaction mark latches. A listing of LATCH_* waits is available in sys.dm_os_latch_stats. Note that sys.dm_os_latch_stats groups LATCH_NL, LATCH_SH, LATCH_UP, LATCH_EX, and LATCH_DT waits together.",HelpLink=""},
            new WaitTypeInfo(){WaitType="LATCH_EX",Category="Non-Page Latch",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="LATCH_KP",Category="Non-Page Latch",Description="Caused when waiting for a KP (keep) latch. This does not include buffer latches or transaction mark latches. A listing of LATCH_* waits is available in sys.dm_os_latch_stats. Note that sys.dm_os_latch_stats groups LATCH_NL, LATCH_SH, LATCH_UP, LATCH_EX, and LATCH_DT waits together.",HelpLink=""},
            new WaitTypeInfo(){WaitType="LATCH_NL",Category="Non-Page Latch",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="LATCH_SH",Category="Non-Page Latch",Description="Caused when waiting for an SH (share) latch. This does not include buffer latches or transaction mark latches. A listing of LATCH_* waits is available in sys.dm_os_latch_stats. Note that sys.dm_os_latch_stats groups LATCH_NL, LATCH_SH, LATCH_UP, LATCH_EX, and LATCH_DT waits together.",HelpLink=""},
            new WaitTypeInfo(){WaitType="LATCH_UP",Category="Non-Page Latch",Description="Caused when waiting for an UP (update) latch. This does not include buffer latches or transaction mark latches. A listing of LATCH_* waits is available in sys.dm_os_latch_stats. Note that sys.dm_os_latch_stats groups LATCH_NL, LATCH_SH, LATCH_UP, LATCH_EX, and LATCH_DT waits together.",HelpLink=""},
            new WaitTypeInfo(){WaitType="LAZYWRITER_SLEEP",Category="Excluded",Description="Caused when lazywriter tasks are suspended. This is a measure of the time spent by background tasks that are waiting. This wait can be safely ignored as wait times will cycle as Lazywriter is designed to sleep and wake-up every 1 second.",HelpLink=""},
            new WaitTypeInfo(){WaitType="LCK_M_BU",Category="Lock",Description="Caused when a task is waiting to acquire a Bulk Update (BU) lock.",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_IS",Category="Lock",Description="Caused when a task is waiting to acquire an Intent Shared (IS) lock.",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_IU",Category="Lock",Description="Caused when a task is waiting to acquire an Intent Update (IU) lock. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_IX",Category="Lock",Description="Caused when a task is waiting to acquire an Intent Exclusive (IX) lock. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_RIn_NL",Category="Lock",Description="Caused when a task is waiting to acquire a NULL lock on the current key value, and an Insert Range lock between the current and previous key. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_RIn_S",Category="Lock",Description="Caused when a task is waiting to acquire a shared lock on the current key value, and an Insert Range lock between the current and previous key. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_RIn_U",Category="Lock",Description="Caused when a task is waiting to acquire an Update lock on the current key value, and an Insert Range lock between the current and previous key. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_RIn_X",Category="Lock",Description="Caused when a task is waiting to acquire an Exclusive lock on the current key value, and an Insert Range lock between the current and previous key. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_RS_S",Category="Lock",Description="Caused when a task is waiting to acquire a Shared lock on the current key value, and a Shared Range lock between the current and previous key. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_RS_U",Category="Lock",Description="Caused when a task is waiting to acquire an Update lock on the current key value, and an Update Range lock between the current and previous key. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_RX_S",Category="Lock",Description="Caused when a task is waiting to acquire a Shared lock on the current key value, and an Exclusive Range lock between the current and previous key. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_RX_U",Category="Lock",Description="Caused when a task is waiting to acquire an Update lock on the current key value, and an Exclusive range lock between the current and previous key. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_RX_X",Category="Lock",Description="Caused when a task is waiting to acquire an Exclusive lock on the current key value, and an Exclusive Range lock between the current and previous key. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_S",Category="Lock",Description="Caused when a task is waiting to acquire a Shared lock. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_SCH_M",Category="Lock",Description="Caused when a task is waiting to acquire a Schema Modify lock. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_SCH_S",Category="Lock",Description="Caused when a task is waiting to acquire a Schema Share lock. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_SIU",Category="Lock",Description="Caused when a task is waiting to acquire a Shared With Intent Update lock. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_SIX",Category="Lock",Description="Caused when a task is waiting to acquire a Shared With Intent Exclusive lock. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_U",Category="Lock",Description="Caused when a task is waiting to acquire an Update lock. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_UIX",Category="Lock",Description="Caused when a task is waiting to acquire an Update With Intent Exclusive lock. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LCK_M_X",Category="Lock",Description="Caused when a task is waiting to acquire an Exclusive lock. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms190345.aspx"},
            new WaitTypeInfo(){WaitType="LOGBUFFER",Category="Transaction Log",Description="Caused when a task is waiting for space in the WRITELOG buffer to store a log record. This wait is typical when there is an I/O botteneck. Look for WRITERLOG waiters and if found the overall problem is an I/O bottleneck on the storage system associated with the transaction log.",HelpLink="WS Logbuffer.htm"},
            new WaitTypeInfo(){WaitType="LOGGENERATION",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="LOGMGR",Category="Transaction Log",Description="Caused when a task is waiting for any outstanding log I/Os to finish before shutting down the log while closing the database.",HelpLink=""},
            new WaitTypeInfo(){WaitType="LOGMGR_FLUSH",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="LOGMGR_QUEUE",Category="Excluded",Description="Caused when the log writer task is waiting for work requests. You should be able to safely ignore this wait type unless you believe a problem exists in processing log blocks to flush to the transaction log. ",HelpLink=""},
            new WaitTypeInfo(){WaitType="LOGMGR_RESERVE_APPEND",Category="Other",Description="Caused when a task is waiting to see whether log truncation frees up log space to enable the task to write a new log record. ",HelpLink="WS LOGMGR Reserve.htm"},
            new WaitTypeInfo(){WaitType="LOWFAIL_MEMMGR_QUEUE",Category="Other",Description="Caused while waiting for memory to be available for use.",HelpLink=""},
            new WaitTypeInfo(){WaitType="METADATA_LAZYCACHE_RWLOCK",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="MIRROR_SEND_MESSAGE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="MISCELLANEOUS",Category="Excluded",Description="Used for informational purposes only. This wait is only seen in SQL Server 2000 and is listed as the default wait in the list and isn't used to indicate ay real waiting.",HelpLink=""},
            new WaitTypeInfo(){WaitType="MSQL_DQ",Category="Other",Description="Caused when a task is waiting for a distributed query operation to finish. This is used to detect potential Multiple Active Result Set (MARS) application deadlocks. The wait ends when the distributed query call finishes.",HelpLink=""},
            new WaitTypeInfo(){WaitType="MSQL_SYNC_PIPE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="MSQL_XACT_MGR_MUTEX",Category="Other",Description="Caused when a task is waiting to obtain ownership of the session transaction manager to perform a session level transaction operation.",HelpLink=""},
            new WaitTypeInfo(){WaitType="MSQL_XACT_MUTEX",Category="Other",Description="Caused during the synchronization of transaction usage. Requests must acquire the mutex before it can use the transaction.",HelpLink=""},
            new WaitTypeInfo(){WaitType="MSQL_XP",Category="Other",Description="Caused when a task is waiting for an extended stored procedure to end. SQL Server uses this wait state to detect potential MARS application deadlocks. The wait ends when the extended stored procedure call completes.",HelpLink=""},
            new WaitTypeInfo(){WaitType="MSSEARCH",Category="Other",Description="Caused during Full-Text Search calls. This wait ends when the full-text operation completes. It does not indicate contention, but rather the duration of full-text operations.",HelpLink=""},
            new WaitTypeInfo(){WaitType="NET_WAITFOR_PACKET",Category="Other",Description="Caused when a connection is waiting for a network packet during a network read.",HelpLink=""},
            new WaitTypeInfo(){WaitType="NODE_CACHE_MUTEX",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="OLEDB",Category="Other",Description="Caused when SQL Server calls the SQL Server Native Client OLE DB Provider. This wait type indicates the duration of calls to the OLE DB provider.",HelpLink=""},
            new WaitTypeInfo(){WaitType="ONDEMAND_TASK_QUEUE",Category="Excluded",Description="Caused when a background task waits for high priority system task requests. A long wait time indicates that there have been no high priority requests to process, and should not cause concern.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PAGEIOLATCH_DT",Category="I/O",Description="Caused when a task is waiting on a latch for a buffer that is in an I/O request. The latch request is in Destroy mode. A long wait time may indicate problems with the disk subsystem.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PAGEIOLATCH_EX",Category="I/O",Description="Caused when a task is waiting on a latch for a buffer that is in an I/O request. The latch request is in Exclusive mode. A long wait time may indicate problems with the disk subsystem.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PAGEIOLATCH_KP",Category="I/O",Description="Caused when a task is waiting on a latch for a buffer that is in an I/O request. The latch request is in Keep mode. A long wait time may indicate problems with the disk subsystem.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PAGEIOLATCH_NL",Category="I/O",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PAGEIOLATCH_SH",Category="I/O",Description="Caused when a task is waiting on a latch for a buffer that is in an I/O request. The latch request is in Shared mode. A long wait time may indicate problems with the disk subsystem.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PAGEIOLATCH_UP",Category="I/O",Description="Caused when a task is waiting on a latch for a buffer that is in an I/O request. The latch request is in Update mode. A long wait time may indicate problems with the disk subsystem.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PAGELATCH_DT",Category="Non-I/O Page Latch",Description="Caused when a task is waiting on a latch for a buffer that is not in an I/O request. The latch request is in Destroy mode.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PAGELATCH_EX",Category="Non-I/O Page Latch",Description="Caused when a task is waiting on a latch for a buffer that is not in an I/O request. The latch request is in Exclusive mode.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PAGELATCH_KP",Category="Non-I/O Page Latch",Description="Caused when a task is waiting on a latch for a buffer that is not in an I/O request. The latch request is in Keep mode.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PAGELATCH_NL",Category="Non-I/O Page Latch",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PAGELATCH_SH",Category="Non-I/O Page Latch",Description="Caused when a task is waiting on a latch for a buffer that is not in an I/O request. The latch request is in Shared mode.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PAGELATCH_UP",Category="Non-I/O Page Latch",Description="Caused when a task is waiting on a latch for a buffer that is not in an I/O request. The latch request is in Update mode.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PARALLEL_BACKUP_QUEUE",Category="Other",Description="Caused when serializing output produced by RESTORE HEADERONLY, RESTORE FILELISTONLY, or RESTORE LABELONLY.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PERFORMANCE_COUNTERS_RWLOCK",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PLACEHOLDER1",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PLACEHOLDER2",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_ABR",Category="Other",Description="Caused when a worker is running coded in a non-SQLOS Sceduling Systems mode.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_AUDIT_ACCESS_EVENTLOG",Category="Other",Description="Caused when the SQL Server Operating System (SQLOS) scheduler switches to preemptive mode to write an audit event to the Windows event log.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_AUDIT_ACCESS_SECLOG",Category="Other",Description="Caused when the SQLOS scheduler switches to preemptive mode to write an audit event to the Windows Security log.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_CLOSEBACKUPMEDIA",Category="Other",Description="Caused when the SQLOS scheduler switches to preemptive mode to close backup media.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_CLOSEBACKUPTAPE",Category="Other",Description="Caused when the SQLOS scheduler switches to preemptive mode to close a tape backup device.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_CLOSEBACKUPVDIDEVICE",Category="Other",Description="Caused when the SQLOS scheduler switches to preemptive mode to close a virtual backup device.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_CLUSAPI_CLUSTERRESOURCECONTROL",Category="Other",Description="Caused when the SQLOS scheduler switches to preemptive mode to perform Windows failover cluster operations.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_COCREATEINSTANCE",Category="Other",Description="Caused when the SQLOS scheduler switches to preemptive mode to create a COM object.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_COGETCLASSOBJECT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_CREATEACCESSOR",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_DELETEROWS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_GETCOMMANDTEXT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_GETDATA",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_GETNEXTROWS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_GETRESULT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_GETROWSBYBOOKMARK",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_LBFLUSH",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_LBLOCKREGION",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_LBREADAT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_LBSETSIZE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_LBSTAT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_LBUNLOCKREGION",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_LBWRITEAT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_QUERYINTERFACE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_RELEASE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_RELEASEACCESSOR",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_RELEASEROWS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_RELEASESESSION",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_RESTARTPOSITION",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_SEQSTRMREAD",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_SEQSTRMREADANDWRITE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_SETDATAFAILURE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_SETPARAMETERINFO",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_SETPARAMETERPROPERTIES",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_STRMLOCKREGION",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_STRMSEEKANDREAD",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_STRMSEEKANDWRITE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_STRMSETSIZE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_STRMSTAT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_COM_STRMUNLOCKREGION",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_CONSOLEWRITE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_CREATEPARAM",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_DEBUG",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_DFSADDLINK",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_DFSLINKEXISTCHECK",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_DFSLINKHEALTHCHECK",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_DFSREMOVELINK",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_DFSREMOVEROOT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_DFSROOTFOLDERCHECK",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_DFSROOTINIT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_DFSROOTSHARECHECK",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_DTC_ABORT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_DTC_ABORTREQUESTDONE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_DTC_BEGINTRANSACTION",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_DTC_COMMITREQUESTDONE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_DTC_ENLIST",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_DTC_PREPAREREQUESTDONE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_FILESIZEGET",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_FSAOLEDB_ABORTTRANSACTION",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_FSAOLEDB_COMMITTRANSACTION",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_FSAOLEDB_STARTTRANSACTION",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_FSRECOVER_UNCONDITIONALUNDO",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_GETRMINFO",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_LOCKMONITOR",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_MSS_RELEASE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_ODBCOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OLE_UNINIT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OLEDB_ABORTORCOMMITTRAN",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OLEDB_ABORTTRAN",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OLEDB_GETDATASOURCE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OLEDB_GETLITERALINFO",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OLEDB_GETPROPERTIES",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OLEDB_GETPROPERTYINFO",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OLEDB_GETSCHEMALOCK",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OLEDB_JOINTRANSACTION",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OLEDB_RELEASE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OLEDB_SETPROPERTIES",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OLEDBOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_ACCEPTSECURITYCONTEXT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_ACQUIRECREDENTIALSHANDLE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_AUTHENTICATIONOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_AUTHORIZATIONOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_AUTHZGETINFORMATIONFROMCONTEXT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_AUTHZINITIALIZECONTEXTFROMSID",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_AUTHZINITIALIZERESOURCEMANAGER",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_BACKUPREAD",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_CLOSEHANDLE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_CLUSTEROPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_COMOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_COMPLETEAUTHTOKEN",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_COPYFILE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_CREATEDIRECTORY",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_CREATEFILE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_CRYPTACQUIRECONTEXT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_CRYPTIMPORTKEY",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_CRYPTOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_DECRYPTMESSAGE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_DELETEFILE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_DELETESECURITYCONTEXT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_DEVICEIOCONTROL",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_DEVICEOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_DIRSVC_NETWORKOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_DISCONNECTNAMEDPIPE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_DOMAINSERVICESOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_DSGETDCNAME",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_DTCOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_ENCRYPTMESSAGE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_FILEOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_FINDFILE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_FLUSHFILEBUFFERS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_FORMATMESSAGE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_FREECREDENTIALSHANDLE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_FREELIBRARY",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_GENERICOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_GETADDRINFO",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_GETCOMPRESSEDFILESIZE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_GETDISKFREESPACE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_GETFILEATTRIBUTES",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_GETFILESIZE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_GETLONGPATHNAME",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_GETPROCADDRESS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_GETVOLUMENAMEFORVOLUMEMOUNTPOINT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_GETVOLUMEPATHNAME",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_INITIALIZESECURITYCONTEXT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_LIBRARYOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_LOADLIBRARY",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_LOGONUSER",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_LOOKUPACCOUNTSID",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_MESSAGEQUEUEOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_MOVEFILE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_NETGROUPGETUSERS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_NETLOCALGROUPGETMEMBERS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_NETUSERGETGROUPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_NETUSERGETLOCALGROUPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_NETUSERMODALSGET",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_NETVALIDATEPASSWORDPOLICY",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_NETVALIDATEPASSWORDPOLICYFREE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_OPENDIRECTORY",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_PIPEOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_PROCESSOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_QUERYREGISTRY",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_QUERYSECURITYCONTEXTTOKEN",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_REMOVEDIRECTORY",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_REPORTEVENT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_REVERTTOSELF",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_RSFXDEVICEOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_SECURITYOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_SERVICEOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_SETENDOFFILE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_SETFILEPOINTER",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_SETFILEVALIDDATA",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_SETNAMEDSECURITYINFO",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_SQLCLROPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_SQMLAUNCH",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_VERIFYSIGNATURE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_VSSOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_WAITFORSINGLEOBJECT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_WINSOCKOPS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_WRITEFILE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_WRITEFILEGATHER",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_OS_WSASETLASTERROR",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_REENLIST",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_RESIZELOG",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_ROLLFORWARDREDO",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_ROLLFORWARDUNDO",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_SB_STOPENDPOINT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_SERVER_STARTUP",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_SETRMINFO",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_SHAREDMEM_GETDATA",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_SNIOPEN",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_SOSHOST",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_SOSTESTING",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_STARTRM",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_STREAMFCB_CHECKPOINT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_STREAMFCB_RECOVER",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_STRESSDRIVER",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_TESTING",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_TRANSIMPORT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_UNMARSHALPROPAGATIONTOKEN",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_VSS_CREATESNAPSHOT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_VSS_CREATEVOLUMESNAPSHOT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_XE_CALLBACKEXECUTE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_XE_DISPATCHER",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_XE_ENGINEINIT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_XE_GETTARGETSTATE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_XE_SESSIONCOMMIT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_XE_TARGETFINALIZE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_XE_TARGETINIT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_XE_TIMERRUN",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="PREEMPTIVE_XETESTING",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="PRINT_ROLLBACK_PROGRESS",Category="Other",Description="Caused while waiting for user processes to end in a database that has been transitioned by using the ALTER DATABASE termination clause. ",HelpLink="http://msdn.microsoft.com/en-us/library/ms174269.aspx"},
            new WaitTypeInfo(){WaitType="QNMANAGER_ACQUIRE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="QPJOB_KILL",Category="Other",Description="Caused when a asynchronous automatic statistics update is canceled by a call to KILL as the update was starting to run. The terminating thread is suspended, waiting for it to start listening for KILL commands. An acceptable value is less than one second.",HelpLink=""},
            new WaitTypeInfo(){WaitType="QPJOB_WAITFOR_ABORT",Category="Other",Description="Caused when an asynchronous automatic statistics update is canceled by a call to KILL when it was running. The update has now completed but is suspended until the terminating thread message coordination is complete. This is an ordinary but rare state, and should be very short. An acceptable value is less than one second.",HelpLink=""},
            new WaitTypeInfo(){WaitType="QRY_MEM_GRANT_INFO_MUTEX",Category="Other",Description="Caused when Query Execution memory management tries to control access to a static grant information list. This state lists information about the current granted and waiting memory requests and is a simple access control state. There should never be a long wait on this state.",HelpLink=""},
            new WaitTypeInfo(){WaitType="QUERY_ERRHDL_SERVICE_DONE",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="QUERY_EXECUTION_INDEX_SORT_EVENT_OPEN",Category="Other",Description="Caused when offline create index builds are run in parallel, and the different worker threads that are sorting synchronize access to the sort files.",HelpLink=""},
            new WaitTypeInfo(){WaitType="QUERY_NOTIFICATION_MGR_MUTEX",Category="Other",Description="Caused  during synchronization of the garbage collection queue in the Query Notification Manager.",HelpLink=""},
            new WaitTypeInfo(){WaitType="QUERY_NOTIFICATION_SUBSCRIPTION_MUTEX",Category="Other",Description="Caused during state synchronization for transactions in Query Notifications.",HelpLink=""},
            new WaitTypeInfo(){WaitType="QUERY_NOTIFICATION_TABLE_MGR_MUTEX",Category="Other",Description="Caused during internal synchronization within the Query Notification Manager.",HelpLink=""},
            new WaitTypeInfo(){WaitType="QUERY_NOTIFICATION_UNITTEST_MUTEX",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="QUERY_OPTIMIZER_PRINT_MUTEX",Category="Other",Description="Caused during synchronization of query optimizer diagnostic output production. This wait type only occurs if diagnostic settings have been enabled under direction of Microsoft Product Support.",HelpLink=""},
            new WaitTypeInfo(){WaitType="QUERY_TRACEOUT",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="QUERY_WAIT_ERRHDL_SERVICE",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="RECOVER_CHANGEDB",Category="Other",Description="Caused during synchronization of database status in warm standby database.",HelpLink=""},
            new WaitTypeInfo(){WaitType="REPL_CACHE_ACCESS",Category="Other",Description="Caused during synchronization on a replication article cache. During these waits, the replication log reader stalls, and data definition language (DDL) statements on a published table are blocked.",HelpLink=""},
            new WaitTypeInfo(){WaitType="REPL_HISTORYCACHE_ACCESS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="REPL_SCHEMA_ACCESS",Category="Other",Description="Caused during synchronization of replication schema version information. This state exists when DDL statements are executed on the replicated object, and when the log reader builds or consumes versioned schema based on DDL occurrence.",HelpLink=""},
            new WaitTypeInfo(){WaitType="REPL_TRANHASHTABLE_ACCESS",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="REPLICA_WRITES",Category="Other",Description="Caused when a task is waiting for completion of page writes to database snapshots or DBCC replicas.",HelpLink=""},
            new WaitTypeInfo(){WaitType="REQUEST_DISPENSER_PAUSE",Category="Other",Description="Caused when a task is waiting for all outstanding I/O to complete, so that I/O to a file can be frozen for snapshot backup.",HelpLink=""},
            new WaitTypeInfo(){WaitType="REQUEST_FOR_DEADLOCK_SEARCH",Category="Excluded",Description="Caused when the deadlock monitor waits to start the next deadlock search. This wait is expected between deadlock detections, and lengthy total waiting time on this resource does not indicate a problem.",HelpLink=""},
            new WaitTypeInfo(){WaitType="RESMGR_THROTTLED",Category="Other",Description="Caused when a new request comes in and is throttled based on the GROUP_MAX_REQUESTS setting.",HelpLink=""},
            new WaitTypeInfo(){WaitType="RESOURCE_QUEUE",Category="Excluded",Description="Caused during synchronization of various internal resource queues.",HelpLink=""},
            new WaitTypeInfo(){WaitType="RESOURCE_SEMAPHORE",Category="Memory",Description="Caused when a query memory request cannot be granted immediately due to other concurrent queries. Long waits and wait times may indicate excessive number of concurrent queries, or excessive memory request amounts.",HelpLink=""},
            new WaitTypeInfo(){WaitType="RESOURCE_SEMAPHORE_MUTEX",Category="Memory",Description="Caused when a query waits for its request for a thread reservation to be fulfilled. The wait also occurs when synchronizing query compile and memory grant requests.",HelpLink=""},
            new WaitTypeInfo(){WaitType="RESOURCE_SEMAPHORE_QUERY_COMPILE",Category="Memory",Description="Caused when the number of concurrent query compilations reaches a throttling limit. High waits and wait times may indicate excessive compilations, recompiles, or uncachable plans.",HelpLink=""},
            new WaitTypeInfo(){WaitType="RESOURCE_SEMAPHORE_SMALL_QUERY",Category="Memory",Description="Caused when memory request by a small query cannot be granted immediately due to other concurrent queries. Wait time should not exceed more than a few seconds, because the server transfers the request to the main query memory pool if it fails to grant the requested memory within a few seconds. High waits may indicate an excessive number of concurrent small queries while the main memory pool is blocked by waiting queries.",HelpLink=""},
            new WaitTypeInfo(){WaitType="RFS_MSGPUMP",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="RFS_NOTIFYTHREAD",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="RFS_STARTUP",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="RG_RECONFIG",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="SEC_DROP_TEMP_KEY",Category="Other",Description="Caused after a failed attempt to drop a temporary security key before a retry attempt.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SECURITY_MUTEX",Category="Other",Description="Caused when there is a wait for mutexes that control access to the global list of Extensible Key Management (EKM) cryptographic providers and the session-scoped list of EKM sessions.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SEQUENTIAL_GUID",Category="Other",Description="Caused when a new sequential GUID is being obtained.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SERVER_IDLE_CHECK",Category="Other",Description="Caused when synchronization of SQL Server instance idle status when a resource monitor is attempting to declare a SQL Server instance as idle or trying to wake up.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SHUTDOWN",Category="Other",Description="Caused when a shutdown statement waits for active connections to exit.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SLEEP_BPOOL_FLUSH",Category="Other",Description="Caused when a checkpoint is throttling the issuance of new I/Os in order to avoid flooding the disk subsystem.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SLEEP_DBSTARTUP",Category="Other",Description="Caused during database startup while waiting for all databases to recover.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SLEEP_DCOMSTARTUP",Category="Other",Description="Caused once at most during SQL Server instance startup while waiting for DCOM initialization to complete.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SLEEP_MSDBSTARTUP",Category="Other",Description="Caused when SQL Trace waits for the msdb database to complete startup.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SLEEP_SYSTEMTASK",Category="Excluded",Description="Caused during the start of a background task while waiting for tempdb to complete startup.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SLEEP_TASK",Category="Excluded",Description="Caused when a task sleeps while waiting for a generic event to occur.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SLEEP_TEMPDBSTARTUP",Category="Other",Description="Caused when a task waits for tempdb to complete startup.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SNI_CRITICAL_SECTION",Category="Other",Description="Caused when internal synchronization within SQL Server networking components.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SNI_HTTP_ACCEPT",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="SNI_HTTP_WAITFOR_0_DISCON",Category="Other",Description="Caused when a SQL Server shutdown occurs while waiting for outstanding HTTP connections to exit.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SNI_LISTENER_ACCESS",Category="Other",Description="Caused when waiting for non-uniform memory access (NUMA) nodes to update state change. The access to state change is serialized.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SNI_TASK_COMPLETION",Category="Other",Description="Caused when there is a wait for all tasks to finish during a NUMA node state change.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOAP_READ",Category="Other",Description="Caused when waiting for an HTTP network read to complete.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOAP_WRITE",Category="Other",Description="Caused when waiting for an HTTP network write to complete.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOS_CALLBACK_REMOVAL",Category="Other",Description="Caused when performing synchronization on a callback list in order to remove a callback. It is not expected for this counter to change after server initialization is completed.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOS_DISPATCHER_MUTEX",Category="Other",Description="Caused when internal synchronization of the dispatcher pool. This includes when the pool is being adjusted.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOS_LOCALALLOCATORLIST",Category="Other",Description="Caused when internal synchronization in the SQL Server memory manager occurs.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOS_MEMORY_USAGE_ADJUSTMENT",Category="Other",Description="Caused when memory usage is being adjusted among pools.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOS_OBJECT_STORE_DESTROY_MUTEX",Category="Other",Description="Caused when internal synchronization in memory pools destroys objects from the pool.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOS_PROCESS_AFFINITY_MUTEX",Category="Other",Description="Caused when synchronizing access to process affinity settings.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOS_RESERVEDMEMBLOCKLIST",Category="Memory",Description="Caused when internal synchronization in the SQL Server memory manager occurs.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOS_SCHEDULER_YIELD",Category="Other",Description="Caused when a task voluntarily yields the scheduler for other tasks to execute. During this wait the task is waiting for its quantum to be renewed.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOS_SMALL_PAGE_ALLOC",Category="Other",Description="Caused when the allocation and freeing of memory that is managed by some memory objects. You can safely ignore this wait if there are no unexplained problems with SQLTrace files not getting written to the disk properly.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOS_STACKSTORE_INIT_MUTEX",Category="Other",Description="Caused during the synchronization of internal store initialization.",HelpLink="WS SOS Stackstore.htm"},
            new WaitTypeInfo(){WaitType="SOS_SYNC_TASK_ENQUEUE_EVENT",Category="Other",Description="Caused when tasks are started in a synchronous manner. Most tasks in SQL Server are started in an asynchronous manner, in which control returns to the starter immediately after the task request has been placed on the work queue.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOS_VIRTUALMEMORY_LOW",Category="Other",Description="Caused when a memory allocation waits for a resource manager to free up virtual memory.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOSHOST_EVENT",Category="Other",Description="Caused when a hosted component, such as CLR, waits on a SQL Server event synchronization object.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOSHOST_INTERNAL",Category="Other",Description="Caused during synchronization of memory manager callbacks used by hosted components, such as the CLR.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOSHOST_MUTEX",Category="Other",Description="Caused when a hosted component, such as the CLR, waits on a SQL Server mutex synchronization object.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOSHOST_RWLOCK",Category="Other",Description="Caused when a hosted component, such as the CLR, waits on a SQL Server reader-writer synchronization object.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOSHOST_SEMAPHORE",Category="Other",Description="Caused when a hosted component, such as the CLR, waits on a SQL Server semaphore synchronization object.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOSHOST_SLEEP",Category="Other",Description="Caused when a hosted task sleeps while waiting for a generic event to occur. Hosted tasks are used by hosted components such as the CLR.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOSHOST_TRACELOCK",Category="Other",Description="Caused during synchronization of access to trace streams.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SOSHOST_WAITFORDONE",Category="Other",Description="Caused when a hosted component, such as the CLR, waits for a task to complete.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SQLCLR_APPDOMAIN",Category="Other",Description="Caused when the CLR waits for an application domain to complete startup.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SQLCLR_ASSEMBLY",Category="Other",Description="Caused when waiting for access to the loaded assembly list in the appdomain.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SQLCLR_DEADLOCK_DETECTION",Category="Other",Description="Caused when the CLR waits for deadlock detection to complete.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SQLCLR_QUANTUM_PUNISHMENT",Category="Other",Description="Caused when a CLR task is throttled because it has exceeded its execution quantum. This throttling is done in order to reduce the effect of this resource-intensive task on other tasks.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SQLSORT_NORMMUTEX",Category="Other",Description="Caused during internal synchronization, while initializing internal sorting structures.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SQLSORT_SORTMUTEX",Category="Other",Description="Caused during internal synchronization, while initializing internal sorting structures.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SQLTRACE_BUFFER_FLUSH",Category="Excluded",Description="Caused when a task is waiting for a background task to flush trace buffers to disk every four seconds.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SQLTRACE_LOCK",Category="Other",Description="Caused during synchronization on trace buffers during a file trace.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SQLTRACE_SHUTDOWN",Category="Other",Description="Caused when trace shutdown waits for outstanding trace events to complete.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SQLTRACE_WAIT_ENTRIES",Category="Other",Description="Caused when a SQL Trace event queue waits for packets to arrive on the queue.",HelpLink=""},
            new WaitTypeInfo(){WaitType="SRVPROC_SHUTDOWN",Category="Other",Description="Caused when the shutdown process waits for internal resources to be released to shutdown cleanly.",HelpLink=""},
            new WaitTypeInfo(){WaitType="TEMPOBJ",Category="Other",Description="Caused when temporary object drops are synchronized. This wait is rare, and only occurs if a task has requested exclusive access for temp table drops.",HelpLink=""},
            new WaitTypeInfo(){WaitType="THREADPOOL",Category="Other",Description="Caused when a task is waiting for a worker to run on. This can indicate that the maximum worker setting is too low, or that batch executions are taking unusually long, thus reducing the number of workers available to satisfy other batches.",HelpLink="WS Threadpool.htm"},
            new WaitTypeInfo(){WaitType="TIMEPRIV_TIMEPERIOD",Category="Other",Description="Caused during internal synchronization of the Extended Events timer.",HelpLink=""},
            new WaitTypeInfo(){WaitType="TRACE_EVTNOTIF",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="TRACEWRITE",Category="Other",Description="Caused when the SQL Trace rowset trace provider waits for either a free buffer or a buffer with events to process.",HelpLink=""},
            new WaitTypeInfo(){WaitType="TRAN_MARKLATCH_DT",Category="Non-Page Latch",Description="Caused when waiting for a destroy mode latch on a transaction mark latch. Transaction mark latches are used for synchronization of commits with marked transactions.",HelpLink=""},
            new WaitTypeInfo(){WaitType="TRAN_MARKLATCH_EX",Category="Non-Page Latch",Description="Caused when waiting for an exclusive mode latch on a marked transaction. Transaction mark latches are used for synchronization of commits with marked transactions.",HelpLink=""},
            new WaitTypeInfo(){WaitType="TRAN_MARKLATCH_KP",Category="Non-Page Latch",Description="Caused when waiting for a keep mode latch on a marked transaction. Transaction mark latches are used for synchronization of commits with marked transactions.",HelpLink=""},
            new WaitTypeInfo(){WaitType="TRAN_MARKLATCH_NL",Category="Non-Page Latch",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="TRAN_MARKLATCH_SH",Category="Non-Page Latch",Description="Caused when waiting for a shared mode latch on a marked transaction. Transaction mark latches are used for synchronization of commits with marked transactions.",HelpLink=""},
            new WaitTypeInfo(){WaitType="TRAN_MARKLATCH_UP",Category="Non-Page Latch",Description="Caused when waiting for an update mode latch on a marked transaction. Transaction mark latches are used for synchronization of commits with marked transactions.",HelpLink=""},
            new WaitTypeInfo(){WaitType="TRANSACTION_MUTEX",Category="Other",Description="Caused during synchronization of access to a transaction by multiple batches.",HelpLink=""},
            new WaitTypeInfo(){WaitType="UTIL_PAGE_ALLOC",Category="Other",Description="Caused when transaction log scans wait for memory to be available during memory pressure.",HelpLink=""},
            new WaitTypeInfo(){WaitType="VIA_ACCEPT",Category="Other",Description="Caused when a Virtual Interface Adapter (VIA) provider connection is completed during startup.",HelpLink=""},
            new WaitTypeInfo(){WaitType="VIEW_DEFINITION_MUTEX",Category="Other",Description="Caused during synchronization on access to cached view definitions.",HelpLink=""},
            new WaitTypeInfo(){WaitType="WAIT_FOR_RESULTS",Category="Other",Description="Caused when waiting for a query notification to be triggered.",HelpLink=""},
            new WaitTypeInfo(){WaitType="WAITFOR",Category="Excluded",Description="Caused as a result of a WAITFOR Transact-SQL statement. The duration of the wait is determined by the parameters to the statement. This is a user-initiated wait.",HelpLink=""},
            new WaitTypeInfo(){WaitType="WAITFOR_TASKSHUTDOWN",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="WAITSTAT_MUTEX",Category="Other",Description="Caused during synchronization of access to the collection of statistics used to populate sys.dm_os_wait_stats.",HelpLink=""},
            new WaitTypeInfo(){WaitType="WCC",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="WORKTBL_DROP",Category="Other",Description="Caused when pausing before retrying, after a failed worktable drop.",HelpLink=""},
            new WaitTypeInfo(){WaitType="WRITE_COMPLETION",Category="Other",Description="Caused when a write operation is in progress.",HelpLink=""},
            new WaitTypeInfo(){WaitType="WRITELOG",Category="Transaction Log",Description="Caused when waiting for a log flush to complete. Common operations that cause log flushes are checkpoints and transaction commits.",HelpLink=""},
            new WaitTypeInfo(){WaitType="XACT_OWN_TRANSACTION",Category="Other",Description="Caused when waiting to acquire ownership of a transaction.",HelpLink=""},
            new WaitTypeInfo(){WaitType="XACT_RECLAIM_SESSION",Category="Other",Description="Caused when waiting for the current owner of a session to release ownership of the session.",HelpLink=""},
            new WaitTypeInfo(){WaitType="XACTLOCKINFO",Category="Lock",Description="Caused during synchronization of access to the list of locks for a transaction. In addition to the transaction itself, the list of locks is accessed by operations such as deadlock detection and lock migration during page splits.",HelpLink=""},
            new WaitTypeInfo(){WaitType="XACTWORKSPACE_MUTEX",Category="Other",Description="Caused during synchronization of defections from a transaction, as well as the number of database locks between enlist members of a transaction.",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_BUFFERMGR_ALLPROCESSED_EVENT",Category="Other",Description="Caused when Extended Events session buffers are flushed to targets. This wait occurs on a background thread.",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_BUFFERMGR_FREEBUF_EVENT",Category="Other",Description="Caused when either of the following conditions is true: (1) An Extended Events session is configured for no event loss, and all buffers in the session are currently full. This can indicate that the buffers for an Extended Events session are too small, or should be partitioned. (2) Audits experience a delay. This can indicate a disk bottleneck on the drive where the audits are written.",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_DISPATCHER_CONFIG_SESSION_LIST",Category="Other",Description="Caused when an Extended Events session that is using asynchronous targets is started or stopped. This wait indicates either of the following: (1) An Extended Events session is registering with a background thread pool. (2) The background thread pool is calculating the required number of threads based on current load.",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_DISPATCHER_JOIN",Category="Other",Description="Caused when a background thread that is used for Extended Events sessions is terminating.",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_DISPATCHER_WAIT",Category="Excluded",Description="Caused when a background thread that is used for Extended Events sessions is waiting for event buffers to process.",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_MODULEMGR_SYNC",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_OLS_LOCK",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_PACKAGE_LOCK_BACKOFF",Category="Other",Description="Used for informational purposes only.",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_SERVICES_EVENTMANUAL",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_SERVICES_MUTEX",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_SERVICES_RWLOCK",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_SESSION_CREATE_SYNC",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_SESSION_FLUSH",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_SESSION_SYNC",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_STM_CREATE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_TIMER_EVENT",Category="Excluded",Description="Indicates a background task is waiting for \"expired\" timers for internal Xevent engine work",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_TIMER_MUTEX",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="XE_TIMER_TASK_DONE",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="SQLTRACE_FILE_BUFFER",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="SQLTRACE_INCREMENTAL_FLUSH_SLEEP",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="SQLTRACE_FILE_WRITE_IO_COMPLETION",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="SQLTRACE_FILE_READ_IO_COMPLETION",Category="Other",Description="",HelpLink=""},
            new WaitTypeInfo(){WaitType="SQLTRACE_PENDING_BUFFER_WRITERS",Category="Other",Description="",HelpLink=""},
        };
        static WaitStatsHelper()
        {
            _waitInfo.Sort();
        }

        static internal WaitTypeInfo GetWaitInfo(string waitType)
        {
            int n = _waitInfo.BinarySearch(new WaitTypeInfo() { WaitType = waitType });
            if ((n >= 0) && (n < _waitInfo.Count)) return (_waitInfo[n]);
            return (null);
        }

        internal class WaitTypeInfo : IComparable
        {
            public string WaitType { get; set; }
            public string Category { get; set; }
            public string Description { get; set; }
            public string HelpLink { get; set; }

            public int CompareTo(object obj)
            {
                WaitTypeInfo wi = obj as WaitTypeInfo;
                if (null != wi) return (WaitType.CompareTo(wi.WaitType));
                return (WaitType.CompareTo(obj));
            }
        }
    }
}
