//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idera.SQLdm.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProbePermissionsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProbePermissionsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Idera.SQLdm.Common.ProbePermissionsResource", typeof(ProbePermissionsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It It requires ALTER ANY EVENT SESSION or ALTER TRACE, and TempDb Db_Owner or Tempdb Db_DataWriter permission.
        /// </summary>
        public static string ActiveWaits {
            get {
                return ResourceManager.GetString("ActiveWaits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It It requires ALTER ANY EVENT SESSION and TempDb Db_Owner or Tempdb Db_DataWriter permission ..
        /// </summary>
        public static string ActiveWaitsEx {
            get {
                return ResourceManager.GetString("ActiveWaitsEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW DATABASE STATE and DB_Owner for Tempdb ..
        /// </summary>
        public static string ActiveWaitsQs {
            get {
                return ResourceManager.GetString("ActiveWaitsQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires ALTER TRACE..
        /// </summary>
        public static string ActiveWaitsTrc {
            get {
                return ResourceManager.GetString("ActiveWaitsTrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires ALTER TRACE permission or ALTER ANY EVENT SESSION,  and TempDb Db_Owner or Tempdb Db_DataWriter permission and VIEW DATABASE STATE (on Azure SQL Database) permissions..
        /// </summary>
        public static string ActivityMonitor {
            get {
                return ResourceManager.GetString("ActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires access to MSDB..
        /// </summary>
        public static string AgentJobHistory {
            get {
                return ResourceManager.GetString("AgentJobHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires access to MSDB, EXECUTE on master..xp_sqlagent_enum_jobs, EXECUTE on msdb..sp_get_composite_job_info or Db_Owner in MSDB, 
        ///&quot;Sysadmin or SQLAgentOperatorRole or SQLAgentReaderRole in MSDB&quot;, &quot;user will be able to control services only if using SYSADMIN role or for SQL 2008 R2 and above 
        ///for viewing sercvices status, SELECT permission on sys.dm_server_services is required&quot;.
        /// </summary>
        public static string AgentJobSummary {
            get {
                return ResourceManager.GetString("AgentJobSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW ANY DEFINITION, VIEW ANY DATABASE and VIEW SERVER STATE permissions, ALTERANYDATABASE, CREATEDATABASE and metadata visibility for master.sys.availability_group_listener_ip_addresses and master.sys.availability_group_listeners..
        /// </summary>
        public static string AlwaysOnMetrics {
            get {
                return ResourceManager.GetString("AlwaysOnMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE permission..
        /// </summary>
        public static string AlwaysOnStatistics2012 {
            get {
                return ResourceManager.GetString("AlwaysOnStatistics2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires access to MSDB and Sysadmin role and ALTER ANY DATABASE or VIEW ANY DATABASE, and VIEW ANY DEFINITION permissions..
        /// </summary>
        public static string BackupAndRecovery {
            get {
                return ResourceManager.GetString("BackupAndRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires access to MSDB BACKUPFILE,BACKUPMEDIAFAMILY, BACKUPSET and RESTOREHISTORY..
        /// </summary>
        public static string BackupRestoreHistory {
            get {
                return ResourceManager.GetString("BackupRestoreHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires access to MSDB SYSCATEGORIES,SYSJOBHISTORY,SYSJOBS and SYSJOBSTEPS..
        /// </summary>
        public static string BombedJobVariablesStore {
            get {
                return ResourceManager.GetString("BombedJobVariablesStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, VIEW DATABASE STATE, Server admin account or an Azure Active Directory admin account for Azure SQL Database..
        /// </summary>
        public static string BUFFERPOOLEXTIO {
            get {
                return ResourceManager.GetString("BUFFERPOOLEXTIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, VIEW DATABASE STATE, Server admin account or an Azure Active Directory admin account for Azure SQL Database..
        /// </summary>
        public static string ColumnStoreIndex {
            get {
                return ResourceManager.GetString("ColumnStoreIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW DEFINITION, ALTER ANY DATABASE or the VIEW ANY DATABASE, Server admin or an Azure Active Directory admin account for Azure SQL Database, CONTROL SERVER (may be disabled).
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires SYSADMIN role..
        /// </summary>
        public static string CustomCounterOS {
            get {
                return ResourceManager.GetString("CustomCounterOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DatabaseConfiguration {
            get {
                return ResourceManager.GetString("DatabaseConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires ALTER ANY DATABASE or VIEW ANY DATABASE permissions.
        /// </summary>
        public static string DatabaseConfiguration2012 {
            get {
                return ResourceManager.GetString("DatabaseConfiguration2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW ANY DATABASE, VIEW SERVER STATE,VIEW ANY DEFINITION and CREATE DATABASE or ALTER ANY DATABASE permissions..
        /// </summary>
        public static string DatabaseFileInfo {
            get {
                return ResourceManager.GetString("DatabaseFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires Server admin account or an Azure Active Directory admin account, VIEW SERVER STATE, VIEW DATABASE STATE, VIEW ANY DATABASE,
        ///        ALTER ANY DATABASE, CREATE DATABASE, ALTER SERVER STATE	and Metadata visibility for Sysfilegroups and Sysfiles.
        /// </summary>
        public static string DatabaseFiles {
            get {
                return ResourceManager.GetString("DatabaseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires access to MSDB..
        /// </summary>
        public static string DatabaseLastBackupDateTime {
            get {
                return ResourceManager.GetString("DatabaseLastBackupDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE permission..
        /// </summary>
        public static string DatabaseRanking2005 {
            get {
                return ResourceManager.GetString("DatabaseRanking2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, ALTER SERVER STATE, CREATE DATABASE, ALTER ANY DATABASE, or VIEW ANY DEFINITION, Tempdb db_owner access,
        ///          Server admin account or an Azure Active Directory admin account (Azure SQL Database), Access to MSDB,
        ///         and Metadata Visibility for sys.internal_tables, sysfiles, sySysAllocationUnits,SysPartitions and Temp DB SysDatabaseFiles.
        /// </summary>
        public static string DatabaseSize {
            get {
                return ResourceManager.GetString("DatabaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires Sysadmin role for viewing data using OLE Automation, ALTER SERVER STATE, VIEW SERVER STATE, VIEW DATABASE STATE, Server admin account or an Azure Active Directory admin account (Azure SQL Database), Access to MSDB
        ///	and Metadata visibility for sysfilegroups, sysfiles, sysallobjects,sysinternaltables, tempdb sysobjects..
        /// </summary>
        public static string DatabaseSummary {
            get {
                return ResourceManager.GetString("DatabaseSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW ANY DATABASE, SYSADMIN role and metadata visibility for sys.symmetric_keys and sysusers..
        /// </summary>
        public static string DBSecurity {
            get {
                return ResourceManager.GetString("DBSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires metadata visibility for  sys.assemblies, sys.assembly_modules, sys.assembly_references, sys.assembly_types, sys.columns, sys.foreign_keys, sys.indexes, sys.objects, sys.parameters, sys.synonyms, sys.tables, sys.types and sys.xml_schema_collections..
        /// </summary>
        public static string DependentObject {
            get {
                return ResourceManager.GetString("DependentObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires metadata visibility for sys.indexes..
        /// </summary>
        public static string DisabledIndexes {
            get {
                return ResourceManager.GetString("DisabledIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires SYSADMIN role for OLEAutomation, VIEW ANY DEFINITION permissions, CREATE DATABASE and ALTER ANY DATABASE..
        /// </summary>
        public static string DiskDrives {
            get {
                return ResourceManager.GetString("DiskDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires ALTER ANY LINKED SERVER or ALTER ANY LOGIN ON SERVER (for Linked Servers) permission.
        ///	It requires SETUPADMIN member or Sysadmin member..
        /// </summary>
        public static string DistributorDetails {
            get {
                return ResourceManager.GetString("DistributorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, VIEW DATABASE STATE, Server admin account or an Azure Active Directory admin account (Azure SQL Database), and ALTER SERVER STATE permissions..
        /// </summary>
        public static string DropPlans {
            get {
                return ResourceManager.GetString("DropPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires sysadmin member role for OLE Automation to collect data..
        /// </summary>
        public static string DTCStatus {
            get {
                return ResourceManager.GetString("DTCStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires access to MSDB..
        /// </summary>
        public static string FailedVariables {
            get {
                return ResourceManager.GetString("FailedVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires sysadmin member role for collecting data via OLE Automation..
        /// </summary>
        public static string FileActivity {
            get {
                return ResourceManager.GetString("FileActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, CREATE DATABASE, ALTER ANY DATABASE, or VIEW ANY DEFINITION permissions and membership in SYSADMIN role..
        /// </summary>
        public static string FileActivity2005 {
            get {
                return ResourceManager.GetString("FileActivity2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires membership of SERVERADMIN role, and CREATE DATABASE, ALTER ANY DATABASE, or VIEW ANY DEFINITION permissions..
        /// </summary>
        public static string FileGroup {
            get {
                return ResourceManager.GetString("FileGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires metadata visibility for sys.columns, sys.index_columns and sys.indexes..
        /// </summary>
        public static string FilteredColumnNotInKeyOfFilteredIndex {
            get {
                return ResourceManager.GetString("FilteredColumnNotInKeyOfFilteredIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, VIEW DATABASE STATE (Azure SQL Database) permissions and metadata visibility for sys.indexes..
        /// </summary>
        public static string FragmentedIndexes2005 {
            get {
                return ResourceManager.GetString("FragmentedIndexes2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires CREATE DATABASE, VIEW SERVER STATE, VIEW DATABASE STATE (Azure SQL Database), ALTER ANY USER permissions and metadata visibility for sys.fulltext_catalogs and sysobjects..
        /// </summary>
        public static string FullTextCatalogs {
            get {
                return ResourceManager.GetString("FullTextCatalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires metadata visibility for syscolumns and systypes..
        /// </summary>
        public static string FullTextColumns {
            get {
                return ResourceManager.GetString("FullTextColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires sysadmin member role for OLE Automation to collect data..
        /// </summary>
        public static string FullTextSearchService {
            get {
                return ResourceManager.GetString("FullTextSearchService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FULLTEXTTABLES.
        /// </summary>
        public static string FullTextTables {
            get {
                return ResourceManager.GetString("FullTextTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE and VIEW DATABASE STATE (Azure SQL Database) permissions..
        /// </summary>
        public static string GetAdhocCachedPlanBytes2005 {
            get {
                return ResourceManager.GetString("GetAdhocCachedPlanBytes2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE and VIEW DATABASE STATE (Azure SQL Database) permissions..
        /// </summary>
        public static string GetLockedPageKB2008 {
            get {
                return ResourceManager.GetString("GetLockedPageKB2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires SYSADMIN role, or VIEW SERVER STATE and VIEW DATABASE STATE (Azure SQL Database) permissions, and metadata visibility for sys.hash_indexes..
        /// </summary>
        public static string HashIndex {
            get {
                return ResourceManager.GetString("HashIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE and VIEW DATABASE STATE (Azure SQL Database), SERVERADMIN or AzureAdmin permissions..
        /// </summary>
        public static string HighCPUTimeProcedures {
            get {
                return ResourceManager.GetString("HighCPUTimeProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires SERVERADMIN and VIEW SERVER STATE, AzureAdmin and VIEW DATABASE STATE (Azure SQL Database) permissions and metadata visiblity for sys.indexes and sys.tables..
        /// </summary>
        public static string HighIndexUpdates {
            get {
                return ResourceManager.GetString("HighIndexUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW DATABASE STATE and metadata visiblity for sys.indexes and sys.objects..
        /// </summary>
        public static string IndexContention {
            get {
                return ResourceManager.GetString("IndexContention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires to be a member of SYSADMIN, DB_OWNER or DB_DDLADMIN roles and metadata visibility for Sysobjects..
        /// </summary>
        public static string IndexStatistics {
            get {
                return ResourceManager.GetString("IndexStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires EXECUTE permission and access to MSDB..
        /// </summary>
        public static string JobAlerts {
            get {
                return ResourceManager.GetString("JobAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires select permissions on table or needs to have SYSADMIN, DB_OWNER or DB_DDLADMIN roles, and metadata visibility for sys.stats..
        /// </summary>
        public static string LargeTableStats {
            get {
                return ResourceManager.GetString("LargeTableStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, VIEW DATABASE STATE permissions, and Server admin account or an Azure Active Directory admin account (Azure SQL Database)..
        /// </summary>
        public static string LockCounterStatistics2005 {
            get {
                return ResourceManager.GetString("LockCounterStatistics2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, VIEW DATABASE STATE (Azure SQL Database Premium), Server admin or an Azure Active Directory admin account (Azure SQL Database Std or Basic), 
        ///	Meta Visibility Configuration for sys.all_objects, sysobjects and SysPartitions.
        /// </summary>
        public static string LockDetails {
            get {
                return ResourceManager.GetString("LockDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE and VIEW DATABASE STATE (Azure SQL Database) permissions and SERVERADMIN or AzureAdmin account..
        /// </summary>
        public static string LockedPageKB {
            get {
                return ResourceManager.GetString("LockedPageKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires EXECUTE permission on master..xp_instance_regread and master..xp_readerrorlog..
        /// </summary>
        public static string LogList {
            get {
                return ResourceManager.GetString("LogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires EXECUTE permission on master..xp_instance_regread and master..xp_readerrorlog..
        /// </summary>
        public static string LogList2005 {
            get {
                return ResourceManager.GetString("LogList2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires SecurityAdmin server-level role or the View Server State permissions..
        /// </summary>
        public static string LogScan {
            get {
                return ResourceManager.GetString("LogScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires SecurityAdmin server-level role permission..
        /// </summary>
        public static string LogScanvariablestore {
            get {
                return ResourceManager.GetString("LogScanvariablestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires minimum permissions VIEWANYDATABASE, VIEWANYDEFINITION and VIEWSERVERSTATE.
        /// </summary>
        public static string MinimumPermissions {
            get {
                return ResourceManager.GetString("MinimumPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires minimum permissions VIEWANYDATABASE, VIEWANYDEFINITION and VIEWSERVERSTATE.
        /// </summary>
        public static string MinimumPermissions1 {
            get {
                return ResourceManager.GetString("MinimumPermissions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires minimum permissions VIEWANYDATABASE, VIEWANYDEFINITION, VIEWSERVERSTATE and VIEWDATABASESTATE.
        /// </summary>
        public static string MinimumPermissions2 {
            get {
                return ResourceManager.GetString("MinimumPermissions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires minimum permissions VIEWANYDATABASE, VIEWANYDEFINITION and VIEWSERVERSTATE.
        /// </summary>
        public static string MinimumPermissions3 {
            get {
                return ResourceManager.GetString("MinimumPermissions3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires SYSADMIN role and ALTER ANY DATABASE or VIEW ANY DATABASE permissions..
        /// </summary>
        public static string MirrorMetricsUpdateCallback {
            get {
                return ResourceManager.GetString("MirrorMetricsUpdateCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires SYSADMIN or DBM_MONITOR roles..
        /// </summary>
        public static string MirrorMonitoringHistoryCallback {
            get {
                return ResourceManager.GetString("MirrorMonitoringHistoryCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires SYSADMIN or DBM_MONITOR role, ALTER ANY DATABASE or VIEW ANY DATABASE, VIEW SERVER STATE, VIEW DATABASE STATE (Azure SQL Database Premium) permissions and Server admin account or an Azure Active Directory admin account (Azure SQL Database Std or Basic) and SYSADMIN or DBM_MONITOR roles..
        /// </summary>
        public static string MirrorMonitoringRealtime {
            get {
                return ResourceManager.GetString("MirrorMonitoringRealtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires ALTER ANY DATABASE or CREATEDATABASE permissions and SYSADMIN or DBM_MONITOR roles..
        /// </summary>
        public static string MirrorMonitoringRealtimeCallback {
            get {
                return ResourceManager.GetString("MirrorMonitoringRealtimeCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires metadata visibility for sys.columns, sys.indexes, sys.stats and sys.stats_columns..
        /// </summary>
        public static string NonIncrementalColumnStatsCallback {
            get {
                return ResourceManager.GetString("NonIncrementalColumnStatsCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, VIEW DATABASE STATE(Azure SQL Database Premium) permissions, and Server admin account or an Azure Active Directory admin account (Azure SQL Database Std or Basic)..
        /// </summary>
        public static string NUMANodeCounters {
            get {
                return ResourceManager.GetString("NUMANodeCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, VIEW DATABASE STATE(Azure SQL Database Premium) permissions, and Server admin account or an Azure Active Directory admin account (Azure SQL Database Std or Basic)..
        /// </summary>
        public static string OldestOpenTransaction {
            get {
                return ResourceManager.GetString("OldestOpenTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires SYSADMIN role..
        /// </summary>
        public static string OSMetrics {
            get {
                return ResourceManager.GetString("OSMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires metadata visibility for sys.objects and sysindexes..
        /// </summary>
        public static string OutOfDateStats {
            get {
                return ResourceManager.GetString("OutOfDateStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, VIEW DATABASE STATE(Azure SQL Database Premium) permissions, and Server admin account or an Azure Active Directory admin account (Azure SQL Database Std or Basic) and metadata visibility for sys.foreign_keys, sys.index_columns, sys.indexes and sys.objects..
        /// </summary>
        public static string OverlappingIndexes {
            get {
                return ResourceManager.GetString("OverlappingIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, VIEW DATABASE STATE(Azure SQL Database Premium) permissions, and Server admin account or an Azure Active Directory admin account (Azure SQL Database Std or Basic) and metadata visibility for sys.foreign_keys, sys.index_columns, sys.indexes and sys.objects..
        /// </summary>
        public static string OverlappingIndexes2008 {
            get {
                return ResourceManager.GetString("OverlappingIndexes2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, VIEW DATABASE STATE(Azure SQL Database Premium) permissions, and Server admin account or an Azure Active Directory admin account (Azure SQL Database Std or Basic)..
        /// </summary>
        public static string ProcedureCache {
            get {
                return ResourceManager.GetString("ProcedureCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reuqires VIEW DATABASE STATE permission..
        /// </summary>
        public static string QueryAnalyzer2016 {
            get {
                return ResourceManager.GetString("QueryAnalyzer2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW DATABASE STATE and DB_Owner for Tempdb for Query Store or ALTER ANY EVENT SESSION for Extended Events or ALTER TRACE for Trace..
        /// </summary>
        public static string QueryMonitor {
            get {
                return ResourceManager.GetString("QueryMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires metadata visibility for temp db sysobjects)..
        /// </summary>
        public static string QueryMonitorStateStore {
            get {
                return ResourceManager.GetString("QueryMonitorStateStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, VIEW DATABASE STATE(Azure SQL Database Premium) permissions, and Server admin account or an Azure Active Directory admin account (Azure SQL Database Std or Basic)..
        /// </summary>
        public static string QueryPlanEstRows {
            get {
                return ResourceManager.GetString("QueryPlanEstRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW DATABASE STATE and metadata visibility for sys.plan_guides..
        /// </summary>
        public static string QueryStore {
            get {
                return ResourceManager.GetString("QueryStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW DATABASE STATE and metadata visibility for sys.indexes..
        /// </summary>
        public static string RarelyUsedIndexOnInMemoryTable {
            get {
                return ResourceManager.GetString("RarelyUsedIndexOnInMemoryTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires ALTER, CREATE DATABASE and VIEW DATABASE STATE permissions, should be a member of SYSADMIN, DB_OWNER, or DB_DDLADMIN roles and should have metadata visibility for sys.columns, sys.index_columns, sys.indexes, sys.types, sys.xml_indexes and sysobjects..
        /// </summary>
        public static string Reindex2005 {
            get {
                return ResourceManager.GetString("Reindex2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires CREATE DATABASE, VIEW SERVER STATE, ALTER ANY LINKED SERVER or ALTER ANY LOGIN ON SERVER (for Linked Servers) and EXECUTE(in master) permissions, SYSADMIN role at the Publisher and DB_OWNER role on the publication database, and metadata visibility for sysobjects..
        /// </summary>
        public static string Replication {
            get {
                return ResourceManager.GetString("Replication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires SYSADMIN role..
        /// </summary>
        public static string ReplicationStatus {
            get {
                return ResourceManager.GetString("ReplicationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires access to MSDB..
        /// </summary>
        public static string RestoreHistoryFull {
            get {
                return ResourceManager.GetString("RestoreHistoryFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires access to MSDB..
        /// </summary>
        public static string RestoreHistorySmall {
            get {
                return ResourceManager.GetString("RestoreHistorySmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, VIEW DATABASE STATE(Azure SQL Database Premium) permissions, and Server admin account or an Azure Active Directory admin account (Azure SQL Database Std or Basic)..
        /// </summary>
        public static string SampleServerResources {
            get {
                return ResourceManager.GetString("SampleServerResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Action missing permissions for {0} action.
        /// </summary>
        public static string ServerAction {
            get {
                return ResourceManager.GetString("ServerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Action - FullTextActionConfiguration. It requires DbOwner in {0} database..
        /// </summary>
        public static string ServerActionFullTextActionConfiguration {
            get {
                return ResourceManager.GetString("ServerActionFullTextActionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Action - MirroringPartnerActionConfiguration. It requires visibility of the metadata for sysobjects,sysindexcolumns, sysindexes, systypes, sysxmlindexes, syscolumns
        ///	and ALTER permission on the table or view id {1} in {0} database..
        /// </summary>
        public static string ServerActionMirroringPartnerActionConfiguration {
            get {
                return ResourceManager.GetString("ServerActionMirroringPartnerActionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires ALTER on {0} database and and Control on table id {1}, CREATE DATABASE and VIEW DATABASE STATE permissions, should be a member of SYSADMIN, DB_OWNER, or DB_DDLADMIN roles and should have metadata visibility for sys.columns, sys.index_columns, sys.indexes, sys.types, sys.xml_indexes and sysobjects..
        /// </summary>
        public static string ServerActionReindexConfiguration {
            get {
                return ResourceManager.GetString("ServerActionReindexConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerAction - UpdateStatisticsConfiguration. It requires visibility of the metadata for sysobjects,sysindexcolumns, sysindexes, systypes, sysxmlindexes, syscolumns
        ///	and ALTER permission on the table or view id {1} in {0} database..
        /// </summary>
        public static string ServerActionUpdateStatisticsConfiguration {
            get {
                return ResourceManager.GetString("ServerActionUpdateStatisticsConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires ALTERSETTINGS, VIEWDEFINITION, SYSADMINMember and EXECUTEMASTERDBOXPINSTANCEREGREAD Permissions..
        /// </summary>
        public static string ServerBasics {
            get {
                return ResourceManager.GetString("ServerBasics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires ALTER ANY LOGIN, ALTER ANY USER, CREATEDATABASE, ALTERANYDATABASE ,VIEW SERVER STATE and VIEW ANY DEFINITION permissions, access to MSDB and SYSADMIN role..
        /// </summary>
        public static string ServerConfiguration {
            get {
                return ResourceManager.GetString("ServerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires CREATE DATABASE, VIEW SERVER STATE, VIEW DATABASE STATE, VIEW ANY DEFINITION and VIEW ANY DATABASE permissions, ALTER ANY DATABASE permission, TempDb Db_Owner permission
        ///Server admin account or an Azure Active Directory admin account (SQL Database Standard and Basic Tiers)..
        /// </summary>
        public static string ServerDetails {
            get {
                return ResourceManager.GetString("ServerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires CREATEDATABASE, VIEWDEFINITION or ALTERSERVERSTATE, CONTROLSERVER or EXECUTE permission on master..xp_loginconfig and EXECUTE permission on master..dbo.xp_regread
        ///It requires SERVERADMIN or Azure Admin for Cloud..
        /// </summary>
        public static string ServerOverview {
            get {
                return ResourceManager.GetString("ServerOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires SYSADMIN role for OLE Automation sp_OACreate.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE permission..
        /// </summary>
        public static string SessionCount {
            get {
                return ResourceManager.GetString("SessionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires ALTER TRACE, and metadata visibility for master.sys.traces, sysobjects and Server admin account or an Azure Active Directory admin account..
        /// </summary>
        public static string SessionDetails {
            get {
                return ResourceManager.GetString("SessionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires SYSADMIN role, VIEW SERVER STATE, VIEW DATABASE STATE permissions, and Server admin account or an Azure Active Directory admin account (SQL Database Standard and Basic Tiers)..
        /// </summary>
        public static string SessionDetails2005 {
            get {
                return ResourceManager.GetString("SessionDetails2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User must be a member of the sysadmin fixed server role, or User must have VIEW SERVER STATE permission, or session_id must be the same as the session ID on which the command is being run and CREATE Database. Server admin account or an Azure Active Directory admin account (SQL Database Standard and Basic Tiers)..
        /// </summary>
        public static string SessionList {
            get {
                return ResourceManager.GetString("SessionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, VIEW DATABASE STATE(Azure SQL Database Premium) permissions, and Server admin account or an Azure Active Directory admin account (Azure SQL Database Std or Basic)..
        /// </summary>
        public static string SessionSummary {
            get {
                return ResourceManager.GetString("SessionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, VIEW DATABASE STATE(Azure SQL Database Premium) permissions, and Server admin account or an Azure Active Directory admin account (Azure SQL Database Std or Basic)..
        /// </summary>
        public static string SessionSummary2005 {
            get {
                return ResourceManager.GetString("SessionSummary2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires SYSADMIN role..
        /// </summary>
        public static string sp_OACheckTest {
            get {
                return ResourceManager.GetString("sp_OACheckTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires metadata visibility for sys.all_objects, sys.all_sql_modules, sys.objects, and sys.schemas..
        /// </summary>
        public static string SQLModuleOptions {
            get {
                return ResourceManager.GetString("SQLModuleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires ALTER TRACE permission and metadata visibility for master.sys.traces and tempdb..sysobjects..
        /// </summary>
        public static string StopSessionDetailsTrace2005 {
            get {
                return ResourceManager.GetString("StopSessionDetailsTrace2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires metadata visibility for sysdepends, sysindexes, sysobjects and sysreferences. .
        /// </summary>
        public static string TableDetails {
            get {
                return ResourceManager.GetString("TableDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires CONTROL permission on the specified object within the database, VIEW DATABASE STATE and VIEW SERVER STATE permissions based on certain conditions..
        /// </summary>
        public static string TableFragmentation {
            get {
                return ResourceManager.GetString("TableFragmentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires metadata visibility for  sysindexes, sysobjects and syscolumns.
        /// </summary>
        public static string TableFragmentationWorkload {
            get {
                return ResourceManager.GetString("TableFragmentationWorkload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW ANY DATABASE, VIEW SERVER STATE, VIEW DATABASE STATE permissions, and Server admin account or an Azure Active Directory admin account (Azure SQL Database Std or Basic).
        ///	It requires metadata visibility for sys.indexes, sys.internal_tables, and sys.objects.
        /// </summary>
        public static string TableGrowth {
            get {
                return ResourceManager.GetString("TableGrowth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires CREATE DATABASE permission and metadata visibility for sys.fulltext_catalogs, sys.indexes, sys.internal_tables, and sys.objects..
        /// </summary>
        public static string TableSummary {
            get {
                return ResourceManager.GetString("TableSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, VIEW DATABASE STATE permissions, and Server admin account or an Azure Active Directory admin account (Azure SQL Database Std or Basic)..
        /// </summary>
        public static string WaitingBatches {
            get {
                return ResourceManager.GetString("WaitingBatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires VIEW SERVER STATE, VIEW DATABASE STATE permissions, and Server admin account or an Azure Active Directory admin account (Azure SQL Database Std or Basic)..
        /// </summary>
        public static string WaitStats {
            get {
                return ResourceManager.GetString("WaitStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It requires ALTER ANY DATABASE or the VIEW ANY DATABASE, and VIEW SERVER STATE permissions, and metadata visibility for sys.internal_tables, sys.objects, and sys.sysindexes. .
        /// </summary>
        public static string WorstFillFactorIndexes {
            get {
                return ResourceManager.GetString("WorstFillFactorIndexes", resourceCulture);
            }
        }
    }
}
