//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idera.SQLdm.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Idera.SQLdm.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} has Agent XPs {1}..
        /// </summary>
        internal static string Agentxpstatus_Body {
            get {
                return ResourceManager.GetString("Agentxpstatus_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent XPs are {1}.
        /// </summary>
        internal static string Agentxpstatus_Header {
            get {
                return ResourceManager.GetString("Agentxpstatus_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent XPs are {1} on {0}.
        /// </summary>
        internal static string Agentxpstatus_Todo {
            get {
                return ResourceManager.GetString("Agentxpstatus_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} has OLE Automation {1}..
        /// </summary>
        internal static string Automationstatus_Body {
            get {
                return ResourceManager.GetString("Automationstatus_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLE Automation is {1}.
        /// </summary>
        internal static string Automationstatus_Header {
            get {
                return ResourceManager.GetString("Automationstatus_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLE Automation is {1} on {0}.
        /// </summary>
        internal static string Automationstatus_Todo {
            get {
                return ResourceManager.GetString("Automationstatus_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - Session {3} has been blocking other sessions for {1} seconds.
        ///
        ///The session is being run on database [{2}] with application name &apos;{5}&apos; by user &apos;{4}&apos; on host &apos;{6}&apos;. 
        ///
        ///Last command issued: 
        ///
        ///{7}.
        /// </summary>
        internal static string Blockingprocess_Body {
            get {
                return ResourceManager.GetString("Blockingprocess_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session {3} blocking for {1} seconds.
        /// </summary>
        internal static string Blockingprocess_Header {
            get {
                return ResourceManager.GetString("Blockingprocess_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session {3} blocking for {1} seconds on {0}.
        /// </summary>
        internal static string Blockingprocess_Todo {
            get {
                return ResourceManager.GetString("Blockingprocess_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} has {1} sessions blocking other sessions..
        /// </summary>
        internal static string Blockingsessions_Body {
            get {
                return ResourceManager.GetString("Blockingsessions_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking sessions count is {1}.
        /// </summary>
        internal static string Blockingsessions_Header {
            get {
                return ResourceManager.GetString("Blockingsessions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking sessions count is {1} on {0}.
        /// </summary>
        internal static string Blockingsessions_Todo {
            get {
                return ResourceManager.GetString("Blockingsessions_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - SQL Agent job &apos;{2}&apos; failed with a Sql Severity of {5}. 
        ///
        ///The job started at {3} and was in step {4} which issued the command &apos;{8}&apos;.
        ///
        ///Sql Message ID: {6} 
        ///Message: 
        ///{7}.
        /// </summary>
        internal static string Bombedjob_Body {
            get {
                return ResourceManager.GetString("Bombedjob_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Agent job &apos;{2}&apos; failed.
        /// </summary>
        internal static string Bombedjob_Header {
            get {
                return ResourceManager.GetString("Bombedjob_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Agent job &apos;{2}&apos; failed on {0}.
        /// </summary>
        internal static string Bombedjob_Todo {
            get {
                return ResourceManager.GetString("Bombedjob_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} has {1} client computers connected..
        /// </summary>
        internal static string Clientcomputers_Body {
            get {
                return ResourceManager.GetString("Clientcomputers_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client computers is {1}.
        /// </summary>
        internal static string Clientcomputers_Header {
            get {
                return ResourceManager.GetString("Clientcomputers_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client computers is {1} on {0}.
        /// </summary>
        internal static string Clientcomputers_Todo {
            get {
                return ResourceManager.GetString("Clientcomputers_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} has the CLR configuration option  {1}..
        /// </summary>
        internal static string Clrstatus_Body {
            get {
                return ResourceManager.GetString("Clrstatus_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR configuration option  is {1}.
        /// </summary>
        internal static string Clrstatus_Header {
            get {
                return ResourceManager.GetString("Clrstatus_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR configuration option  is {1} on {0}.
        /// </summary>
        internal static string Clrstatus_Todo {
            get {
                return ResourceManager.GetString("Clrstatus_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL diagnostic manager collection service with service name {0} is {1}.
        /// </summary>
        internal static string Collectionservicestatus_Body {
            get {
                return ResourceManager.GetString("Collectionservicestatus_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLdm collection service is {1}.
        /// </summary>
        internal static string Collectionservicestatus_Header {
            get {
                return ResourceManager.GetString("Collectionservicestatus_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLdm collection service is {1}.
        /// </summary>
        internal static string Collectionservicestatus_Todo {
            get {
                return ResourceManager.GetString("Collectionservicestatus_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} has {2} user connections and is at {1:F2}% of the maximum connections allowed..
        /// </summary>
        internal static string Connections_Body {
            get {
                return ResourceManager.GetString("Connections_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User connections are at {1:F2}%.
        /// </summary>
        internal static string Connections_Header {
            get {
                return ResourceManager.GetString("Connections_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User connections are at {1:F2}% on {0}.
        /// </summary>
        internal static string Connections_Todo {
            get {
                return ResourceManager.GetString("Connections_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} is currently using {1:F2}% of the CPU-Baseline..
        /// </summary>
        internal static string Cpu_Baselined_Body {
            get {
                return ResourceManager.GetString("Cpu_Baselined_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} is currently using {1:F2}% of the CPU..
        /// </summary>
        internal static string Cpu_Body {
            get {
                return ResourceManager.GetString("Cpu_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server CPU usage is {1:F2}%.
        /// </summary>
        internal static string Cpu_Header {
            get {
                return ResourceManager.GetString("Cpu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server CPU usage is {1:F2}% on {0}.
        /// </summary>
        internal static string Cpu_Todo {
            get {
                return ResourceManager.GetString("Cpu_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} has {1:F2}% of the total allocated database file space in use.
        ///
        ///If this percentage appears incorrect, you may need to run DBCC UPDATEUSAGE to have SQL Server update the information..
        /// </summary>
        internal static string Datausedpercent_Body {
            get {
                return ResourceManager.GetString("Datausedpercent_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Data used is {1:F2}%.
        /// </summary>
        internal static string Datausedpercent_Header {
            get {
                return ResourceManager.GetString("Datausedpercent_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Data used is {1:F2}% on {0}.
        /// </summary>
        internal static string Datausedpercent_Todo {
            get {
                return ResourceManager.GetString("Datausedpercent_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - Database [{2}] has data files that are {1:F2}% full.
        ///
        ///If this percentage appears incorrect, you may need to run DBCC UPDATEUSAGE to have SQL Server update the information..
        /// </summary>
        internal static string Dbsize_Body {
            get {
                return ResourceManager.GetString("Dbsize_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data files are {1:F2}% full for database [{2}].
        /// </summary>
        internal static string Dbsize_Header {
            get {
                return ResourceManager.GetString("Dbsize_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data files are {1:F2}% full for database [{2}] on {0}.
        /// </summary>
        internal static string Dbsize_Todo {
            get {
                return ResourceManager.GetString("Dbsize_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - Database [{2}] has a status of {1}..
        /// </summary>
        internal static string Dbstatus_Body {
            get {
                return ResourceManager.GetString("Dbstatus_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database status for [{2}] is {1}.
        /// </summary>
        internal static string Dbstatus_Header {
            get {
                return ResourceManager.GetString("Dbstatus_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database status for [{2}] is {1} on {0}.
        /// </summary>
        internal static string Dbstatus_Todo {
            get {
                return ResourceManager.GetString("Dbstatus_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The Distributed Transaction Coordinator service has a status of {1}..
        /// </summary>
        internal static string Dtcother_Body {
            get {
                return ResourceManager.GetString("Dtcother_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTC is {1}.
        /// </summary>
        internal static string Dtcother_Header {
            get {
                return ResourceManager.GetString("Dtcother_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTC is {1} on {0}.
        /// </summary>
        internal static string Dtcother_Todo {
            get {
                return ResourceManager.GetString("Dtcother_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The Distributed Transaction Coordinator service is running..
        /// </summary>
        internal static string Dtcrunning_Body {
            get {
                return ResourceManager.GetString("Dtcrunning_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTC running.
        /// </summary>
        internal static string Dtcrunning_Header {
            get {
                return ResourceManager.GetString("Dtcrunning_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTC running on {0}.
        /// </summary>
        internal static string Dtcrunning_Todo {
            get {
                return ResourceManager.GetString("Dtcrunning_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The Distributed Transaction Coordinator service is stopped..
        /// </summary>
        internal static string Dtcstopped_Body {
            get {
                return ResourceManager.GetString("Dtcstopped_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTC stopped.
        /// </summary>
        internal static string Dtcstopped_Header {
            get {
                return ResourceManager.GetString("Dtcstopped_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTC stopped on {0}.
        /// </summary>
        internal static string Dtcstopped_Todo {
            get {
                return ResourceManager.GetString("Dtcstopped_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The SQL Server Agent service has a status of {1}..
        /// </summary>
        internal static string Execother_Body {
            get {
                return ResourceManager.GetString("Execother_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Agent is {1}.
        /// </summary>
        internal static string Execother_Header {
            get {
                return ResourceManager.GetString("Execother_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Agent is {1} on {0}.
        /// </summary>
        internal static string Execother_Todo {
            get {
                return ResourceManager.GetString("Execother_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The SQL Server Agent service is running..
        /// </summary>
        internal static string Execrunning_Body {
            get {
                return ResourceManager.GetString("Execrunning_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Agent running.
        /// </summary>
        internal static string Execrunning_Header {
            get {
                return ResourceManager.GetString("Execrunning_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Agent running on {0}.
        /// </summary>
        internal static string Execrunning_Todo {
            get {
                return ResourceManager.GetString("Execrunning_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The SQL Server Agent service is stopped..
        /// </summary>
        internal static string Execstopped_Body {
            get {
                return ResourceManager.GetString("Execstopped_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Agent stopped.
        /// </summary>
        internal static string Execstopped_Header {
            get {
                return ResourceManager.GetString("Execstopped_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Agent stopped on {0}.
        /// </summary>
        internal static string Execstopped_Todo {
            get {
                return ResourceManager.GetString("Execstopped_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The Full-Text Search service has a status of {1}..
        /// </summary>
        internal static string Fulltextother_Body {
            get {
                return ResourceManager.GetString("Fulltextother_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-Text Search is {1}.
        /// </summary>
        internal static string Fulltextother_Header {
            get {
                return ResourceManager.GetString("Fulltextother_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-Text Search is {1} on {0}.
        /// </summary>
        internal static string Fulltextother_Todo {
            get {
                return ResourceManager.GetString("Fulltextother_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The Full-Text Search service is running..
        /// </summary>
        internal static string Fulltextrunning_Body {
            get {
                return ResourceManager.GetString("Fulltextrunning_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-Text Search running.
        /// </summary>
        internal static string Fulltextrunning_Header {
            get {
                return ResourceManager.GetString("Fulltextrunning_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-Text Search running on {0}.
        /// </summary>
        internal static string Fulltextrunning_Todo {
            get {
                return ResourceManager.GetString("Fulltextrunning_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} has experienced {1:F0} I/O errors while reading or writing to data files..
        /// </summary>
        internal static string Io_Body {
            get {
                return ResourceManager.GetString("Io_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O error count is {1:F0}.
        /// </summary>
        internal static string Io_Header {
            get {
                return ResourceManager.GetString("Io_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O error count is {1:F0} on {0}.
        /// </summary>
        internal static string Io_Todo {
            get {
                return ResourceManager.GetString("Io_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - Database [{2}] has transaction log files that are {1:F2}% full.
        ///
        ///If this percentage appears incorrect, you may need to run DBCC UPDATEUSAGE to have SQL Server update the information..
        /// </summary>
        internal static string Logsize_Body {
            get {
                return ResourceManager.GetString("Logsize_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files are {1:F2}% full for database [{2}].
        /// </summary>
        internal static string Logsize_Header {
            get {
                return ResourceManager.GetString("Logsize_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files are {1:F2}% full for database [{2}] on {0}.
        /// </summary>
        internal static string Logsize_Todo {
            get {
                return ResourceManager.GetString("Logsize_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} has {1:F2}% of the total allocated database transaction log file space in use.
        ///
        ///If this percentage appears incorrect, you may need to run DBCC UPDATEUSAGE to have SQL Server update the information..
        /// </summary>
        internal static string Logusedpercent_Body {
            get {
                return ResourceManager.GetString("Logusedpercent_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Log used is {1:F2}%.
        /// </summary>
        internal static string Logusedpercent_Header {
            get {
                return ResourceManager.GetString("Logusedpercent_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Log used is {1:F2}% on {0}.
        /// </summary>
        internal static string Logusedpercent_Todo {
            get {
                return ResourceManager.GetString("Logusedpercent_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - SQL Agent job &apos;{2}&apos; started at {6} is in step &apos;{7}&apos; and has run for {5} seconds which is {3}% longer than the average of {4} seconds..
        /// </summary>
        internal static string Longrunningjob_Body {
            get {
                return ResourceManager.GetString("Longrunningjob_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Agent job &apos;{2}&apos; running {3}% long.
        /// </summary>
        internal static string Longrunningjob_Header {
            get {
                return ResourceManager.GetString("Longrunningjob_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Agent job &apos;{2}&apos; running {3}% long on {0}.
        /// </summary>
        internal static string Longrunningjob_Todo {
            get {
                return ResourceManager.GetString("Longrunningjob_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server {0} is no longer in SQL Diagnostic Manager maintenance mode..
        /// </summary>
        internal static string Maintenancemodeend_Body {
            get {
                return ResourceManager.GetString("Maintenancemodeend_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLdm maintenance mode ended.
        /// </summary>
        internal static string Maintenancemodeend_Header {
            get {
                return ResourceManager.GetString("Maintenancemodeend_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLdm maintenance mode ended on {0}.
        /// </summary>
        internal static string Maintenancemodeend_Todo {
            get {
                return ResourceManager.GetString("Maintenancemodeend_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server {0} is in SQL Diagnostic Manager maintenance mode..
        /// </summary>
        internal static string Maintenancemodestart_Body {
            get {
                return ResourceManager.GetString("Maintenancemodestart_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLdm maintenance mode started.
        /// </summary>
        internal static string Maintenancemodestart_Header {
            get {
                return ResourceManager.GetString("Maintenancemodestart_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLdm maintenance mode started on {0}.
        /// </summary>
        internal static string Maintenancemodestart_Todo {
            get {
                return ResourceManager.GetString("Maintenancemodestart_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} is currently using {1:F2}% of the server memory..
        /// </summary>
        internal static string Memory_Body {
            get {
                return ResourceManager.GetString("Memory_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server memory is {1:F2}%.
        /// </summary>
        internal static string Memory_Header {
            get {
                return ResourceManager.GetString("Memory_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server memory is {1:F2}% on {0}.
        /// </summary>
        internal static string Memory_Todo {
            get {
                return ResourceManager.GetString("Memory_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} has {1} replication transactions published by the Publisher but not received by the Distributor..
        /// </summary>
        internal static string Nondistributed_Body {
            get {
                return ResourceManager.GetString("Nondistributed_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Distributed transaction count is {1}.
        /// </summary>
        internal static string Nondistributed_Header {
            get {
                return ResourceManager.GetString("Nondistributed_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Distributed transactions count is {1} on {0}.
        /// </summary>
        internal static string Nondistributed_Todo {
            get {
                return ResourceManager.GetString("Nondistributed_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} has {1} unsubscribed replication transactions received by the Distributor and not received by a Subscriber..
        /// </summary>
        internal static string Nonsubscribed_Body {
            get {
                return ResourceManager.GetString("Nonsubscribed_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribed transaction count is {1}.
        /// </summary>
        internal static string Nonsubscribed_Header {
            get {
                return ResourceManager.GetString("Nonsubscribed_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribed transaction count is {1} on {0}.
        /// </summary>
        internal static string Nonsubscribed_Todo {
            get {
                return ResourceManager.GetString("Nonsubscribed_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} has unsubscribed replication transactions that have been holding at the Distributor for {3} hours {4} minutes {5} seconds ({1} total seconds)..
        /// </summary>
        internal static string Nonsubscribedtime_Body {
            get {
                return ResourceManager.GetString("Nonsubscribedtime_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribed transaction time is {3} hours {4} minutes {5} seconds ({1} total seconds).
        /// </summary>
        internal static string Nonsubscribedtime_Header {
            get {
                return ResourceManager.GetString("Nonsubscribedtime_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribed transaction time is {3} hours {4} minutes {5} seconds ({1} total seconds) on {0}.
        /// </summary>
        internal static string Nonsubscribedtime_Todo {
            get {
                return ResourceManager.GetString("Nonsubscribedtime_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The oldest open transaction previously alerted has ended and is no longer a problem..
        /// </summary>
        internal static string OldestopenEnded_Body {
            get {
                return ResourceManager.GetString("OldestopenEnded_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest open transaction ended.
        /// </summary>
        internal static string OldestopenEnded_Header {
            get {
                return ResourceManager.GetString("OldestopenEnded_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest open transaction ended on {0}.
        /// </summary>
        internal static string OldestopenEnded_Todo {
            get {
                return ResourceManager.GetString("OldestopenEnded_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - A transaction in session {6} has been running for {1} minute(s).
        ///
        ///The transaction is being run on database [{2}] with application name &apos;{3}&apos; by user &apos;{5}&apos; on host &apos;{4}&apos;. 
        ///
        ///Last command issued: 
        ///
        ///{7}.
        /// </summary>
        internal static string Opentran_Body {
            get {
                return ResourceManager.GetString("Opentran_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transaction in session {6} has been running for {1} minute(s).
        /// </summary>
        internal static string Opentran_Header {
            get {
                return ResourceManager.GetString("Opentran_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transaction in session {6} has been running for {1} minute(s) on {0}.
        /// </summary>
        internal static string Opentran_Todo {
            get {
                return ResourceManager.GetString("Opentran_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The operating system privileged CPU usage is {1:F2}%..
        /// </summary>
        internal static string Oscpuprivilegedtime_Body {
            get {
                return ResourceManager.GetString("Oscpuprivilegedtime_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS privileged CPU usage is {1:F2}%.
        /// </summary>
        internal static string Oscpuprivilegedtime_Header {
            get {
                return ResourceManager.GetString("Oscpuprivilegedtime_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS privileged CPU usage is {1:F2}% on {0}.
        /// </summary>
        internal static string Oscpuprivilegedtime_Todo {
            get {
                return ResourceManager.GetString("Oscpuprivilegedtime_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The operating system processor queue length is {1}..
        /// </summary>
        internal static string Oscpuprocessorqueuelength_Body {
            get {
                return ResourceManager.GetString("Oscpuprocessorqueuelength_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS processor queue length is {1}.
        /// </summary>
        internal static string Oscpuprocessorqueuelength_Header {
            get {
                return ResourceManager.GetString("Oscpuprocessorqueuelength_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS processor queue length is {1} on {0}.
        /// </summary>
        internal static string Oscpuprocessorqueuelength_Todo {
            get {
                return ResourceManager.GetString("Oscpuprocessorqueuelength_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The operating system CPU usage is {1:F2}%..
        /// </summary>
        internal static string Oscpuprocessortime_Body {
            get {
                return ResourceManager.GetString("Oscpuprocessortime_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS CPU usage is {1:F2}%.
        /// </summary>
        internal static string Oscpuprocessortime_Header {
            get {
                return ResourceManager.GetString("Oscpuprocessortime_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS CPU usage is {1:F2}% on {0}.
        /// </summary>
        internal static string Oscpuprocessortime_Todo {
            get {
                return ResourceManager.GetString("Oscpuprocessortime_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The operating system user CPU usage is {1:F2}%..
        /// </summary>
        internal static string Oscpuusertime_Body {
            get {
                return ResourceManager.GetString("Oscpuusertime_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS user CPU usage is {1:F2}%.
        /// </summary>
        internal static string Oscpuusertime_Header {
            get {
                return ResourceManager.GetString("Oscpuusertime_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS user CPU usage is {1:F2}% on {0}.
        /// </summary>
        internal static string Oscpuusertime_Todo {
            get {
                return ResourceManager.GetString("Oscpuusertime_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The operating system average disk queue length is {1:F2}..
        /// </summary>
        internal static string Osdiskaveragediskqueuelength_Body {
            get {
                return ResourceManager.GetString("Osdiskaveragediskqueuelength_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS average disk queue length is {1:F2}.
        /// </summary>
        internal static string Osdiskaveragediskqueuelength_Header {
            get {
                return ResourceManager.GetString("Osdiskaveragediskqueuelength_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS average disk queue length is {1:F2} on {0}.
        /// </summary>
        internal static string Osdiskaveragediskqueuelength_Todo {
            get {
                return ResourceManager.GetString("Osdiskaveragediskqueuelength_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The operating system physical disks are {1:F2}% busy..
        /// </summary>
        internal static string Osdiskphysicaldisktime_Body {
            get {
                return ResourceManager.GetString("Osdiskphysicaldisktime_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS disk time is currently {1:F2}%.
        /// </summary>
        internal static string Osdiskphysicaldisktime_Header {
            get {
                return ResourceManager.GetString("Osdiskphysicaldisktime_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS disk time is currently {1:F2}% on {0}.
        /// </summary>
        internal static string Osdiskphysicaldisktime_Todo {
            get {
                return ResourceManager.GetString("Osdiskphysicaldisktime_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The operating system is paging at {1:F2} pages/second..
        /// </summary>
        internal static string Osmemorypagespersecond_Body {
            get {
                return ResourceManager.GetString("Osmemorypagespersecond_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS paging is {1:F2} pages/second.
        /// </summary>
        internal static string Osmemorypagespersecond_Header {
            get {
                return ResourceManager.GetString("Osmemorypagespersecond_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS paging is {1:F2} pages/second on {0}.
        /// </summary>
        internal static string Osmemorypagespersecond_Todo {
            get {
                return ResourceManager.GetString("Osmemorypagespersecond_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The operating system has {1:F2}% of memory in use..
        /// </summary>
        internal static string Osmemoryusedpct_Body {
            get {
                return ResourceManager.GetString("Osmemoryusedpct_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS memory used is {1:F2}%.
        /// </summary>
        internal static string Osmemoryusedpct_Header {
            get {
                return ResourceManager.GetString("Osmemoryusedpct_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS memory used is {1:F2}% on {0}.
        /// </summary>
        internal static string Osmemoryusedpct_Todo {
            get {
                return ResourceManager.GetString("Osmemoryusedpct_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The operating system metrics data is available..
        /// </summary>
        internal static string Osmetricsstatusavail_Body {
            get {
                return ResourceManager.GetString("Osmetricsstatusavail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS metrics data available.
        /// </summary>
        internal static string Osmetricsstatusavail_Header {
            get {
                return ResourceManager.GetString("Osmetricsstatusavail_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS metrics data available on {0}.
        /// </summary>
        internal static string Osmetricsstatusavail_Todo {
            get {
                return ResourceManager.GetString("Osmetricsstatusavail_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The operating system metrics data is not available..
        /// </summary>
        internal static string Osmetricsstatusdisabled_Body {
            get {
                return ResourceManager.GetString("Osmetricsstatusdisabled_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS metrics data unavailable.
        /// </summary>
        internal static string Osmetricsstatusdisabled_Header {
            get {
                return ResourceManager.GetString("Osmetricsstatusdisabled_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS metrics data unavailable on {0}.
        /// </summary>
        internal static string Osmetricsstatusdisabled_Todo {
            get {
                return ResourceManager.GetString("Osmetricsstatusdisabled_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The operating system metrics data is not available because OLE Automation is not enabled..
        /// </summary>
        internal static string Osmetricsstatusother_Body {
            get {
                return ResourceManager.GetString("Osmetricsstatusother_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS metrics data unavailable.
        /// </summary>
        internal static string Osmetricsstatusother_Header {
            get {
                return ResourceManager.GetString("Osmetricsstatusother_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS metrics data unavailable on {0}.
        /// </summary>
        internal static string Osmetricsstatusother_Todo {
            get {
                return ResourceManager.GetString("Osmetricsstatusother_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The operating system metrics data is not available because the WMI service did not respond or could not be started..
        /// </summary>
        internal static string Osmetricsstatusunavail_Body {
            get {
                return ResourceManager.GetString("Osmetricsstatusunavail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS metrics data unavailable.
        /// </summary>
        internal static string Osmetricsstatusunavail_Header {
            get {
                return ResourceManager.GetString("Osmetricsstatusunavail_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS metrics data unavailable on {0}.
        /// </summary>
        internal static string Osmetricsstatusunavail_Todo {
            get {
                return ResourceManager.GetString("Osmetricsstatusunavail_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - Query Monitor returned {1} statements..
        /// </summary>
        internal static string Querymonitorstatus_Body {
            get {
                return ResourceManager.GetString("Querymonitorstatus_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Monitor returned {1} statements.
        /// </summary>
        internal static string Querymonitorstatus_Header {
            get {
                return ResourceManager.GetString("Querymonitorstatus_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Monitor returned {1} statements on {0}.
        /// </summary>
        internal static string Querymonitorstatus_Todo {
            get {
                return ResourceManager.GetString("Querymonitorstatus_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - {6}.
        /// </summary>
        internal static string Reorg_Body {
            get {
                return ResourceManager.GetString("Reorg_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragmentation &gt; {5}% on {1} table{2} in database [{3}].
        /// </summary>
        internal static string Reorg_Header {
            get {
                return ResourceManager.GetString("Reorg_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragmentation &gt; {5}% on {1} table{2} in database [{3}] on {0}.
        /// </summary>
        internal static string Reorg_Todo {
            get {
                return ResourceManager.GetString("Reorg_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - Session {2} which logged in at {3} has CPU time of {1:F2} seconds during the last refresh interval..
        /// </summary>
        internal static string Resourcelimit_Body {
            get {
                return ResourceManager.GetString("Resourcelimit_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session CPU time is {1:F2} seconds for session {2}.
        /// </summary>
        internal static string Resourcelimit_Header {
            get {
                return ResourceManager.GetString("Resourcelimit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session CPU time is {1:F2} seconds for session {2} on {0}.
        /// </summary>
        internal static string Resourcelimit_Todo {
            get {
                return ResourceManager.GetString("Resourcelimit_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} cannot be accessed. The SQL Server service is stopped, the user may not have been granted login permission to the server or the server is unavailable..
        /// </summary>
        internal static string Servernotaccessible_Body {
            get {
                return ResourceManager.GetString("Servernotaccessible_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server cannot be accessed.
        /// </summary>
        internal static string Servernotaccessible_Header {
            get {
                return ResourceManager.GetString("Servernotaccessible_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server cannot be accessed on {0}.
        /// </summary>
        internal static string Servernotaccessible_Todo {
            get {
                return ResourceManager.GetString("Servernotaccessible_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The SQL Server service status is {1}. 
        ///
        ///{3}.
        /// </summary>
        internal static string Serverother_Body {
            get {
                return ResourceManager.GetString("Serverother_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server is {1}.
        /// </summary>
        internal static string Serverother_Header {
            get {
                return ResourceManager.GetString("Serverother_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server is {1} on {0}.
        /// </summary>
        internal static string Serverother_Todo {
            get {
                return ResourceManager.GetString("Serverother_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} is paused..
        /// </summary>
        internal static string Serverpaused_Body {
            get {
                return ResourceManager.GetString("Serverpaused_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server paused.
        /// </summary>
        internal static string Serverpaused_Header {
            get {
                return ResourceManager.GetString("Serverpaused_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server paused on {0}.
        /// </summary>
        internal static string Serverpaused_Todo {
            get {
                return ResourceManager.GetString("Serverpaused_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} has a response time of {1} ms..
        /// </summary>
        internal static string Serverresponsetime_Body {
            get {
                return ResourceManager.GetString("Serverresponsetime_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server response time is {1} ms.
        /// </summary>
        internal static string Serverresponsetime_Header {
            get {
                return ResourceManager.GetString("Serverresponsetime_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server response time is {1} ms on {0}.
        /// </summary>
        internal static string Serverresponsetime_Todo {
            get {
                return ResourceManager.GetString("Serverresponsetime_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The SQL Server service is running..
        /// </summary>
        internal static string Serverrunning_Body {
            get {
                return ResourceManager.GetString("Serverrunning_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server running.
        /// </summary>
        internal static string Serverrunning_Header {
            get {
                return ResourceManager.GetString("Serverrunning_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server running on {0}.
        /// </summary>
        internal static string Serverrunning_Todo {
            get {
                return ResourceManager.GetString("Serverrunning_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - The SQL Server service is stopped..
        /// </summary>
        internal static string Serverstopped_Body {
            get {
                return ResourceManager.GetString("Serverstopped_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server stopped.
        /// </summary>
        internal static string Serverstopped_Header {
            get {
                return ResourceManager.GetString("Serverstopped_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server stopped on {0}.
        /// </summary>
        internal static string Serverstopped_Todo {
            get {
                return ResourceManager.GetString("Serverstopped_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance {0} - WMI is not available on the server.
        /// </summary>
        internal static string Wmistatus_Body {
            get {
                return ResourceManager.GetString("Wmistatus_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMI unavailable.
        /// </summary>
        internal static string Wmistatus_Header {
            get {
                return ResourceManager.GetString("Wmistatus_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMI unavailable on {0}.
        /// </summary>
        internal static string Wmistatus_Todo {
            get {
                return ResourceManager.GetString("Wmistatus_Todo", resourceCulture);
            }
        }
    }
}
