//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Installer_form_application.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MemoryRqdForSQLdmConsoleInMB {
            get {
                return ((int)(this["MemoryRqdForSQLdmConsoleInMB"]));
            }
            set {
                this["MemoryRqdForSQLdmConsoleInMB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int MemoryRqdForSQLdmServicesInMB {
            get {
                return ((int)(this["MemoryRqdForSQLdmServicesInMB"]));
            }
            set {
                this["MemoryRqdForSQLdmServicesInMB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230")]
        public int MemoryRqdForDashboardInMB {
            get {
                return ((int)(this["MemoryRqdForDashboardInMB"]));
            }
            set {
                this["MemoryRqdForDashboardInMB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int MemoryRqdForBufferInMB {
            get {
                return ((int)(this["MemoryRqdForBufferInMB"]));
            }
            set {
                this["MemoryRqdForBufferInMB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.1.0")]
        public string RestrictedIDVersionsForLocal {
            get {
                return ((string)(this["RestrictedIDVersionsForLocal"]));
            }
            set {
                this["RestrictedIDVersionsForLocal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.6.0.0")]
        public string RestrictedIDVersionForRemote {
            get {
                return ((string)(this["RestrictedIDVersionForRemote"]));
            }
            set {
                this["RestrictedIDVersionForRemote"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11.1.0")]
        public string SQLdmProductVersion {
            get {
                return ((string)(this["SQLdmProductVersion"]));
            }
            set {
                this["SQLdmProductVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MemoryRqdForSqlClrTypesInMB {
            get {
                return ((int)(this["MemoryRqdForSqlClrTypesInMB"]));
            }
            set {
                this["MemoryRqdForSqlClrTypesInMB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int MemoryRqdForSMOInMB {
            get {
                return ((int)(this["MemoryRqdForSMOInMB"]));
            }
            set {
                this["MemoryRqdForSMOInMB"] = value;
            }
        }
    }
}