//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idera.SQLdm.DesktopClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainFormLocation"]));
            }
            set {
                this["MainFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280, 960")]
        public global::System.Drawing.Size MainFormSize {
            get {
                return ((global::System.Drawing.Size)(this["MainFormSize"]));
            }
            set {
                this["MainFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int InvalidLicenseLimitFound_CheckboxState {
            get {
                return ((int)(this["InvalidLicenseLimitFound_CheckboxState"]));
            }
            set {
                this["InvalidLicenseLimitFound_CheckboxState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int InvalidLicenseProductFound_CheckboxState {
            get {
                return ((int)(this["InvalidLicenseProductFound_CheckboxState"]));
            }
            set {
                this["InvalidLicenseProductFound_CheckboxState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int InvalidLicenseFound_CheckboxState {
            get {
                return ((int)(this["InvalidLicenseFound_CheckboxState"]));
            }
            set {
                this["InvalidLicenseFound_CheckboxState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideAddServersWizardWelcomePage {
            get {
                return ((bool)(this["HideAddServersWizardWelcomePage"]));
            }
            set {
                this["HideAddServersWizardWelcomePage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NavigationPaneVisible {
            get {
                return ((bool)(this["NavigationPaneVisible"]));
            }
            set {
                this["NavigationPaneVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NavigationPaneUserViewsExpanded {
            get {
                return ((bool)(this["NavigationPaneUserViewsExpanded"]));
            }
            set {
                this["NavigationPaneUserViewsExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideTodayViewCommonTasks {
            get {
                return ((bool)(this["HideTodayViewCommonTasks"]));
            }
            set {
                this["HideTodayViewCommonTasks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TasksNavigationPaneCurrentViewPanelExpanded {
            get {
                return ((bool)(this["TasksNavigationPaneCurrentViewPanelExpanded"]));
            }
            set {
                this["TasksNavigationPaneCurrentViewPanelExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TasksViewDetailsPanelExpanded {
            get {
                return ((bool)(this["TasksViewDetailsPanelExpanded"]));
            }
            set {
                this["TasksViewDetailsPanelExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlertsNavigationPaneCurrentViewPanelExpanded {
            get {
                return ((bool)(this["AlertsNavigationPaneCurrentViewPanelExpanded"]));
            }
            set {
                this["AlertsNavigationPaneCurrentViewPanelExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlertsViewDetailsPanelExpanded {
            get {
                return ((bool)(this["AlertsViewDetailsPanelExpanded"]));
            }
            set {
                this["AlertsViewDetailsPanelExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlertsViewFilterOptionsPanelVisible {
            get {
                return ((bool)(this["AlertsViewFilterOptionsPanelVisible"]));
            }
            set {
                this["AlertsViewFilterOptionsPanelVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TasksViewFilterOptionsPanelVisible {
            get {
                return ((bool)(this["TasksViewFilterOptionsPanelVisible"]));
            }
            set {
                this["TasksViewFilterOptionsPanelVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideConsoleWhenMinimized {
            get {
                return ((bool)(this["HideConsoleWhenMinimized"]));
            }
            set {
                this["HideConsoleWhenMinimized"] = value;
            }
        }

        /// <summary>
        ///SQLDM-30480
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableBaseline
        {
            get
            {
                return ((bool)(this["EnableBaseline"]));
            }
            set
            {
                this["EnableBaseline"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BackgroundRefreshIntervalInMinutes {
            get {
                return ((int)(this["BackgroundRefreshIntervalInMinutes"]));
            }
            set {
                this["BackgroundRefreshIntervalInMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int ForegroundRefreshIntervalInSeconds {
            get {
                return ((int)(this["ForegroundRefreshIntervalInSeconds"]));
            }
            set {
                this["ForegroundRefreshIntervalInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormState {
            get {
                return ((int)(this["MainFormState"]));
            }
            set {
                this["MainFormState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int RealTimeChartHistoryLimitInMinutes {
            get {
                return ((int)(this["RealTimeChartHistoryLimitInMinutes"]));
            }
            set {
                this["RealTimeChartHistoryLimitInMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool ReportsNavigationPaneCurrentViewPanelExpanded {
            get {
                return ((bool)(this["ReportsNavigationPaneCurrentViewPanelExpanded"]));
            }
            set {
                this["ReportsNavigationPaneCurrentViewPanelExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReportsViewFilterOptionsPanelVisible {
            get {
                return ((bool)(this["ReportsViewFilterOptionsPanelVisible"]));
            }
            set {
                this["ReportsViewFilterOptionsPanelVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640, 500")]
        public global::System.Drawing.Size AlertConfigurationDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["AlertConfigurationDialogSize"]));
            }
            set {
                this["AlertConfigurationDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("270")]
        public int AlertConfigurationDialogDividerLocation {
            get {
                return ((int)(this["AlertConfigurationDialogDividerLocation"]));
            }
            set {
                this["AlertConfigurationDialogDividerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlertConfigurationDialogGroupByCategory {
            get {
                return ((bool)(this["AlertConfigurationDialogGroupByCategory"]));
            }
            set {
                this["AlertConfigurationDialogGroupByCategory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MainFormToolbarSettings {
            get {
                return ((string)(this["MainFormToolbarSettings"]));
            }
            set {
                this["MainFormToolbarSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("222")]
        public int ServerSummaryViewStatusPanelWidth {
            get {
                return ((int)(this["ServerSummaryViewStatusPanelWidth"]));
            }
            set {
                this["ServerSummaryViewStatusPanelWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125")]
        public int ServerSummaryViewRecentTrendsPanelHeight {
            get {
                return ((int)(this["ServerSummaryViewRecentTrendsPanelHeight"]));
            }
            set {
                this["ServerSummaryViewRecentTrendsPanelHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("207")]
        public int MainFormNavigationPanelSize {
            get {
                return ((int)(this["MainFormNavigationPanelSize"]));
            }
            set {
                this["MainFormNavigationPanelSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowServerSummaryControlHelpOnClick {
            get {
                return ((bool)(this["ShowServerSummaryControlHelpOnClick"]));
            }
            set {
                this["ShowServerSummaryControlHelpOnClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("261")]
        public int SessionsDetailsViewMainSplitter {
            get {
                return ((int)(this["SessionsDetailsViewMainSplitter"]));
            }
            set {
                this["SessionsDetailsViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("242")]
        public int SessionsLocksViewMainSplitter {
            get {
                return ((int)(this["SessionsLocksViewMainSplitter"]));
            }
            set {
                this["SessionsLocksViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("242")]
        public int ResourcesDiskSizeViewMainSplitter {
            get {
                return ((int)(this["ResourcesDiskSizeViewMainSplitter"]));
            }
            set {
                this["ResourcesDiskSizeViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("209")]
        public int SessionsBlockingViewMainSplitter {
            get {
                return ((int)(this["SessionsBlockingViewMainSplitter"]));
            }
            set {
                this["SessionsBlockingViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("202")]
        public int LogsViewLogsSplitter {
            get {
                return ((int)(this["LogsViewLogsSplitter"]));
            }
            set {
                this["LogsViewLogsSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public int LogsViewDataSplitter {
            get {
                return ((int)(this["LogsViewDataSplitter"]));
            }
            set {
                this["LogsViewDataSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("248")]
        public int DatabasesBackupsViewMainSplitter {
            get {
                return ((int)(this["DatabasesBackupsViewMainSplitter"]));
            }
            set {
                this["DatabasesBackupsViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("394")]
        public int DatabasesFilesViewMainSplitter {
            get {
                return ((int)(this["DatabasesFilesViewMainSplitter"]));
            }
            set {
                this["DatabasesFilesViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("221")]
        public int DatabasesFilesViewFilesSplitter {
            get {
                return ((int)(this["DatabasesFilesViewFilesSplitter"]));
            }
            set {
                this["DatabasesFilesViewFilesSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("221")]
        public int DatabasesFilesViewGroupsSplitter {
            get {
                return ((int)(this["DatabasesFilesViewGroupsSplitter"]));
            }
            set {
                this["DatabasesFilesViewGroupsSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("221")]
        public int DatabasesFilesViewLogsSplitter {
            get {
                return ((int)(this["DatabasesFilesViewLogsSplitter"]));
            }
            set {
                this["DatabasesFilesViewLogsSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("308")]
        public int DatabasesSummaryViewMainSplitter {
            get {
                return ((int)(this["DatabasesSummaryViewMainSplitter"]));
            }
            set {
                this["DatabasesSummaryViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230")]
        public int DatabasesTablesViewMainSplitter {
            get {
                return ((int)(this["DatabasesTablesViewMainSplitter"]));
            }
            set {
                this["DatabasesTablesViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("328")]
        public int ResourcesProcedureCacheViewMainSplitter {
            get {
                return ((int)(this["ResourcesProcedureCacheViewMainSplitter"]));
            }
            set {
                this["ResourcesProcedureCacheViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("206")]
        public int QueryMonitorViewMainSplitter {
            get {
                return ((int)(this["QueryMonitorViewMainSplitter"]));
            }
            set {
                this["QueryMonitorViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int QueryMonitorViewQuerySplitter {
            get {
                return ((int)(this["QueryMonitorViewQuerySplitter"]));
            }
            set {
                this["QueryMonitorViewQuerySplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("209")]
        public int ServicesSummaryViewMainSplitter {
            get {
                return ((int)(this["ServicesSummaryViewMainSplitter"]));
            }
            set {
                this["ServicesSummaryViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int ServicesFullTextViewMainSplitter {
            get {
                return ((int)(this["ServicesFullTextViewMainSplitter"]));
            }
            set {
                this["ServicesFullTextViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("246")]
        public int ServicesFullTextViewCatalogSplitter {
            get {
                return ((int)(this["ServicesFullTextViewCatalogSplitter"]));
            }
            set {
                this["ServicesFullTextViewCatalogSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("234")]
        public int ServicesAgentJobsViewMainSplitter {
            get {
                return ((int)(this["ServicesAgentJobsViewMainSplitter"]));
            }
            set {
                this["ServicesAgentJobsViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMessage_ManyServersSlowsReporting {
            get {
                return ((bool)(this["ShowMessage_ManyServersSlowsReporting"]));
            }
            set {
                this["ShowMessage_ManyServersSlowsReporting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowServerSummaryAnimations {
            get {
                return ((bool)(this["ShowServerSummaryAnimations"]));
            }
            set {
                this["ShowServerSummaryAnimations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SessionsDetailsViewDetailsVisible {
            get {
                return ((bool)(this["SessionsDetailsViewDetailsVisible"]));
            }
            set {
                this["SessionsDetailsViewDetailsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SessionsLocksViewChartVisible {
            get {
                return ((bool)(this["SessionsLocksViewChartVisible"]));
            }
            set {
                this["SessionsLocksViewChartVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ResourcesDiskSizeViewChartVisible {
            get {
                return ((bool)(this["ResourcesDiskSizeViewChartVisible"]));
            }
            set {
                this["ResourcesDiskSizeViewChartVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SessionsBlockingViewChartVisible {
            get {
                return ((bool)(this["SessionsBlockingViewChartVisible"]));
            }
            set {
                this["SessionsBlockingViewChartVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Requests")]
        public string SessionsLocksViewChartType {
            get {
                return ((string)(this["SessionsLocksViewChartType"]));
            }
            set {
                this["SessionsLocksViewChartType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Requests")]
        public string SessionsSummaryViewLocksChartType {
            get {
                return ((string)(this["SessionsSummaryViewLocksChartType"]));
            }
            set {
                this["SessionsSummaryViewLocksChartType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ServicesFullTextViewDetailsVisible {
            get {
                return ((bool)(this["ServicesFullTextViewDetailsVisible"]));
            }
            set {
                this["ServicesFullTextViewDetailsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ServicesAgentJobsViewHistoryVisible {
            get {
                return ((bool)(this["ServicesAgentJobsViewHistoryVisible"]));
            }
            set {
                this["ServicesAgentJobsViewHistoryVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ServicesSummaryViewChartVisible {
            get {
                return ((bool)(this["ServicesSummaryViewChartVisible"]));
            }
            set {
                this["ServicesSummaryViewChartVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Current Megabytes")]
        public string DatabasesFilesViewFilesChartType {
            get {
                return ((string)(this["DatabasesFilesViewFilesChartType"]));
            }
            set {
                this["DatabasesFilesViewFilesChartType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Current Megabytes")]
        public string DatabasesFilesViewGroupsChartType {
            get {
                return ((string)(this["DatabasesFilesViewGroupsChartType"]));
            }
            set {
                this["DatabasesFilesViewGroupsChartType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Current Megabytes")]
        public string DatabasesFilesViewLogsChartType {
            get {
                return ((string)(this["DatabasesFilesViewLogsChartType"]));
            }
            set {
                this["DatabasesFilesViewLogsChartType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Megabytes")]
        public string DatabasesFilesViewDisksChartType {
            get {
                return ((string)(this["DatabasesFilesViewDisksChartType"]));
            }
            set {
                this["DatabasesFilesViewDisksChartType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DatabasesFilesViewFilesTab {
            get {
                return ((int)(this["DatabasesFilesViewFilesTab"]));
            }
            set {
                this["DatabasesFilesViewFilesTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Megabytes")]
        public string DatabasesSummaryViewCapacityChartType {
            get {
                return ((string)(this["DatabasesSummaryViewCapacityChartType"]));
            }
            set {
                this["DatabasesSummaryViewCapacityChartType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Active Sessions")]
        public string DatabasesSummaryViewTrendsChartType {
            get {
                return ((string)(this["DatabasesSummaryViewTrendsChartType"]));
            }
            set {
                this["DatabasesSummaryViewTrendsChartType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DatabasesSummaryViewChartsVisible {
            get {
                return ((bool)(this["DatabasesSummaryViewChartsVisible"]));
            }
            set {
                this["DatabasesSummaryViewChartsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("References")]
        public string DatabasesTablesViewDependencyType {
            get {
                return ((string)(this["DatabasesTablesViewDependencyType"]));
            }
            set {
                this["DatabasesTablesViewDependencyType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Columns")]
        public string DatabasesTablesViewStatisticsType {
            get {
                return ((string)(this["DatabasesTablesViewStatisticsType"]));
            }
            set {
                this["DatabasesTablesViewStatisticsType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DatabasesTablesViewDetailsVisible {
            get {
                return ((bool)(this["DatabasesTablesViewDetailsVisible"]));
            }
            set {
                this["DatabasesTablesViewDetailsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DatabasesTablesViewDetailsTab {
            get {
                return ((int)(this["DatabasesTablesViewDetailsTab"]));
            }
            set {
                this["DatabasesTablesViewDetailsTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogsViewDetailsPanelVisible {
            get {
                return ((bool)(this["LogsViewDetailsPanelVisible"]));
            }
            set {
                this["LogsViewDetailsPanelVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogsViewLogsPanelVisible {
            get {
                return ((bool)(this["LogsViewLogsPanelVisible"]));
            }
            set {
                this["LogsViewLogsPanelVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ConsoleAlertNotificationDisplayOption {
            get {
                return ((int)(this["ConsoleAlertNotificationDisplayOption"]));
            }
            set {
                this["ConsoleAlertNotificationDisplayOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("133")]
        public int ServerConfigurationViewMainSplitter {
            get {
                return ((int)(this["ServerConfigurationViewMainSplitter"]));
            }
            set {
                this["ServerConfigurationViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ServerConfigurationViewDetailsPanelVisible {
            get {
                return ((bool)(this["ServerConfigurationViewDetailsPanelVisible"]));
            }
            set {
                this["ServerConfigurationViewDetailsPanelVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("195")]
        public int ServerDetailsViewMainSplitter {
            get {
                return ((int)(this["ServerDetailsViewMainSplitter"]));
            }
            set {
                this["ServerDetailsViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ServerDetailsViewChartVisible {
            get {
                return ((bool)(this["ServerDetailsViewChartVisible"]));
            }
            set {
                this["ServerDetailsViewChartVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QueryMonitorViewFiltersVisible {
            get {
                return ((bool)(this["QueryMonitorViewFiltersVisible"]));
            }
            set {
                this["QueryMonitorViewFiltersVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Megabytes")]
        public string ResourcesDiskSizeViewChartType {
            get {
                return ((string)(this["ResourcesDiskSizeViewChartType"]));
            }
            set {
                this["ResourcesDiskSizeViewChartType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ResourcesProcedureCacheViewChartsVisible {
            get {
                return ((bool)(this["ResourcesProcedureCacheViewChartsVisible"]));
            }
            set {
                this["ResourcesProcedureCacheViewChartsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hit Ratio")]
        public string ResourcesProcedureCacheViewChartType {
            get {
                return ((string)(this["ResourcesProcedureCacheViewChartType"]));
            }
            set {
                this["ResourcesProcedureCacheViewChartType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ResourcesProcedureCacheViewQuerySplitter {
            get {
                return ((int)(this["ResourcesProcedureCacheViewQuerySplitter"]));
            }
            set {
                this["ResourcesProcedureCacheViewQuerySplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("170")]
        public int TodayViewMainSplitter {
            get {
                return ((int)(this["TodayViewMainSplitter"]));
            }
            set {
                this["TodayViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int RepositoryConnectionTimeoutInSeconds {
            get {
                return ((int)(this["RepositoryConnectionTimeoutInSeconds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int RepositoryCommandTimeoutInSeconds {
            get {
                return ((int)(this["RepositoryCommandTimeoutInSeconds"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeSettings {
            get {
                return ((bool)(this["UpgradeSettings"]));
            }
            set {
                this["UpgradeSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RecentlyViewedSnapshotsPanelExpanded {
            get {
                return ((bool)(this["RecentlyViewedSnapshotsPanelExpanded"]));
            }
            set {
                this["RecentlyViewedSnapshotsPanelExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideCustomCounterWizardWelcomePage {
            get {
                return ((bool)(this["HideCustomCounterWizardWelcomePage"]));
            }
            set {
                this["HideCustomCounterWizardWelcomePage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideAddPermissionsWizardWelcomePage {
            get {
                return ((bool)(this["HideAddPermissionsWizardWelcomePage"]));
            }
            set {
                this["HideAddPermissionsWizardWelcomePage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMessage_OLEAutomationUnavailable {
            get {
                return ((bool)(this["ShowMessage_OLEAutomationUnavailable"]));
            }
            set {
                this["ShowMessage_OLEAutomationUnavailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMessage_WMIServiceUnreachable {
            get {
                return ((bool)(this["ShowMessage_WMIServiceUnreachable"]));
            }
            set {
                this["ShowMessage_WMIServiceUnreachable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMessage_LightweightPooling {
            get {
                return ((bool)(this["ShowMessage_LightweightPooling"]));
            }
            set {
                this["ShowMessage_LightweightPooling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCustomizeBaselineConfigurationMessage {
            get {
                return ((bool)(this["ShowCustomizeBaselineConfigurationMessage"]));
            }
            set {
                this["ShowCustomizeBaselineConfigurationMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int AlertRecommendationWarningThesholdPercentage {
            get {
                return ((int)(this["AlertRecommendationWarningThesholdPercentage"]));
            }
            set {
                this["AlertRecommendationWarningThesholdPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int AlertRecommendationCriticalThesholdPercentage {
            get {
                return ((int)(this["AlertRecommendationCriticalThesholdPercentage"]));
            }
            set {
                this["AlertRecommendationCriticalThesholdPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int AlertConfigurationDialogSizeUpgradeMarker {
            get {
                return ((int)(this["AlertConfigurationDialogSizeUpgradeMarker"]));
            }
            set {
                this["AlertConfigurationDialogSizeUpgradeMarker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int DatabasesMirroringViewMainSplitter {
            get {
                return ((int)(this["DatabasesMirroringViewMainSplitter"]));
            }
            set {
                this["DatabasesMirroringViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NavigationPaneTagsPanelExpanded {
            get {
                return ((bool)(this["NavigationPaneTagsPanelExpanded"]));
            }
            set {
                this["NavigationPaneTagsPanelExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection PreviouslyUsedReportServers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PreviouslyUsedReportServers"]));
            }
            set {
                this["PreviouslyUsedReportServers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreviouslyUsedReportFolder {
            get {
                return ((string)(this["PreviouslyUsedReportFolder"]));
            }
            set {
                this["PreviouslyUsedReportFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMessage_OLEAutomationDisabled {
            get {
                return ((bool)(this["ShowMessage_OLEAutomationDisabled"]));
            }
            set {
                this["ShowMessage_OLEAutomationDisabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeIndexesDataTableRemoveRows {
            get {
                return ((bool)(this["UpgradeIndexesDataTableRemoveRows"]));
            }
            set {
                this["UpgradeIndexesDataTableRemoveRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ServicesReplicationViewMainSplitter {
            get {
                return ((int)(this["ServicesReplicationViewMainSplitter"]));
            }
            set {
                this["ServicesReplicationViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public int ServicesReplicationViewGridSplitter {
            get {
                return ((int)(this["ServicesReplicationViewGridSplitter"]));
            }
            set {
                this["ServicesReplicationViewGridSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeadlockViewDetailsPanelExpanded {
            get {
                return ((bool)(this["DeadlockViewDetailsPanelExpanded"]));
            }
            set {
                this["DeadlockViewDetailsPanelExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("315")]
        public int DeadlockViewSplitterDistance {
            get {
                return ((int)(this["DeadlockViewSplitterDistance"]));
            }
            set {
                this["DeadlockViewSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideCustomReportsWizardWelcomePage {
            get {
                return ((bool)(this["HideCustomReportsWizardWelcomePage"]));
            }
            set {
                this["HideCustomReportsWizardWelcomePage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AlertRowLimit {
            get {
                return ((int)(this["AlertRowLimit"]));
            }
            set {
                this["AlertRowLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public int AlertsViewMainSplitter {
            get {
                return ((int)(this["AlertsViewMainSplitter"]));
            }
            set {
                this["AlertsViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public int ActiveAlertsViewMainSplitter {
            get {
                return ((int)(this["ActiveAlertsViewMainSplitter"]));
            }
            set {
                this["ActiveAlertsViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActiveAlertsViewDetailsPanelExpanded {
            get {
                return ((bool)(this["ActiveAlertsViewDetailsPanelExpanded"]));
            }
            set {
                this["ActiveAlertsViewDetailsPanelExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideReplicationTrendGraphs {
            get {
                return ((bool)(this["HideReplicationTrendGraphs"]));
            }
            set {
                this["HideReplicationTrendGraphs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ResourcesDiskViewChart1Type {
            get {
                return ((int)(this["ResourcesDiskViewChart1Type"]));
            }
            set {
                this["ResourcesDiskViewChart1Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ResourcesDiskViewChart2Type {
            get {
                return ((int)(this["ResourcesDiskViewChart2Type"]));
            }
            set {
                this["ResourcesDiskViewChart2Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ResourcesDiskViewChart3Type {
            get {
                return ((int)(this["ResourcesDiskViewChart3Type"]));
            }
            set {
                this["ResourcesDiskViewChart3Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ResourcesDiskViewChart4Type {
            get {
                return ((int)(this["ResourcesDiskViewChart4Type"]));
            }
            set {
                this["ResourcesDiskViewChart4Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideAddActionProviderWelcomePage {
            get {
                return ((bool)(this["HideAddActionProviderWelcomePage"]));
            }
            set {
                this["HideAddActionProviderWelcomePage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QueryMonitorViewGridVisible {
            get {
                return ((bool)(this["QueryMonitorViewGridVisible"]));
            }
            set {
                this["QueryMonitorViewGridVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int QueryMonitorViewDetailItems {
            get {
                return ((int)(this["QueryMonitorViewDetailItems"]));
            }
            set {
                this["QueryMonitorViewDetailItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TodayViewSelectedTabIndex {
            get {
                return ((int)(this["TodayViewSelectedTabIndex"]));
            }
            set {
                this["TodayViewSelectedTabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.idera.com/Trial-Center/SQL-diagnostic-manager/ ")]
        public string TrialCenterUrl {
            get {
                return ((string)(this["TrialCenterUrl"]));
            }
            set {
                this["TrialCenterUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ServerSummaryViewSelectedTabIndex {
            get {
                return ((int)(this["ServerSummaryViewSelectedTabIndex"]));
            }
            set {
                this["ServerSummaryViewSelectedTabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PulseAccountName {
            get {
                return ((string)(this["PulseAccountName"]));
            }
            set {
                this["PulseAccountName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PulseAccountKeepLoggedIn {
            get {
                return ((bool)(this["PulseAccountKeepLoggedIn"]));
            }
            set {
                this["PulseAccountKeepLoggedIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HidePulseTeaser {
            get {
                return ((bool)(this["HidePulseTeaser"]));
            }
            set {
                this["HidePulseTeaser"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TasksEnabled {
            get {
                return ((int)(this["TasksEnabled"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PopupShowPopupServerInfoWarCrit {
            get {
                return ((bool)(this["PopupShowPopupServerInfoWarCrit"]));
            }
            set {
                this["PopupShowPopupServerInfoWarCrit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActiveAlertsViewForecastPanelVisible {
            get {
                return ((bool)(this["ActiveAlertsViewForecastPanelVisible"]));
            }
            set {
                this["ActiveAlertsViewForecastPanelVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CollapseRibbon {
            get {
                return ((bool)(this["CollapseRibbon"]));
            }
            set {
                this["CollapseRibbon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DashboardDatabasesControlSelectedChart {
            get {
                return ((int)(this["DashboardDatabasesControlSelectedChart"]));
            }
            set {
                this["DashboardDatabasesControlSelectedChart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Office2007Black.isl")]
        public string ColorScheme {
            get {
                return ((string)(this["ColorScheme"]));
            }
            set {
                this["ColorScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("261")]
        public int TempdbViewMainSplitter {
            get {
                return ((int)(this["TempdbViewMainSplitter"]));
            }
            set {
                this["TempdbViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Idera.SQLdm.DesktopClient.Objects.GridSettings TempdbViewMainGrid {
            get {
                return ((global::Idera.SQLdm.DesktopClient.Objects.GridSettings)(this["TempdbViewMainGrid"]));
            }
            set {
                this["TempdbViewMainGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Version Store Cleanup Rate")]
        public string TempdbViewContentionButton {
            get {
                return ((string)(this["TempdbViewContentionButton"]));
            }
            set {
                this["TempdbViewContentionButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0")]
        public global::System.Windows.Point MainWindowLocation {
            get {
                return ((global::System.Windows.Point)(this["MainWindowLocation"]));
            }
            set {
                this["MainWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280,960")]
        public global::System.Windows.Size MainWindowSize {
            get {
                return ((global::System.Windows.Size)(this["MainWindowSize"]));
            }
            set {
                this["MainWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState MainWindowState {
            get {
                return ((global::System.Windows.WindowState)(this["MainWindowState"]));
            }
            set {
                this["MainWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0")]
        public global::System.Windows.Rect MainWindowRestoreBounds {
            get {
                return ((global::System.Windows.Rect)(this["MainWindowRestoreBounds"]));
            }
            set {
                this["MainWindowRestoreBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("225")]
        public double MainWindowNavigationPanelSize {
            get {
                return ((double)(this["MainWindowNavigationPanelSize"]));
            }
            set {
                this["MainWindowNavigationPanelSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PopupShowCriticalServersOnly {
            get {
                return ((bool)(this["PopupShowCriticalServersOnly"]));
            }
            set {
                this["PopupShowCriticalServersOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PopupEnableCriticalAlertSound {
            get {
                return ((bool)(this["PopupEnableCriticalAlertSound"]));
            }
            set {
                this["PopupEnableCriticalAlertSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PopupShowAllServerStatuses {
            get {
                return ((bool)(this["PopupShowAllServerStatuses"]));
            }
            set {
                this["PopupShowAllServerStatuses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string NeverShowPopupServerOk {
            get {
                return ((string)(this["NeverShowPopupServerOk"]));
            }
            set {
                this["NeverShowPopupServerOk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short OSCurrentDPI {
            get {
                return ((short)(this["OSCurrentDPI"]));
            }
            set {
                this["OSCurrentDPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("315")]
        public int BlockViewSplitterDistance {
            get {
                return ((int)(this["BlockViewSplitterDistance"]));
            }
            set {
                this["BlockViewSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMessage_WMIServiceTimedout {
            get {
                return ((bool)(this["ShowMessage_WMIServiceTimedout"]));
            }
            set {
                this["ShowMessage_WMIServiceTimedout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MultipleDesktopClients {
            get {
                return ((int)(this["MultipleDesktopClients"]));
            }
            set {
                this["MultipleDesktopClients"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SessionsBlockingViewLocksDeadlocksListVisible {
            get {
                return ((bool)(this["SessionsBlockingViewLocksDeadlocksListVisible"]));
            }
            set {
                this["SessionsBlockingViewLocksDeadlocksListVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int DatabaseAlwaysOnViewMainSplitter {
            get {
                return ((int)(this["DatabaseAlwaysOnViewMainSplitter"]));
            }
            set {
                this["DatabaseAlwaysOnViewMainSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int CachedViewCount {
            get {
                return ((int)(this["CachedViewCount"]));
            }
            set {
                this["CachedViewCount"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public string AuditEventsTopCount {
            get {
                return ((string)(this["AuditEventsTopCount"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.idera.com/buynow/diagnostic-manager?utm_source=sqldm&utm_medium=inprod" +
            "uct&utm_content=bn&utm_campaign=buynow")]
        public string ProductPurchaseUrl {
            get {
                return ((string)(this["ProductPurchaseUrl"]));
            }
            set {
                this["ProductPurchaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityOverviewDashboard {
            get {
                return ((string)(this["VisibilityOverviewDashboard"]));
            }
            set {
                this["VisibilityOverviewDashboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityOverviewDetails {
            get {
                return ((string)(this["VisibilityOverviewDetails"]));
            }
            set {
                this["VisibilityOverviewDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityOverviewConfiguration {
            get {
                return ((string)(this["VisibilityOverviewConfiguration"]));
            }
            set {
                this["VisibilityOverviewConfiguration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityOverviewActiveAlerts {
            get {
                return ((string)(this["VisibilityOverviewActiveAlerts"]));
            }
            set {
                this["VisibilityOverviewActiveAlerts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityOverviewTimeline {
            get {
                return ((string)(this["VisibilityOverviewTimeline"]));
            }
            set {
                this["VisibilityOverviewTimeline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilitySessionsSummary {
            get {
                return ((string)(this["VisibilitySessionsSummary"]));
            }
            set {
                this["VisibilitySessionsSummary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilitySessionsDetails {
            get {
                return ((string)(this["VisibilitySessionsDetails"]));
            }
            set {
                this["VisibilitySessionsDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilitySessionsLocks {
            get {
                return ((string)(this["VisibilitySessionsLocks"]));
            }
            set {
                this["VisibilitySessionsLocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilitySessionsBlocking {
            get {
                return ((string)(this["VisibilitySessionsBlocking"]));
            }
            set {
                this["VisibilitySessionsBlocking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityQueriesSignatureMode {
            get {
                return ((string)(this["VisibilityQueriesSignatureMode"]));
            }
            set {
                this["VisibilityQueriesSignatureMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityQueriesStatementMode {
            get {
                return ((string)(this["VisibilityQueriesStatementMode"]));
            }
            set {
                this["VisibilityQueriesStatementMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityQueriesQueryHistory {
            get {
                return ((string)(this["VisibilityQueriesQueryHistory"]));
            }
            set {
                this["VisibilityQueriesQueryHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityQueriesQueryWaits {
            get {
                return ((string)(this["VisibilityQueriesQueryWaits"]));
            }
            set {
                this["VisibilityQueriesQueryWaits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityResourcesSummary {
            get {
                return ((string)(this["VisibilityResourcesSummary"]));
            }
            set {
                this["VisibilityResourcesSummary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityResourcesCPU {
            get {
                return ((string)(this["VisibilityResourcesCPU"]));
            }
            set {
                this["VisibilityResourcesCPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityResourcesMemory {
            get {
                return ((string)(this["VisibilityResourcesMemory"]));
            }
            set {
                this["VisibilityResourcesMemory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityResourcesDisk {
            get {
                return ((string)(this["VisibilityResourcesDisk"]));
            }
            set {
                this["VisibilityResourcesDisk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityResourcesDiskSize {
            get {
                return ((string)(this["VisibilityResourcesDiskSize"]));
            }
            set {
                this["VisibilityResourcesDiskSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityResourcesFileActivity {
            get {
                return ((string)(this["VisibilityResourcesFileActivity"]));
            }
            set {
                this["VisibilityResourcesFileActivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityResourcesProcedureCache {
            get {
                return ((string)(this["VisibilityResourcesProcedureCache"]));
            }
            set {
                this["VisibilityResourcesProcedureCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityResourcesServerWaits {
            get {
                return ((string)(this["VisibilityResourcesServerWaits"]));
            }
            set {
                this["VisibilityResourcesServerWaits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityDatabaseSummary {
            get {
                return ((string)(this["VisibilityDatabaseSummary"]));
            }
            set {
                this["VisibilityDatabaseSummary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityDatabaseAvailabilityGroup {
            get {
                return ((string)(this["VisibilityDatabaseAvailabilityGroup"]));
            }
            set {
                this["VisibilityDatabaseAvailabilityGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityDatabaseTempdbSummary {
            get {
                return ((string)(this["VisibilityDatabaseTempdbSummary"]));
            }
            set {
                this["VisibilityDatabaseTempdbSummary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityDatabaseConfiguration {
            get {
                return ((string)(this["VisibilityDatabaseConfiguration"]));
            }
            set {
                this["VisibilityDatabaseConfiguration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityDatabaseFiles {
            get {
                return ((string)(this["VisibilityDatabaseFiles"]));
            }
            set {
                this["VisibilityDatabaseFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityDatabaseBackupRestore {
            get {
                return ((string)(this["VisibilityDatabaseBackupRestore"]));
            }
            set {
                this["VisibilityDatabaseBackupRestore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityDatabaseTablesIndexes {
            get {
                return ((string)(this["VisibilityDatabaseTablesIndexes"]));
            }
            set {
                this["VisibilityDatabaseTablesIndexes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityDatabaseMirroring {
            get {
                return ((string)(this["VisibilityDatabaseMirroring"]));
            }
            set {
                this["VisibilityDatabaseMirroring"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityServicesSummary {
            get {
                return ((string)(this["VisibilityServicesSummary"]));
            }
            set {
                this["VisibilityServicesSummary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityServicesSQLAgentJobs {
            get {
                return ((string)(this["VisibilityServicesSQLAgentJobs"]));
            }
            set {
                this["VisibilityServicesSQLAgentJobs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityServicesFullTextSearch {
            get {
                return ((string)(this["VisibilityServicesFullTextSearch"]));
            }
            set {
                this["VisibilityServicesFullTextSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public string VisibilityServicesReplication {
            get {
                return ((string)(this["VisibilityServicesReplication"]));
            }
            set {
                this["VisibilityServicesReplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Custom View 1.xml")]
        public string SelectedViewFileName {
            get {
                return ((string)(this["SelectedViewFileName"]));
            }
            set {
                this["SelectedViewFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection SavedViews {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SavedViews"]));
            }
            set {
                this["SavedViews"] = value;
            }
        }
    }
}
